### ISSUE TITLE
Constant timeouts when Roborock is offline

### ISSUE THREAD

**Issue by mjmeli** [humbertogontijo/homeassistant-roborock#109]
My vacuum is currently offline (disconnected from the internet). The integration is logging a ton of timeout errors to the logs.

![image](https://user-images.githubusercontent.com/6422129/210641366-ae674047-4a23-4667-996a-725c99fe0f01.png)

```
2023-01-04 15:12:59.281 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 316, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 121, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 381, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/roborock/vacuum.py", line 271, in state
    if not self._device_status:
  File "/config/custom_components/roborock/device.py", line 51, in _device_status
    return self.coordinator.data.get(self._device_id).status
AttributeError: 'NoneType' object has no attribute 'status'
2023-01-04 15:13:03.322 WARNING (MainThread) [custom_components.roborock.api.api] Timeout after 4 seconds waiting for get_map_v1 response
2023-01-04 15:13:03.323 WARNING (MainThread) [custom_components.roborock.camera] Unable to retrieve map data
2023-01-04 15:13:08.324 WARNING (MainThread) [custom_components.roborock.api.api] Timeout after 4 seconds waiting for get_map_v1 response
2023-01-04 15:13:08.325 WARNING (MainThread) [custom_components.roborock.camera] Unable to retrieve map data
2023-01-04 15:13:13.326 WARNING (MainThread) [custom_components.roborock.api.api] Timeout after 4 seconds waiting for get_map_v1 response
2023-01-04 15:13:13.327 WARNING (MainThread) [custom_components.roborock.camera] Unable to retrieve map data
2023-01-04 15:13:18.327 WARNING (MainThread) [custom_components.roborock.api.api] Timeout after 4 seconds waiting for get_map_v1 response
2023-01-04 15:13:18.329 WARNING (MainThread) [custom_components.roborock.camera] Unable to retrieve map data
2023-01-04 15:13:23.328 WARNING (MainThread) [custom_components.roborock.api.api] Timeout after 4 seconds waiting for get_map_v1 response
2023-01-04 15:13:23.329 WARNING (MainThread) [custom_components.roborock.camera] Unable to retrieve map data
2023-01-04 15:13:28.327 WARNING (MainThread) [custom_components.roborock.api.api] Timeout after 4 seconds waiting for get_map_v1 response
2023-01-04 15:13:28.329 WARNING (MainThread) [custom_components.roborock.camera] Unable to retrieve map data
2023-01-04 15:13:33.267 WARNING (MainThread) [custom_components.roborock.api.api] Timeout after 4 seconds waiting for get_status response
2023-01-04 15:13:33.269 WARNING (MainThread) [custom_components.roborock.api.api] Timeout after 4 seconds waiting for get_dnd_timer response
2023-01-04 15:13:33.270 WARNING (MainThread) [custom_components.roborock.api.api] Timeout after 4 seconds waiting for get_clean_summary response
2023-01-04 15:13:33.270 WARNING (MainThread) [custom_components.roborock.api.api] Timeout after 4 seconds waiting for get_consumable response
2023-01-04 15:13:33.328 WARNING (MainThread) [custom_components.roborock.api.api] Timeout after 4 seconds waiting for get_map_v1 response
2023-01-04 15:13:33.329 WARNING (MainThread) [custom_components.roborock.camera] Unable to retrieve map data
2023-01-04 15:13:37.272 WARNING (MainThread) [custom_components.roborock.api.api] Timeout after 4 seconds waiting for get_status response
2023-01-04 15:13:37.273 WARNING (MainThread) [custom_components.roborock.api.api] Timeout after 4 seconds waiting for get_dnd_timer response
2023-01-04 15:13:37.275 WARNING (MainThread) [custom_components.roborock.api.api] Timeout after 4 seconds waiting for get_clean_summary response
2023-01-04 15:13:37.276 WARNING (MainThread) [custom_components.roborock.api.api] Timeout after 4 seconds waiting for get_consumable response
2023-01-04 15:13:38.328 WARNING (MainThread) [custom_components.roborock.api.api] Timeout after 4 seconds waiting for get_map_v1 response
2023-01-04 15:13:38.329 WARNING (MainThread) [custom_components.roborock.camera] Unable to retrieve map data
2023-01-04 15:13:41.281 WARNING (MainThread) [custom_components.roborock.api.api] Timeout after 4 seconds waiting for get_status response
2023-01-04 15:13:41.283 WARNING (MainThread) [custom_components.roborock.api.api] Timeout after 4 seconds waiting for get_dnd_timer response
2023-01-04 15:13:41.284 WARNING (MainThread) [custom_components.roborock.api.api] Timeout after 4 seconds waiting for get_clean_summary response
2023-01-04 15:13:41.286 WARNING (MainThread) [custom_components.roborock.api.api] Timeout after 4 seconds waiting for get_consumable response
```

The logs keep happening and it is blowing up the log file. As the logs above show, it is retrying every 4 seconds. Seems like this should ease off, maybe with an exponential back-off.

In the meantime, I have to disable the integration when my device is offline.

**Comment by shred86** [comment]
I wonder if something like [tenacity](https://github.com/jd/tenacity) be used here. I don't fully understand how the re-attempts are currently being handled but it does appear to just try every 4 seconds for `get_prop` and every 5 seconds for `get_map_v1` indefinitely.

On a related note, it seems like timeouts are going to happen even when the device is connected. I think maybe having some logic where if a timeout self recovers after a certain number of attempts or time period, only log to debug. Otherwise, log a warning.

**Comment by humbertogontijo** [comment]
Version v0.0.26 was focused on reducing these logs

**Comment by mjmeli** [comment]
Thanks, I'm not seeing these logs anymore
