### ISSUE TITLE
Feature request: Ability to reset sensors

### ISSUE THREAD

**Issue by NickyM** [humbertogontijo/homeassistant-roborock#122]
Again, first thanks for an awesome integration :)

I would really like to be able to reset filter, main brush, side brush and sensor cleaning sensors with an service, so that I can be reset by doing a long press on a tile in the Xiaomi Vaccum Map Card.

Thanks. :)

**Comment by medfiras** [comment]
You can do it using send_command service

![image](https://user-images.githubusercontent.com/1859595/210973353-2d478bf4-d8c7-44e0-b362-57c87dfac87e.png)

**Comment by NickyM** [comment]
Thanks man!

**Comment by chatainsim** [comment]
Hello, thank you for your work 👍 
I've tried this but got a timeout:
```
Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/roborock/api/roborock_queue.py:14
Integration: Roborock (documentation, issues)
First occurred: 13:02:42 (4 occurrences)
Last logged: 13:04:49

websocket_api script: Error executing script. Unexpected error for call_service at pos 1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 958, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/config/custom_components/roborock/vacuum.py", line 516, in async_send_command
    return await self.send(command, params)
  File "/config/custom_components/roborock/device.py", line 90, in send
    return await self.coordinator.api.send_command(
  File "/config/custom_components/roborock/api/api.py", line 299, in send_command
    raise ex
  File "/config/custom_components/roborock/api/api.py", line 289, in send_command
    (response, err) = await queue.async_get(QUEUE_TIMEOUT)
  File "/config/custom_components/roborock/api/roborock_queue.py", line 14, in async_get
    return await asyncio.wait_for(self.get(), timeout=timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
```
Can you help me ?
Thanks

**Comment by humbertogontijo** [comment]
@chatainsim should be fixed in latest version

**Comment by chatainsim** [comment]
Hello, no more timeout but nothing change on the sensor.
I'll wait a little longer and tell you if it's working.

Thanks

**Comment by humbertogontijo** [comment]
There was a bug in v0.0.26 that was making the device unavailable. Can you try again with v0.0.27?

**Comment by chatainsim** [comment]
> There was a bug in v0.0.26 that was making the device unavailable. Can you try again with v0.0.27?

Thank you @humbertogontijo I confirm it's working now. Thank you for your amazing work!
