### ISSUE TITLE
The vacuum devices has only few sensors, bunch of errors in the log

### ISSUE THREAD

**Issue by eugenet8k** [humbertogontijo/homeassistant-roborock#137]
Latest version, integration created from scratch, config is saved at least once.

```
Logger: homeassistant.components.sensor
Source: custom_components/roborock/device.py:65 
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22)) 
First occurred: January 8, 2023 at 9:12:22 PM (1 occurrences) 
Last logged: January 8, 2023 at 9:12:22 PM

Error while setting up roborock platform for sensor
Traceback (most recent call last):
  File "/Users/pi/.homeassistant-venv/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/Users/pi/.homeassistant/custom_components/roborock/sensor.py", line 250, in async_setup_entry
    RoborockSensor(
  File "/Users/pi/.homeassistant/custom_components/roborock/sensor.py", line 272, in __init__
    self._attr_native_value = self._determine_native_value()
  File "/Users/pi/.homeassistant/custom_components/roborock/sensor.py", line 331, in _determine_native_value
    native_value = self.translate(
  File "/Users/pi/.homeassistant/custom_components/roborock/device.py", line 65, in translate
    return self.coordinator.translation.get(translation_key).get(attr).get(str(value))
AttributeError: 'NoneType' object has no attribute 'get'
```

```
Logger: homeassistant.components.vacuum
Source: custom_components/roborock/device.py:65 
Integration: Vacuum 
First occurred: January 8, 2023 at 9:12:22 PM (2 occurrences) 
Last logged: January 8, 2023 at 9:12:22 PM

Error adding entities for domain vacuum with platform roborock
Error while setting up roborock platform for vacuum
Traceback (most recent call last):
  File "/Users/pi/.homeassistant-venv/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/Users/pi/.homeassistant-venv/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/Users/pi/.homeassistant-venv/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 789, in add_to_platform_finish
    self.async_write_ha_state()
  File "/Users/pi/.homeassistant-venv/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/Users/pi/.homeassistant-venv/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 585, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/Users/pi/.homeassistant/custom_components/roborock/vacuum.py", line 302, in state_attributes
    data[ATTR_ERROR] = self.error
  File "/Users/pi/.homeassistant/custom_components/roborock/vacuum.py", line 358, in error
    return self.translate(self.translation_key, ATTR_ERROR, error_code)
  File "/Users/pi/.homeassistant/custom_components/roborock/device.py", line 65, in translate
    return self.coordinator.translation.get(translation_key).get(attr).get(str(value))
AttributeError: 'NoneType' object has no attribute 'get'
```

```
Logger: homeassistant
Source: custom_components/roborock/device.py:65 
Integration: Roborock 
First occurred: January 8, 2023 at 9:12:53 PM (4363 occurrences) 
Last logged: 11:12:36 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/Users/pi/.homeassistant-venv/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 168, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/Users/pi/.homeassistant-venv/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 316, in _async_refresh
    self.async_update_listeners()
  File "/Users/pi/.homeassistant-venv/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 121, in async_update_listeners
    update_callback()
  File "/Users/pi/.homeassistant-venv/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 381, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/Users/pi/.homeassistant-venv/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/Users/pi/.homeassistant-venv/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 585, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/Users/pi/.homeassistant/custom_components/roborock/vacuum.py", line 302, in state_attributes
    data[ATTR_ERROR] = self.error
  File "/Users/pi/.homeassistant/custom_components/roborock/vacuum.py", line 358, in error
    return self.translate(self.translation_key, ATTR_ERROR, error_code)
  File "/Users/pi/.homeassistant/custom_components/roborock/device.py", line 65, in translate
    return self.coordinator.translation.get(translation_key).get(attr).get(str(value))
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by humbertogontijo** [comment]
What language are you using in HA?

**Comment by eugenet8k** [comment]
It is all default to HA, English, etc.

<img width="658" alt="Снимок экрана 2023-01-10 в 1 36 07 PM" src="https://user-images.githubusercontent.com/4804824/211667440-b4ac7f72-73bc-44a1-8034-d5ef928e3303.png">

**Comment by eugenet8k** [comment]
@humbertogontijo that said, my OS has Russian as the default locale. Maybe that's the issue.

**Comment by humbertogontijo** [comment]
I have my os in English and HA in Portuguese and it gets Portuguese as the locale, so it will not use Russian in your case. In the next release I'll add a debug log for the translation so you can check what you are getting

**Comment by eugenet8k** [comment]
@humbertogontijo thanks for the update. Everything is back to normally now!
