### ISSUE TITLE
Unable to set up integration

### ISSUE THREAD

**Issue by BenchPressesBooks** [humbertogontijo/homeassistant-roborock#161]
When I go through the initial configuration steps where i provide my email, everything seems to go well and it authenticated using 2-FA successfully. After that I see in the integrations page where it just keeps reloading and saying

`Retrying setup: None`

Enabling debug logging shows the following:

```
Logger: homeassistant.config_entries
Source: config_entries.py:825
First occurred: 12:16:08 PM (1 occurrences)
Last logged: 12:16:08 PM
Config entry '<redacted>' for roborock integration not ready yet: None; Retrying in background
```

```
Logger: custom_components.roborock
Source: custom_components/roborock/api/api.py:220
Integration: Roborock ([documentation](https://github.com/humbertogontijo/homeassistant-roborock), [issues](https://github.com/humbertogontijo/homeassistant-roborock/issues))
First occurred: 11:03:21 AM (90 occurrences)
Last logged: 1:07:23 PM
Timeout after 4 seconds waiting for mqtt connection

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/roborock/api/api.py", line 216, in connect
    (_, err) = await connection_queue.async_get(timeout=QUEUE_TIMEOUT)
  File "/config/custom_components/roborock/api/roborock_queue.py", line 14, in async_get
    return await asyncio.wait_for(self.get(), timeout=timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/roborock/__init__.py", line 137, in _async_update_data
    device_prop = await self.api.get_prop(device_id)
  File "/config/custom_components/roborock/api/api.py", line 343, in get_prop
    [status, dnd_timer, clean_summary, consumable] = await asyncio.gather(
  File "/config/custom_components/roborock/api/api.py", line 318, in get_status
    status = await self.send_command(device_id, RoborockCommand.GET_STATUS)
  File "/config/custom_components/roborock/api/api.py", line 271, in send_command
    await self.validate_connection()
  File "/config/custom_components/roborock/api/api.py", line 227, in validate_connection
    await self.async_reconnect()
  File "/config/custom_components/roborock/api/api.py", line 194, in async_reconnect
    await self.connect()
  File "/config/custom_components/roborock/api/api.py", line 220, in connect
    raise RoborockException(f"Timeout after {QUEUE_TIMEOUT} seconds waiting for mqtt connection") from ex
custom_components.roborock.api.exceptions.RoborockException: Timeout after 4 seconds waiting for mqtt connection
```

I have verified that nothing is being blocked by the firewall, and am not seeing other issues that would point to an overall issue with this home assistant installation.

Home Assistant 2023.1.7
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230110.0 - latest 
Roborock integration version 0.0.25 (uninstalled, restarted, and installed 0.0.27, still getting the same results.)
Running on a raspberry pi 4 8gb

**Comment by BenchPressesBooks** [comment]
Unfortunately I get the same errors in v0.0.28 but also see significant instability where the addon errors out, causes HASS to reboot, and has a significant degredation in overall performance, moving back to 0.0.27 resolves all of that new bad behavior.

If it helps, we have two roborocks on our account, not just one so I am not sure if that is a factor here.

**Comment by Lash-L** [comment]
Hi @BenchPressesBooks are you still having issues?

**Comment by mf76130** [comment]
Hi,
Just installed it and i have the same issue.
But i only have 1 Roborock installed.
2023-04-11 06:32:50.952 ERROR (MainThread) [custom_components.roborock] Error fetching roborock data: Timeout after 4 seconds waiting for response

**Comment by BenchPressesBooks** [comment]
Hello unfortunately I am still having the same issues I was having before. I mostly have to leave this integration disabled except for trying to debug issues or home assistant cannot start / runs very slow because of the above error about mqtt timeouts.

**Comment by Lash-L** [comment]
Hi @BenchPressesBooks i would recommend updating when we release our new version and use local control and see if that shows improvements

**Comment by MyHomeAssistantDK** [comment]
Hey, I had the same problem (did not check logs, but same symptom at least).

I wondered if it could because I have two Roborock vacums on my roborock account. 
Tried to make a new account where I shared only one of the vacums (through the app) to new account. 
Then used the new account with one shared vacum to setup the integration.
Success.

Ofcause there might be another reason, but it is worth a try.

@Lash-L looking really forward to local control anyway ;)

/Curt

**Comment by Lash-L** [comment]
Hey @BenchPressesBooks - Have you had any luck recently?

**Comment by BenchPressesBooks** [comment]
Hello, I have updated between versions and I still see the same issues I see above. Unfortunately I do not keep this addon installed and just periodically come back to it because installing it and adding it to HASS on the integrations page will cause Home Assistant to start loop making it unusable for more than about 1 minute at a time while it is starting up.

I tried to diagnose further and thought it was because we had two vacuums on the account, but I have seen others with multiple vacuums who don't appear to have this issue so I am not sure.

**Comment by BenchPressesBooks** [comment]
`This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/roborock/__init__.py:112
Integration: Roborock (documentation, issues)
First occurred: 4:05:31 PM (1 occurrences)
Last logged: 4:05:31 PM

Error setting up entry <redacted> for roborock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/roborock/__init__.py", line 112, in async_setup_entry
    networking = await map_client.get_networking()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/roborock/api.py", line 489, in get_networking
    return await self.send_command(RoborockCommand.GET_NETWORK_INFO, return_type=NetworkInfo)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/roborock/api.py", line 389, in send_command
    response = await self._send_command(method, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/roborock/cloud_api.py", line 207, in _send_command
    return await self.send_message(roborock_message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/roborock/cloud_api.py", line 170, in send_message
    await self.validate_connection()
  File "/usr/local/lib/python3.11/site-packages/roborock/api.py", line 312, in validate_connection
    await self.async_connect()
  File "/usr/local/lib/python3.11/site-packages/roborock/cloud_api.py", line 158, in async_connect
    (connecting, connected_future) = self.sync_connect()
                                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/roborock/cloud_api.py", line 143, in sync_connect
    super().connect(host=self._mqtt_host, port=self._mqtt_port, keepalive=KEEPALIVE)
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
TimeoutError: timed out
`

`Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:137
First occurred: 4:05:35 PM (2 occurrences)
Last logged: 4:07:58 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/roborock/api.py", line 321, in _wait_response
    raise RoborockTimeout(f"id={request_id} Timeout after {QUEUE_TIMEOUT} seconds") from None
roborock.exceptions.RoborockTimeout: id=0 Timeout after 4 seconds
`

Home Assistant 2023.8.1
Supervisor 2023.07.1
Operating System 10.4
Frontend 20230802.0 - latest 
Roborock integration version 1.0.11
Running on a raspberry pi 4 8gb
