### ISSUE TITLE
Failed to set up - Check the logs message / Can't select vaccum platform

### ISSUE THREAD

**Issue by catalinescu-sudo** [humbertogontijo/homeassistant-roborock#165]
Hi, I can't make the intergration work for my S6 Pure.

After I have installed and confirmed the email code, the integrations says that failed to set up . When I press configure I have 2 radio buttons one camera one vacuum. After I choose vacuum and click save, the option is not regitered - the camera option is always enabled. And also the error are this 
<img width="391" alt="Screenshot 2023-01-26 at 14 46 19" src="https://user-images.githubusercontent.com/64982743/214843392-4829857d-ff31-4569-8371-d4f1078e758b.png">
<img width="182" alt="Screenshot 2023-01-26 at 14 46 04" src="https://user-images.githubusercontent.com/64982743/214843534-c9d63552-c0c1-4319-9e88-f75664d3779b.png">

`Logger: homeassistant.config_entries
Source: helpers/translation.py:298
First occurred: 2:40:17 PM (1 occurrences)
Last logged: 2:40:17 PM

Error setting up entry myemail@gmail.com for roborock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 327, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/roborock/__init__.py", line 86, in async_setup_entry
    translation = await get_translation(hass)
  File "/config/custom_components/roborock/__init__.py", line 51, in get_translation
    return await get_translation_from_hass(hass, "en")
  File "/config/custom_components/roborock/__init__.py", line 30, in get_translation_from_hass
    entity_translations = await async_get_translations(hass, language, "entity", [DOMAIN])
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 298, in async_get_translations
    components = {integration}
TypeError: unhashable type: 'list'
`

**Comment by catalinescu-sudo** [comment]
I have installed a previous version 0.0.26 and now is working but only like this
<img width="677" alt="Screenshot 2023-01-26 at 16 03 18" src="https://user-images.githubusercontent.com/64982743/214855432-14e8ddc9-12dd-4374-91fc-dfcfbb3c9aca.png">
<img width="471" alt="Screenshot 2023-01-26 at 16 03 11" src="https://user-images.githubusercontent.com/64982743/214855440-0cab4ec4-9b7d-4bda-9781-886a2b8b5f4d.png">

**Comment by neives** [comment]
Same thing here

**Comment by catalinescu-sudo** [comment]
Updates: installed latest version (0.0.28) and now I can't even start the process for config.

<img width="627" alt="Screenshot 2023-01-30 at 15 28 16" src="https://user-images.githubusercontent.com/64982743/215491101-676df7de-41f2-476b-bda3-d900c9413841.png">

**Comment by humbertogontijo** [comment]
@catalinescu-sudo Can you share the logs with me?

**Comment by catalinescu-sudo** [comment]
`This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/roborock/config_flow.py:130 
Integration: Roborock (documentation, issues) 
First occurred: 3:28:02 PM (3 occurrences) 
Last logged: 6:40:17 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 132, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 72, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 203, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 230, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/roborock/config_flow.py", line 58, in async_step_user
    return self._show_user_form()
  File "/config/custom_components/roborock/config_flow.py", line 130, in _show_user_form
    return self.async_show_menu(
AttributeError: 'RoborockFlowHandler' object has no attribute 'async_show_menu'
`

**Comment by humbertogontijo** [comment]
Do you have latest home assistant version?

**Comment by catalinescu-sudo** [comment]
A polite question for a dumb user :)) problem solved. Seems to work fine after home assistant update. Thank you
