### ISSUE TITLE
Failed to set up

### ISSUE THREAD

**Issue by grssll** [humbertogontijo/homeassistant-roborock#183]
Trying to install and it wont load:
Logs below:
Error setting up entry .....@gmail.com for roborock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/roborock/__init__.py", line 65, in async_setup_entry
    home_data = await api_client.get_home_data(user_data)
  File "/usr/local/lib/python3.10/site-packages/roborock/api.py", line 560, in get_home_data
    home_id_response = await home_id_request.request(
  File "/usr/local/lib/python3.10/site-packages/roborock/api.py", line 84, in request
    async with session.request(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 557, in _request
    resp = await req.send(conn)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 669, in send
    await writer.write_headers(status_line, self.headers)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/http_writer.py", line 130, in write_headers
    buf = _serialize_headers(status_line, headers)
  File "aiohttp/_http_writer.pyx", line 132, in aiohttp._http_writer._serialize_headers
  File "aiohttp/_http_writer.pyx", line 109, in aiohttp._http_writer.to_str
TypeError: Cannot serialize non-str key None

**Comment by humbertogontijo** [comment]
Should be fixed in v0.1.1

**Comment by grssll** [comment]
Thanks
