### ISSUE TITLE
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2396) when toggling the vacuum

### ISSUE THREAD

**Issue by kristofferR** [humbertogontijo/homeassistant-roborock#2]
Thanks so much for this, I've been waiting for a Roborock API implementation for HA for so long! Awesome work so far!

BTW, I posted about this project here, plenty of other people are excited too:
https://old.reddit.com/r/homeassistant/comments/zg5cvm/the_roborock_app_is_finally_supported_no_need_for/

That said, here is this projects' first bug report ;)

When I turn on/off my S7 MaxV I get this error:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/roborock/api.py:168
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 19:49:45 (1 occurrences)
Last logged: 19:49:45

[140638002292688] EOF occurred in violation of protocol (_ssl.c:2396)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1745, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1782, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py", line 358, in async_turn_on
    await self.hass.async_add_executor_job(partial(self.turn_on, **kwargs))
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/roborock/vacuum.py", line 79, in turn_on
    self._client.send_request(self._device.get('duid'), "app_start", [], True)
  File "/config/custom_components/roborock/api.py", line 296, in send_request
    self._mqtt_client.send_request(device_id, method, params, secure)
  File "/config/custom_components/roborock/api.py", line 194, in send_request
    self.send_msg_raw(device_id, 101, timestamp, payload)
  File "/config/custom_components/roborock/api.py", line 168, in send_msg_raw
    info = self.client.publish(
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1257, in publish
    rc = self._send_publish(
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 2693, in _send_publish
    return self._packet_queue(PUBLISH, packet, mid, qos, info)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3016, in _packet_queue
    return self.loop_write()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1577, in loop_write
    rc = self._packet_write()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 2464, in _packet_write
    write_length = self._sock_send(
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 649, in _sock_send
    return self._sock.send(buf)
  File "/usr/local/lib/python3.10/ssl.py", line 1206, in send
    return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2396)

```

**Comment by humbertogontijo** [comment]
I found this issue [637](https://github.com/eclipse/paho.mqtt.python/issues/637) within paho-mqtt repository. I'll look into it later today

**Comment by humbertogontijo** [comment]
I've deployed a new version with corrections mentioned in the paho-mqtt's issue. Since I didn't have this error, could you help me testing it?

**Comment by kristofferR** [comment]
So far I haven't got any errors, will report back if it reappears :)

**Comment by humbertogontijo** [comment]
Closing as complete. Feel free to create a new one if it persists

**Comment by Rena-2022** [comment]
> I've deployed a new version with corrections mentioned in the paho-mqtt's issue. Since I didn't have this error, could you help me testing it? @kristofferR

Hi When you are referring to corrections, what exactly you are referring to
