### ISSUE TITLE
Map occasionally stops working (IndexError: string index out of range)

### ISSUE THREAD

**Issue by kristofferR** [humbertogontijo/homeassistant-roborock#21]
Sometimes the map view just displays a blue background with the text "OK" in the middle of it.

Here's the log:
```
2022-12-14 17:37:45.363 WARNING (MainThread) [homeassistant.components.camera] Updating roborock camera took longer than the scheduled update interval 0:00:05
2022-12-14 17:37:45.365 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.roborock_s7_maxv is taking over 10 seconds
2022-12-14 17:37:45.367 ERROR (SyncWorker_2) [custom_components.roborock.camera] string index out of range
Traceback (most recent call last):
  File "/config/custom_components/roborock/camera.py", line 183, in update
    self._handle_map_data()
  File "/config/custom_components/roborock/camera.py", line 239, in _handle_map_data
    map_data, map_stored = self.get_map(
  File "/config/custom_components/roborock/camera.py", line 216, in get_map
    map_data = self.decode_map(
  File "/config/custom_components/roborock/camera.py", line 232, in decode_map
    return MapDataParserRoborock.parse(
  File "/config/custom_components/roborock/common/map_data_parser.py", line 87, in parse
    map_header_length = MapDataParserRoborock.get_int16(raw, 0x02)
  File "/config/custom_components/roborock/common/map_data_parser.py", line 312, in get_int16
    ((data[address + 0] << 0) & 0xFF) | \
IndexError: string index out of range
```

**Comment by Xyaren** [comment]
I noticed this aswell. 
Is it possible that the robot will unload the map when going into some kind of sleep state ?

**Comment by Nezz** [comment]
I had the same earlier today, hence #18. At least we can see the exception now. It has not happened since I made that change though.

**Comment by Nezz** [comment]
It looks like this happens when the header of the map data gets parsed. Looks like under some circumstances `get_map_v1` returns an empty string?

**Comment by humbertogontijo** [comment]
I've had the same issue. This is propably the #1 issue I'm worried about. Unfortunately I'm out for the holidays. I believe that this would require some sort of option within the config flow to agree with a dumb command being sent to "wakeup" the robot(which could cause a bit greater battery drain)

**Comment by Nezz** [comment]
I'm getting this when the robot is just charging. I don't see the point of updating the map at that point, so perhaps we should just stop requesting map updates when the robot is not cleaning?
```
Logger: custom_components.roborock.camera
Source: custom_components/roborock/common/map_data_parser.py:312
Integration: Roborock ([documentation](https://github.com/humbertogontijo/homeassistant-roborock), [issues](https://github.com/humbertogontijo/homeassistant-roborock/issues))
First occurred: 03:38:56 (834 occurrences)
Last logged: 10:38:41
```
