### ISSUE TITLE
Stuck on initializing after entering credentials

### ISSUE THREAD

**Issue by Fogh** [humbertogontijo/homeassistant-roborock#228]
## Version of the custom_component
0.1.2

## What vacuum are you using?
Roborock S6 MaxV

## Describe the bug

After entering credentials it keeps spinning and the integration just shows as initializing. From the logs it seems that the token is invalid for some reason

## Debug log

```text
2023-04-07 18:14:52.800 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration roborock which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-07 18:14:52.801 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-07 18:14:59.187 DEBUG (MainThread) [custom_components.roborock] Integration async setup entry: {'entry_id': 'REDACTED', 'version': 1, 'domain': 'roborock', 'title': 'REDACTED', 'data': {'username': 'REDACTED', 'user_data': {'uid': "REDACTED", 'tokentype': '', 'token': 'REDACTED', 'rruid': 'REDACTED', 'region': 'eu', 'countrycode': '45', 'country': 'DK', 'nickname': 'REDACTED', 'rriot': {'u': 'REDACTED', 's': 'REDACTED', 'h': 'REDACTED', 'k': 'REDACTED', 'r': {'r': 'EU', 'a': 'https://api-eu.roborock.com', 'm': 'ssl://mqtt-eu-3.roborock.com:8883', 'l': 'https://wood-eu.roborock.com'}}, 'tuyaDeviceState': 0, 'avatarurl': 'https://files.roborock.com/iottest/default_avatar.png'}, 'base_url': 'https://euiot.roborock.com'}, 'options': {'vacuum': {'include_shared': False}}, 'pref_disable_new_entities': False, 'pref_disable_polling': False, 'source': 'user', 'unique_id': 'REDACTED', 'disabled_by': None}
2023-04-07 18:14:59.187 DEBUG (MainThread) [custom_components.roborock] Getting home data
2023-04-07 18:15:03.466 ERROR (MainThread) [homeassistant.bootstrap] Error setting up integration roborock - received exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 100, in async_setup_component
    return await task
  File "/usr/src/homeassistant/homeassistant/setup.py", line 296, in _async_setup_component
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/roborock/__init__.py", line 81, in async_setup_entry
    home_data = await api_client.get_home_data(user_data)
  File "/usr/local/lib/python3.10/site-packages/roborock/api.py", line 594, in get_home_data
    raise RoborockException(home_response)
roborock.exceptions.RoborockException: {'code': 'auth.err', 'msg': 'auth.err.invalid.token', 'status': 'UNAUTHORIZED', 'timestamp': '2023-04-07T19:39:38.910+00:00'}
```

**Comment by Lash-L** [comment]
Just to double check, you haven't accidentally downloaded main instead of 1.2?

Has the integration worked in the past for you? Or is this your first setup?

Your vacuum is online and connected to the Roborock app?

**Comment by BerlinBased** [comment]
I have version 1.2 installed (first time) with the same stuck issue and here is the log:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 579, in async_remove
    await component.async_remove_entry(hass, self)
  File "/config/custom_components/xiaomi_miot_raw/__init__.py", line 185, in async_remove_entry
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1060, in async_remove
    raise UnknownEntry
homeassistant.config_entries.UnknownEntry

**Comment by Fogh** [comment]
> Just to double check, you haven't accidentally downloaded main instead of 1.2?
> 
> Has the integration worked in the past for you? Or is this your first setup?
> 
> Your vacuum is online and connected to the Roborock app?

Yes, it is using version 0.1.2. It is my first setup from a clean Home Assistant docker instance.

Vacuum is online in the app

**Comment by Fogh** [comment]
I found the issue. The time on my host was out of sync.. That causes problems with the access token
