### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by Nezz** [humbertogontijo/homeassistant-roborock#23]
My logs are filled with the following error in addition to #21:

Logger: homeassistant
Source: custom_components/roborock/vacuum.py:130
Integration: Roborock ([documentation](https://github.com/humbertogontijo/homeassistant-roborock), [issues](https://github.com/humbertogontijo/homeassistant-roborock/issues))
First occurred: 03:38:56 (625 occurrences)
Last logged: 10:38:38
Error doing job: Task exception was never retrieved

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 813, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/roborock/vacuum.py", line 125, in state
    return self.status
  File "/config/custom_components/roborock/vacuum.py", line 130, in status
    return STATE_CODE_TO_STRING.get(self._status.get("state"))
AttributeError: 'str' object has no attribute 'get'
```

**Comment by humbertogontijo** [comment]
Should be fixed now

**Comment by Nezz** [comment]
Thanks a lot :)
