### ISSUE TITLE
Map unavailalbe

### ISSUE THREAD

**Issue by talsalmona** [humbertogontijo/homeassistant-roborock#230]
Camera is unavailable after setting up the integration. Everything else (sensors and services) is available.
Tried following the suggestion [here](https://github.com/humbertogontijo/homeassistant-roborock/issues/105#issuecomment-1371061509) but that didn't solve the issue. Tried reinstalling and still have the same issue.

I'm getting the following error in the log. Debug log didn't have additional useful information that I could find.

Logger: custom_components.roborock.camera
Source: custom_components/roborock/common/map_data_parser.py:169
Integration: Roborock ([documentation](https://github.com/humbertogontijo/homeassistant-roborock), [issues](https://github.com/humbertogontijo/homeassistant-roborock/issues))
First occurred: 09:15:30 (1 occurrences)
Last logged: 09:15:30

'NoneType' object has no attribute 'is_empty'
Traceback (most recent call last):
  File "/config/custom_components/roborock/camera.py", line 221, in async_update
    await self._handle_map_data()
  File "/config/custom_components/roborock/camera.py", line 294, in _handle_map_data
    map_data = await self.get_map(
  File "/config/custom_components/roborock/camera.py", line 273, in get_map
    map_data = self.decode_map(
  File "/config/custom_components/roborock/camera.py", line 288, in decode_map
    return MapDataParserRoborock.parse(
  File "/config/custom_components/roborock/common/map_data_parser.py", line 169, in parse
    if not map_data.image.is_empty:
AttributeError: 'NoneType' object has no attribute 'is_empty'

Logger: homeassistant.components.camera
Source: custom_components/roborock/common/map_data_parser.py:169
Integration: Camera (documentation, issues)
First occurred: 09:06:08 (1 occurrences)
Last logged: 09:06:08

roborock: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 521, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in async_device_update
    await task
  File "/config/custom_components/roborock/camera.py", line 224, in async_update
    raise err
  File "/config/custom_components/roborock/camera.py", line 221, in async_update
    await self._handle_map_data()
  File "/config/custom_components/roborock/camera.py", line 294, in _handle_map_data
    map_data = await self.get_map(
  File "/config/custom_components/roborock/camera.py", line 273, in get_map
    map_data = self.decode_map(
  File "/config/custom_components/roborock/camera.py", line 288, in decode_map
    return MapDataParserRoborock.parse(
  File "/config/custom_components/roborock/common/map_data_parser.py", line 169, in parse
    if not map_data.image.is_empty:
AttributeError: 'NoneType' object has no attribute 'is_empty'

**Comment by Lash-L** [comment]
Are you on version 1.2?

**Comment by talsalmona** [comment]
I'm on 0.1.2

**Comment by talsalmona** [comment]
Maps entity became available after a number of hours. Not sure what did that. Perhaps because the robot had a cleaning cycle?

**Comment by talsalmona** [comment]
Seems to be working now
