### ISSUE TITLE
Total clean count sensor

### ISSUE THREAD

**Issue by tobiasbrage** [humbertogontijo/homeassistant-roborock#245]
I know it's been mentioned before but no one seems to have a solution.
If a sensor with the total clean count could be added that would be awesome, otherwise I have no way of counting the number of cleanings the vacuum has done and then make it drive to the bin.

It's in the logs so I hope it's "easy" to add?

2023-04-18 01:15:26.349 DEBUG (MainThread) [roborock.api] id=10 Response from get_clean_summary: 172703

**Comment by humbertogontijo** [comment]
Is 172703 your cleaning could?

**Comment by tobiasbrage** [comment]
In seconds I believe but that's fine. I just need a sensors with some kind of cleaning count either that being in times cleaned or in actual seconds/minutes.

**Comment by tobiasbrage** [comment]
I'm sorry, but I'm not quite sure what you mean?

**Comment by humbertogontijo** [comment]
Redownloading the integration from main branch (Make sure the dropbox with main selected is now grayed out when you hit the download button) 
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/96875138/232864338-acc720ca-e4a1-420b-9a6e-4f36b572b307.png">

**Comment by tobiasbrage** [comment]
Sadly that broke the integration.
I had to redownload the latest version to get it back again.

It wouldn't initialize when redownloading the main branch.

**Comment by humbertogontijo** [comment]
That version is about to be released. Do you have logs for that?

**Comment by Dis90** [comment]
I tried to update to main
```
Unexpected error fetching roborock data: name
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/roborock/coordinator.py", line 77, in _async_update_data
    await self.fill_device_prop(device_info)
  File "/config/custom_components/roborock/coordinator.py", line 60, in fill_device_prop
    device_prop = await self.api.get_prop(device_info.device.duid)
  File "/usr/local/lib/python3.10/site-packages/roborock/api.py", line 286, in get_prop
    dock_summary = await self.get_dock_summary(device_id, status.dock_type)
  File "/usr/local/lib/python3.10/site-packages/roborock/api.py", line 248, in get_dock_summary
    if RoborockDockTypeCode.name != "RoborockDockTypeCode":
  File "/usr/local/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: name
```

**Comment by tobiasbrage** [comment]
I believe i got the same error. The integration wouldn't initialize and gave the error "name". Same as your AttributeError from the log.

**Comment by Lash-L** [comment]
Try using main now

**Comment by Dis90** [comment]
I can also confirm that integration now works but no total clean count or total clean time sensors. There’s now many dock sensors reporting unknown status.

**Comment by Lash-L** [comment]
@Dis90 what dock do you have?

**Comment by Lash-L** [comment]
@Dis90 can you enable debug logging, restart, and then look for the result of get status in the logs and specifically what number is by dock_type

**Comment by Dis90** [comment]
Can't find anything related to dock :(

```
2023-04-20 16:46:04.830 DEBUG (MainThread) [custom_components.roborock] Getting home data
2023-04-20 16:46:06.186 DEBUG (MainThread) [custom_components.roborock] Got home data HomeData(id=xxxxx, name='My Home', lon=None, lat=None, geo_name=None, products=[HomeDataProduct(id='xxxxxx', name='Roborock S6 Pure', code=None, model='roborock.vacuum.a08', iconurl=None, attribute=None, capability=0, category='robot.vacuum.cleaner', schema=[HomeDataProductSchema(id='101', name='rpc_request', code='rpc_request', mode='rw', type='RAW', product_property=None, desc=None), HomeDataProductSchema(id='102', name='rpc_response', code='rpc_response', mode='rw', type='RAW', product_property=None, desc=None), HomeDataProductSchema(id='120', name='错误代码', code='error_code', mode='ro', type='ENUM', product_property=None, desc=None), HomeDataProductSchema(id='121', name='设备状态', code='state', mode='ro', type='ENUM', product_property=None, desc=None), HomeDataProductSchema(id='122', name='设备电量', code='battery', mode='ro', type='ENUM', product_property=None, desc=None), HomeDataProductSchema(id='123', name='清扫模式', code='fan_power', mode='rw', type='ENUM', product_property=None, desc=None), HomeDataProductSchema(id='124', name='拖地模式', code='water_box_mode', mode='rw', type='ENUM', product_property=None, desc=None), HomeDataProductSchema(id='125', name='主刷寿命', code='main_brush_life', mode='rw', type='VALUE', product_property=None, desc=None), HomeDataProductSchema(id='126', name='边刷寿命', code='side_brush_life', mode='rw', type='VALUE', product_property=None, desc=None), HomeDataProductSchema(id='127', name='滤网寿命', code='filter_life', mode='rw', type='VALUE', product_property=None, desc=None), HomeDataProductSchema(id='128', name='额外状态', code='additional_props', mode='ro', type='RAW', product_property=None, desc=None), HomeDataProductSchema(id='130', name='完成事件', code='task_complete', mode='ro', type='RAW', product_property=None, desc=None), HomeDataProductSchema(id='131', name='电量不足任务取消', code='task_cancel_low_power', mode='ro', type='RAW', product_property=None, desc=None), HomeDataProductSchema(id='132', name='运动中任务取消', code='task_cancel_in_motion', mode='ro', type='RAW', product_property=None, desc=None), HomeDataProductSchema(id='133', name='充电状态', code='charge_status', mode='ro', type='RAW', product_property=None, desc=None), HomeDataProductSchema(id='134', name='烘干状态', code='drying_status', mode='ro', type='RAW', product_property=None, desc=None)])], devices=[HomeDataDevice(duid='40LMP7IZg9A52oGVYRGj67', name='Carlos', local_key='F4PoBkfOTwlvDxie', fv='02.13.68', attribute=None, active_time=1671259572, runtime_env=None, time_zone_id='Europe/Helsinki', icon_url='', product_id='6t5OGALwYyq9vFnl62BYuW', lon=None, lat=None, share=False, share_time=None, online=True, pv='1.0', room_id=None, tuya_uuid=None, tuya_migrated=False, extra='{"xxxx": "xxxx"}', sn=None, feature_set=None, new_feature_set=None, device_status=HomeDataDeviceStatus(id=None, name=None, code=None, model=None, icon_url=None, attribute=None, capability=None, category=None, schema=None), silent_ota_switch=False)], received_devices=[], rooms=[HomeDataRoom(id=10099500, name='Kylpyhuone'), HomeDataRoom(id=10099497, name='Käytävä'), HomeDataRoom(id=10099485, name='Master'), HomeDataRoom(id=9691218, name='Tuulikaappi'), HomeDataRoom(id=9691215, name='Vessa'), HomeDataRoom(id=7140420, name='Eteinen'), HomeDataRoom(id=7140401, name='Toimisto'), HomeDataRoom(id=7140391, name='xxxxxx huone'), HomeDataRoom(id=7132112, name='Keittiö'), HomeDataRoom(id=7132110, name='Olohuone'), HomeDataRoom(id=7132107, name='Pikkuhuone')])
2023-04-20 16:46:07.756 DEBUG (MainThread) [custom_components.roborock.coordinator] Finished fetching roborock data in 0.253 seconds (success: True)
2023-04-20 16:46:07.772 DEBUG (MainThread) [custom_components.roborock.sensor] It seems the roborock.vacuum.a08 does not support the last_clean_start as the initial value is None
2023-04-20 16:46:07.772 DEBUG (MainThread) [custom_components.roborock.sensor] It seems the roborock.vacuum.a08 does not support the last_clean_end as the initial value is None
2023-04-20 16:46:07.772 DEBUG (MainThread) [custom_components.roborock.sensor] It seems the roborock.vacuum.a08 does not support the last_clean_duration as the initial value is None
2023-04-20 16:46:07.772 DEBUG (MainThread) [custom_components.roborock.sensor] It seems the roborock.vacuum.a08 does not support the last_clean_area as the initial value is None
2023-04-20 16:46:07.773 DEBUG (MainThread) [custom_components.roborock.sensor] It seems the roborock.vacuum.a08 does not support the clean_history_total_duration as the initial value is None
2023-04-20 16:46:07.773 DEBUG (MainThread) [custom_components.roborock.sensor] It seems the roborock.vacuum.a08 does not support the clean_history_total_area as the initial value is None
2023-04-20 16:46:07.773 DEBUG (MainThread) [custom_components.roborock.sensor] It seems the roborock.vacuum.a08 does not support the clean_history_count as the initial value is None
2023-04-20 16:46:07.773 DEBUG (MainThread) [custom_components.roborock.sensor] It seems the roborock.vacuum.a08 does not support the clean_history_dust_collection_count as the initial value is None
2023-04-20 16:46:07.783 DEBUG (MainThread) [custom_components.roborock.camera] Retrieving map from Roborock MQTT
2023-04-20 16:46:08.168 DEBUG (MainThread) [custom_components.roborock.camera] Map data retrieved
2023-04-20 16:46:08.168 DEBUG (MainThread) [custom_components.roborock.camera] Map is ok
2023-04-20 16:46:37.424 DEBUG (MainThread) [custom_components.roborock.coordinator] Finished fetching roborock data in 0.258 seconds (success: True)
2023-04-20 16:47:07.466 DEBUG (MainThread) [custom_components.roborock.coordinator] Finished fetching roborock data in 0.301 seconds (success: True)
2023-04-20 16:47:37.481 DEBUG (MainThread) [custom_components.roborock.coordinator] Finished fetching roborock data in 0.314 seconds (success: True)
2023-04-20 16:48:07.418 DEBUG (MainThread) [custom_components.roborock.coordinator] Finished fetching roborock data in 0.253 seconds (success: True)
```

**Comment by Lash-L** [comment]
@Dis90 You specifically need to find get_status in the logs. If you don't see it, open Developper tools, services, then send get_status

![image](https://user-images.githubusercontent.com/20257911/233388581-8296119f-b755-4f6f-a214-6e4c827188c5.png)

**Comment by Dis90** [comment]
It seems like debug logging for Roborock was not enough. Here's log:

```
2023-04-20 16:59:31.500 DEBUG (MainThread) [roborock.cloud_api] id=71299 Requesting method get_status with None
2023-04-20 16:59:31.501 DEBUG (MainThread) [roborock.cloud_api] id=43219 Requesting method get_dnd_timer with None
2023-04-20 16:59:31.502 DEBUG (MainThread) [roborock.cloud_api] id=44374 Requesting method get_clean_summary with None
2023-04-20 16:59:31.503 DEBUG (MainThread) [roborock.cloud_api] id=14524 Requesting method get_consumable with None
2023-04-20 16:59:31.588 DEBUG (MainThread) [roborock.cloud_api] id=71299 Response from get_status: {'msg_ver': 2, 'msg_seq': 1696, 'state': 8, 'battery': 100, 'clean_time': 1861, 'clean_area': 27132500, 'error_code': 0, 'map_present': 1, 'in_cleaning': 0, 'in_returning': 0, 'in_fresh_state': 1, 'lab_status': 3, 'water_box_status': 0, 'fan_power': 103, 'dnd_enabled': 0, 'map_status': 3, 'is_locating': 0, 'lock_status': 0}
2023-04-20 16:59:31.627 DEBUG (MainThread) [roborock.cloud_api] id=43219 Response from get_dnd_timer: {'start_hour': 22, 'start_minute': 0, 'end_hour': 8, 'end_minute': 0, 'enabled': 1}
2023-04-20 16:59:31.631 DEBUG (MainThread) [roborock.cloud_api] id=44374 Response from get_clean_summary: [297526, 4309707500, 260, [1681952400, 1681866001, 1681779601, 1681693200, 1681645328, 1681641905, 1681606801, 1681520401, 1681434001, 1681347601, 1681261201, 1681174801, 1681088401, 1681002002, 1680915601, 1680829200, 1680742801, 1680656401, 1680570001, 1680483600]]
2023-04-20 16:59:31.633 DEBUG (MainThread) [roborock.cloud_api] id=14524 Response from get_consumable: {'main_brush_work_time': 298523, 'side_brush_work_time': 298523, 'filter_work_time': 298523, 'filter_element_work_time': 0, 'sensor_dirty_time': 66694}
2023-04-20 16:59:31.636 DEBUG (MainThread) [roborock.cloud_api] id=19086 Requesting method get_dust_collection_mode with None
2023-04-20 16:59:31.721 DEBUG (MainThread) [roborock.cloud_api] id=19086 Response from get_dust_collection_mode: unknown_method
2023-04-20 16:59:31.722 DEBUG (MainThread) [custom_components.roborock.coordinator] Finished fetching roborock data in 0.222 seconds (success: True)
```

**Comment by Dis90** [comment]
get_clean_summary: [297526, 4309707500, 260,
I think these values are 297526=Total Time in second, 4309707500=Total Area in some weird format (app shows 4310m2, 260=Cycles

**Comment by q1t1** [comment]
Hi,

Roborock s5 Max owner here ^^.

If I download 0.1.2 version, I don't have the totoal count entity.

If I download the main one, I have it but I'm loosing the main entity, the vacuum itself !

Can you please advise ?

**Comment by Lash-L** [comment]
@q1t1 can you please share your logs?

**Comment by q1t1** [comment]
The debugging is enabled but don't see any logs...

In which log may I found it ?

**Comment by Lash-L** [comment]
In the home assistant log- you should see it say vacuum platform failed to set up or something along those lines

**Comment by q1t1** [comment]
I will try to download the full log when I'm home.

**Comment by q1t1** [comment]
After installing main from scratch :

Logger: homeassistant.components.select
Source: custom_components/roborock/select.py:56
Integration: Select (documentation, issues)
First occurred: 18:28:47 (1 occurrences)
Last logged: 18:28:47

```
Error while setting up roborock platform for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/roborock/select.py", line 79, in async_setup_entry
    if description.options_lambda(device_info.model_specification) is not None:
  File "/config/custom_components/roborock/select.py", line 56, in <lambda>
    options_lambda=lambda data: data.mop_mode_code.values(),
AttributeError: 'NoneType' object has no attribute 'values'
```

Logger: homeassistant.components.vacuum
Source: custom_components/roborock/vacuum.py:331
Integration: Vacuum (documentation, issues)
First occurred: 18:28:47 (2 occurrences)
Last logged: 18:28:48

```
Error adding entities for domain vacuum with platform roborock
Error while setting up roborock platform for vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 643, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/config/custom_components/roborock/vacuum.py", line 358, in capability_attributes
    capability_attributes[ATTR_MOP_MODE_LIST] = self.mop_mode_list
  File "/config/custom_components/roborock/vacuum.py", line 331, in mop_mode_list
    return self._model_specification.mop_mode_code.values()
AttributeError: 'NoneType' object has no attribute 'values'
```

**Comment by Lash-L** [comment]
@humbertogontijo I know this part of the code is going to change anyways with the new subclasses of Status, but I realized that our options_lambda should be lambda data: data.mop_mode_code.values() if data.mop_mode_code else None 
but with the new system

If you are already working on it, just wanted to give you a heads up. Otherwise when I work on it I will make the change

**Comment by q1t1** [comment]
--
Quentin Couvreux

**Comment by q1t1** [comment]
And this with 0.1.2 :

```
2023-05-05 18:38:09.781 DEBUG (MainThread) [custom_components.roborock.sensor] It seems the roborock.vacuum.s5e does not support the last_clean_start as the initial value is None
2023-05-05 18:38:09.781 DEBUG (MainThread) [custom_components.roborock.sensor] It seems the roborock.vacuum.s5e does not support the last_clean_end as the initial value is None
2023-05-05 18:38:09.782 DEBUG (MainThread) [custom_components.roborock.sensor] It seems the roborock.vacuum.s5e does not support the last_clean_duration as the initial value is None
2023-05-05 18:38:09.782 DEBUG (MainThread) [custom_components.roborock.sensor] It seems the roborock.vacuum.s5e does not support the last_clean_area as the initial value is None
2023-05-05 18:38:09.783 DEBUG (MainThread) [custom_components.roborock.sensor] It seems the roborock.vacuum.s5e does not support the clean_history_total_duration as the initial value is None
2023-05-05 18:38:09.783 DEBUG (MainThread) [custom_components.roborock.sensor] It seems the roborock.vacuum.s5e does not support the clean_history_total_area as the initial value is None
2023-05-05 18:38:09.783 DEBUG (MainThread) [custom_components.roborock.sensor] It seems the roborock.vacuum.s5e does not support the clean_history_count as the initial value is None
2023-05-05 18:38:09.784 DEBUG (MainThread) [custom_components.roborock.sensor] It seems the roborock.vacuum.s5e does not support the clean_history_dust_collection_count as the initial value is None
```

**Comment by humbertogontijo** [comment]
@q1t1 try redownloading main

**Comment by q1t1** [comment]
I tried multiple times.

--
Quentin Couvreux



Le sam. 6 mai 2023, 12:34, Humberto Gontijo ***@***.***> a
écrit :

**Comment by humbertogontijo** [comment]
Actually. I think that those logs are correct for s5 max. Is the vacuum entity back?

**Comment by q1t1** [comment]
With the main branch, I had all the tags (including last_clean_end, last_clean_duration, last_clean_area, clean_history_total_duration, clean_history_total_area, clean_history_count, clean_history_dust_collection_count) but the main entity is missing.

With the 0.1.2 branch, the main entity is back but I don't have the tags previously mentionned.

I tried to use the 2 branches several times, deleting completly the integrations in HACS before installing the other one.

**Comment by q1t1** [comment]
Reinstalled main today, I have all the entities, including vacuum one !

Thanks guys !

**Comment by Lash-L** [comment]
Believe this is fixed, feel free to reopen if not
