### ISSUE TITLE
Can't change map

### ISSUE THREAD

**Issue by Dis90** [humbertogontijo/homeassistant-roborock#249]
## Version of the custom_component
main

## What vacuum are you using?

Roborock S6 Pure
## Describe the bug

It's no longer possible to change map.

## Debug log

`2023-04-20 22:23:34.725 DEBUG (MainThread) [roborock.cloud_api] id=21256 Response from get_multi_maps_list: {'max_multi_map': 4, 'max_bak_map': 0, 'multi_map_count': 2, 'map_info': [{'mapFlag': 0, 'add_time': 1681867754, 'length': 8, 'name': 'Alakerta', 'bak_maps': []}, {'mapFlag': 1, 'add_time': 1672848972, 'length': 9, 'name': 'Yläkerta', 'bak_maps': []}]}`

```text

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1820, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1857, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 809, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 977, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/config/custom_components/roborock/vacuum.py", line 566, in async_load_multi_map
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Map flag 1 is invalid. Available map flags for device are {'Alakerta': None, 'Yläkerta': None}

```

**Comment by humbertogontijo** [comment]
Should be fixed in main

**Comment by Dis90** [comment]
Integration doesn't work anymore

`Setup failed for custom integration roborock: Unable to import component: No module named 'custom_components.roborock.typing'`

**Comment by humbertogontijo** [comment]
My bad. It should work now

**Comment by Dis90** [comment]
Integration now works but still can't change map :(

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1820, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1857, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 809, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 977, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/config/custom_components/roborock/vacuum.py", line 558, in async_load_multi_map
    map_flags = {
  File "/config/custom_components/roborock/vacuum.py", line 559, in <dictcomp>
    map_info.name or str(map_info.mapflag): map_info.mapflag
AttributeError: 'MultiMapsListMapInfo' object has no attribute 'mapflag'
```
