### ISSUE TITLE
Dock type not supported

### ISSUE THREAD

**Issue by tomassj9** [humbertogontijo/homeassistant-roborock#253]
## Version of the custom_component
Latest main f64996b

## What vacuum are you using?
Roborock Q7 Max Plus

## Describe the bug
After updating to main branch, the device cannot be connected. It throws an error about dock type not supported. See attached logs. Please tell me anything you can need from my part! FYI: This dock only have waste bin, not water refilling or something else.

## Debug log

```text
2023-04-24 00:58:20.588 ERROR (MainThread) [custom_components.roborock.coordinator] Unexpected error fetching roborock data: 5 is not a valid RoborockDockTypeCode
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/roborock/coordinator.py", line 77, in _async_update_data
    await self.fill_device_prop(device_info)
  File "/config/custom_components/roborock/coordinator.py", line 60, in fill_device_prop
    device_prop = await self.api.get_prop(device_info.device.duid)
  File "/usr/local/lib/python3.10/site-packages/roborock/api.py", line 278, in get_prop
    [status, dnd_timer, clean_summary, consumable] = await asyncio.gather(
  File "/usr/local/lib/python3.10/site-packages/roborock/api.py", line 177, in get_status
    return Status.from_dict(status)
  File "/usr/local/lib/python3.10/site-packages/roborock/containers.py", line 57, in from_dict
    return from_dict(cls, decamelize_obj(data, ignore_keys), config=Config(cast=[Enum]))
  File "/usr/local/lib/python3.10/site-packages/dacite/core.py", line 64, in from_dict
    value = _build_value(type_=field_type, data=field_data, config=config)
  File "/usr/local/lib/python3.10/site-packages/dacite/core.py", line 95, in _build_value
    data = _build_value_for_union(union=type_, data=data, config=config)
  File "/usr/local/lib/python3.10/site-packages/dacite/core.py", line 113, in _build_value_for_union
    return _build_value(type_=types[0], data=data, config=config)
  File "/usr/local/lib/python3.10/site-packages/dacite/core.py", line 105, in _build_value
    data = type_(data)
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 5 is not a valid RoborockDockTypeCode
2023-04-24 00:58:20.590 WARNING (MainThread) [homeassistant.config_entries] Config entry '' for roborock integration not ready yet: 5 is not a valid RoborockDockTypeCode; Retrying in background

2023-04-24 01:05:03.929 ERROR (MainThread) [roborock.api] Timeout after 4 seconds waiting for response

```

**Comment by Lash-L** [comment]
Good to know - this should be an easy fix, we don't have data for all of the docks - in reality, when we don't have the data it should still work and just assume it is the basic dock.

I will fix that + add support for your dock

https://us.roborock.com/pages/roborock-q7-max#autoEmptyDockPure

This is the one you have, correct?

**Comment by tomassj9** [comment]
Yes, that's correct. Thanks! If you need any testing, here I am!

**Comment by Lash-L** [comment]
It should work on the newest main

**Comment by Lash-L** [comment]
I'm not sure why the extra sensors would be showing up for you, as you have dock code 5. Looking at the code I can't figure out a reason why. @humbertogontijo any ideas?


As far as the prefix goes - both humbertogontijo and I don't have a dock with extra functionality. So we are unable to test these calls ourselves and as such, we are not able to reverse engineer the prefix we need for offline mode.

If you have a mac and an iphone, I could walk you through the process to get us the data, it is very easy and would take 5-10 minutes.

Otherwise,

@TobyStoe are you still willing to let me VPN into an isolated network to connect to your device?

**Comment by tomassj9** [comment]
Okay, tell me how I can extract the data and I will provide it for you. Also, I can manage to create a VPN and set up an isolated net for you without a problem.

**Comment by Lash-L** [comment]
@tomassj9 Awesome - if you have a mac and you have an iPhone - you can get this done pretty easily and I could add in the functionality( and potentially more) as early as today.


The easiest way to do it is to Download Wireshark and download Airtools 2(it has a 3 day free trial (no cc required)). If you want to avoid using airtools you can do this: https://medium.com/geekculture/capture-iphone-ios-http-traffic-using-wireshark-4af01a4313e6 But airtools is a lot simpler.


Airtools 2 will have an icon in the top right corner, click it and then select "Capture iPhone Packet Trace". Once wireshark gets launched by airtools, in the filter bar enter the following: ip.addr == (Your robots ip here (no parenthesis)) and data.data and tcp

 hit enter.

Make sure your phone is on the same network as your vacuum, then open the roborock app. Make sure items are appearing in wireshark. If they are, do all of the dock specific tasks. i.e. open maintenance for dock run dust cleaning, etc. Anything that is dock specific do it.

Then, hit stop button on the top of wireshark, then File-> save as -> pcapng. 

If you send me that file, I will be able to decode it and get the prefixes and any other functionality we don't currently have.

**Comment by TobyStoe** [comment]
> @TobyStoe are you still willing to let me VPN into an isolated network to connect to your device? It will probably be a few days before I have a chance to do it though - as I don't have my mac with me and I have a few other task I am trying to complete

Sure thing! I already set up the network and its ready to go. Just text me, whenever you would like to start

**Comment by Lash-L** [comment]
> > @TobyStoe are you still willing to let me VPN into an isolated network to connect to your device? It will probably be a few days before I have a chance to do it though - as I don't have my mac with me and I have a few other task I am trying to complete
> 
> 
> 
> Sure thing! I already set up the network and its ready to go. Just text me, whenever you would like to start

Okay if @tomassj9 isn't able to get it to work with the instructions I gave him, I'll let you know and I'll vpn there

**Comment by tomassj9** [comment]
Give me 1h or so.

**Comment by humbertogontijo** [comment]
The commands work even without the dock. I've updated the api and will soon update the HA integration

**Comment by humbertogontijo** [comment]
This is another issue I'm trying to solve. Just reload the integraiton

**Comment by tomassj9** [comment]
'''

Logger: roborock.api
Source: runner.py:179 
First occurred: 20:05:15 (230 occurrences) 
Last logged: 20:48:05

Timeout after 4 seconds waiting for response

'''

**Comment by tomassj9** [comment]
See attached logs from Local mode vs Cloud mode

**Local**
```
2023-04-26 08:35:07.974 DEBUG (MainThread) [custom_components.roborock]
*******  --- Personal data (if needed anything else than this I can send it via mail --- *******
received_devices=[], rooms=[HomeDataRoom(id=10991119, name='Sunroom'), HomeDataRoom(id=10943514, name='Default'), HomeDataRoom(id=10942146, name='Corridor1'), HomeDataRoom(id=10942145, name='Bathroom1'), HomeDataRoom(id=10942144, name='Master bedroom'), HomeDataRoom(id=10942104, name='Study'), HomeDataRoom(id=10942098, name='Bedroom1'), HomeDataRoom(id=10942094, name='Bedroom'), HomeDataRoom(id=10942093, name='Bathroom'), HomeDataRoom(id=10942092, name='Corridor'), HomeDataRoom(id=10942089, name='Kitchen'), HomeDataRoom(id=10942088, name='Living room')])
The server closed the connection
The server closed the connection
The server closed the connection
The server closed the connection
The server closed the connection
The server closed the connection
2023-04-26 08:35:12.365 ERROR (MainThread) [roborock.api] Timeout after 4 seconds waiting for response
2023-04-26 08:35:12.370 ERROR (MainThread) [roborock.api] Timeout after 4 seconds waiting for response
2023-04-26 08:35:12.372 ERROR (MainThread) [roborock.api] Timeout after 4 seconds waiting for response
2023-04-26 08:35:12.374 ERROR (MainThread) [roborock.api] Timeout after 4 seconds waiting for response
2023-04-26 08:35:12.376 DEBUG (MainThread) [custom_components.roborock.coordinator] Finished fetching roborock data in 4.380 seconds (success: False)
2023-04-26 08:35:12.377 WARNING (MainThread) [homeassistant.config_entries] Config entry '' for roborock integration not ready yet: Timeout after 4 seconds waiting for response; Retrying in background
```

**Cloud**
```
2023-04-26 08:35:07.974 DEBUG (MainThread) [custom_components.roborock]
*******  --- Personal data --- *******
received_devices=[], rooms=[HomeDataRoom(id=10991119, name='Sunroom'), HomeDataRoom(id=10943514, name='Default'), HomeDataRoom(id=10942146, name='Corridor1'), HomeDataRoom(id=10942145, name='Bathroom1'), HomeDataRoom(id=10942144, name='Master bedroom'), HomeDataRoom(id=10942104, name='Study'), HomeDataRoom(id=10942098, name='Bedroom1'), HomeDataRoom(id=10942094, name='Bedroom'), HomeDataRoom(id=10942093, name='Bathroom'), HomeDataRoom(id=10942092, name='Corridor'), HomeDataRoom(id=10942089, name='Kitchen'), HomeDataRoom(id=10942088, name='Living room')])
2023-04-26 08:35:32.581 DEBUG (MainThread) [custom_components.roborock.coordinator] Finished fetching roborock data in 1.883 seconds (success: True)
2023-04-26 08:35:41.670 DEBUG (MainThread) [custom_components.roborock.camera] Retrieving map from Roborock MQTT
2023-04-26 08:35:42.527 DEBUG (MainThread) [custom_components.roborock.common.map_data_parser] UNKNOWN BLOCK TYPE: 21, header length 12, data length 0
2023-04-26 08:35:42.536 DEBUG (MainThread) [custom_components.roborock.common.map_data_parser] UNKNOWN BLOCK TYPE: 22, header length 12, data length 0
2023-04-26 08:35:42.536 DEBUG (MainThread) [custom_components.roborock.common.map_data_parser] UNKNOWN BLOCK TYPE: 24, header length 8, data length 32
2023-04-26 08:35:42.536 DEBUG (MainThread) [custom_components.roborock.common.map_data_parser] UNKNOWN BLOCK TYPE: 25, header length 12, data length 0
2023-04-26 08:35:42.536 DEBUG (MainThread) [custom_components.roborock.common.map_data_parser] UNKNOWN BLOCK TYPE: 26, header length 8, data length 4
2023-04-26 08:35:42.659 DEBUG (MainThread) [custom_components.roborock.camera] Map data retrieved
2023-04-26 08:35:42.659 DEBUG (MainThread) [custom_components.roborock.camera] Map is ok
2023-04-26 08:35:44.210 DEBUG (MainThread) [custom_components.roborock.coordinator] Finished fetching roborock data in 0.537 seconds (success: True)
2023-04-26 08:36:14.778 DEBUG (MainThread) [custom_components.roborock.coordinator] Finished fetching roborock data in 0.372 seconds (success: True)
2023-04-26 08:36:44.875 DEBUG (MainThread) [custom_components.roborock.coordinator] Finished fetching roborock data in 0.470 seconds (success: True)
```

**Comment by tomassj9** [comment]
Seems that for the latest main, local connection is working with the new dock type. For now, only remains the entities that in my dock aren't available. I think it's a minor issue and that now there are more important things. For me, you can close the issue if you think it's okay. Keep going on this, it's awesome the progress it's making in this short time!

**Comment by Lash-L** [comment]
I'm not really sure why you have extra attributes - they should be ignored on sensor setup as they should be returning None.
