### ISSUE TITLE
Changing map fails with latest main

### ISSUE THREAD

**Issue by Dis90** [humbertogontijo/homeassistant-roborock#275]
## Version of the custom_component

Main

## What vacuum are you using?

S6 Pure

## Describe the bug

Command roborock.camera_load_multi_map fails

## Debug log

```text

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/roborock/device.py:102
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 22.15.02 (1 occurrences)
Last logged: 22.15.02

[139753642704752] Timeout after 4 seconds waiting for response
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1820, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1857, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 809, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 977, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/config/custom_components/roborock/vacuum.py", line 554, in async_load_multi_map
    await self.send(RoborockCommand.LOAD_MULTI_MAP, [map_flag])
  File "/config/custom_components/roborock/device.py", line 102, in send
    response = await self.coordinator.api.send_command(command, params)
  File "/usr/local/lib/python3.10/site-packages/roborock/local_api.py", line 92, in send_command
    return (await self.send_message(roborock_message))[0]
  File "/usr/local/lib/python3.10/site-packages/roborock/local_api.py", line 131, in send_message
    raise exception
  File "/usr/local/lib/python3.10/site-packages/roborock/local_api.py", line 100, in async_local_response
    (response, err) = await self._async_response(request_id, response_protocol)
  File "/usr/local/lib/python3.10/site-packages/roborock/api.py", line 192, in _async_response
    raise RoborockTimeout(f"Timeout after {QUEUE_TIMEOUT} seconds waiting for response") from None
roborock.exceptions.RoborockTimeout: Timeout after 4 seconds waiting for response

```

**Comment by Dis90** [comment]
It seems like map does change in app after command but doesn't change in HA.

**Comment by Dis90** [comment]
Starting vacuum gives same result

**Comment by Dis90** [comment]
Seems to work now with latest main.
