### ISSUE TITLE
Error setting up entry

### ISSUE THREAD

**Issue by dukennl** [humbertogontijo/homeassistant-roborock#276]
## Version of the custom_component
Im using Home Assistant 2023.4.6. and added the latest version of the [homeassistant-roborock](https://github.com/humbertogontijo/homeassistant-roborock) integration.

## What vacuum are you using?

S5 Max

## Describe the bug

I can't add my Roborock account. Not with email password or email and auth code. Error setting up entry

## Debug log

```text

Logger: homeassistant.config_entries
Source: custom_components/roborock/__init__.py:155
Integration: Roborock ([documentation](https://github.com/humbertogontijo/homeassistant-roborock), [issues](https://github.com/humbertogontijo/homeassistant-roborock/issues))
First occurred: 10:34:00 (1 occurrences)
Last logged: 10:34:00

Error setting up entry MYEMAIL@gmail.com for roborock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/roborock/__init__.py", line 112, in async_setup_entry
    local_device_info = await get_local_devices_info(device_info)
  File "/config/custom_components/roborock/__init__.py", line 155, in get_local_devices_info
    discovered = await RoborockProtocol(timeout=10).discover()
  File "/usr/local/lib/python3.10/site-packages/roborock/protocol.py", line 33, in discover
    self.transport, _ = await loop.create_datagram_endpoint(lambda: self, local_addr=("0.0.0.0", 58866))
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1385, in create_datagram_endpoint
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1369, in create_datagram_endpoint
    sock.bind(local_address)
OSError: [Errno 98] Address in use

Debug:

2023-05-03 08:30:40.736 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration roborock which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-05-03 08:31:33.442 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry MYEMAIL@gmail.com for roborock
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/roborock/roborock_future.py", line 23, in async_get
    return await self.fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/roborock/__init__.py", line 112, in async_setup_entry
    local_device_info = await get_local_devices_info(device_info)
  File "/config/custom_components/roborock/__init__.py", line 155, in get_local_devices_info
    discovered = await RoborockProtocol(timeout=10).discover()
  File "/usr/local/lib/python3.10/site-packages/roborock/protocol.py", line 34, in discover
    (response, exception) = await self.queue.async_get(self.timeout)
  File "/usr/local/lib/python3.10/site-packages/roborock/roborock_future.py", line 22, in async_get
    async with async_timeout.timeout(timeout):
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError



```

**Comment by dukennl** [comment]
I installed 0.1.1 and the problem is solved.

**Comment by Lash-L** [comment]
Can you try main @dukennl

**Comment by the-ress** [comment]
I’m getting the same error on 1.0.0

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/roborock/__init__.py", line 92, in async_setup_entry
    devices_network = await get_local_devices_info(_device)
  File "/config/custom_components/roborock/__init__.py", line 131, in get_local_devices_info
    discovered_devices = await RoborockProtocol(timeout=10).discover()
  File "/usr/local/lib/python3.10/site-packages/roborock/protocol.py", line 64, in discover
    self.transport, _ = await loop.create_datagram_endpoint(lambda: self, local_addr=("0.0.0.0", 58866))
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1385, in create_datagram_endpoint
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1369, in create_datagram_endpoint
    sock.bind(local_address)
OSError: [Errno 98] Address in use
```

**Comment by the-ress** [comment]
From the code it looks like this is being run for each device instead just once. (I have 2 devices.)

**Comment by humbertogontijo** [comment]
@the-ress Thank you for the info. I'll fix it soon

**Comment by Lash-L** [comment]
I believe this is resolved, but if it is not - please feel free to reopen/ping me
