### ISSUE TITLE
Q7 Max error on Set-up

### ISSUE THREAD

**Issue by tomassj9** [humbertogontijo/homeassistant-roborock#287]
## Version of the custom_component

Main cf7c3ec

## What vacuum are you using?
Roborock Q7 Max

## Describe the bug
Vacuum entities and mop selects not showing up. Only sensors showing up.

<img src=https://user-images.githubusercontent.com/39006479/236576811-95403e0f-2694-4ae9-9a37-49f412cb7fb8.png height=500>

## Debug log

```
05/05/2023 22:56:27
2023-05-05 22:56:27.765 ERROR (MainThread) [homeassistant.components.vacuum] Error adding entities for domain vacuum with platform roborock
05/05/2023 22:56:27
Traceback (most recent call last):
05/05/2023 22:56:27
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
05/05/2023 22:56:27
    await asyncio.gather(*tasks)
05/05/2023 22:56:27
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 643, in _async_add_entity
05/05/2023 22:56:27
    capabilities=entity.capability_attributes,
05/05/2023 22:56:27
  File "/config/custom_components/roborock/vacuum.py", line 358, in capability_attributes
05/05/2023 22:56:27
    capability_attributes[ATTR_MOP_MODE_LIST] = self.mop_mode_list
05/05/2023 22:56:27
  File "/config/custom_components/roborock/vacuum.py", line 331, in mop_mode_list
05/05/2023 22:56:27
    return self._device_status.mop_mode.keys()
05/05/2023 22:56:27
AttributeError: 'NoneType' object has no attribute 'keys'
05/05/2023 22:56:27
2023-05-05 22:56:27.767 ERROR (MainThread) [homeassistant.components.vacuum] Error while setting up roborock platform for vacuum
05/05/2023 22:56:27
Traceback (most recent call last):
05/05/2023 22:56:27
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 312, in _async_setup_platform
05/05/2023 22:56:27
    await asyncio.gather(*pending)
05/05/2023 22:56:27
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
05/05/2023 22:56:27
    await asyncio.gather(*tasks)
05/05/2023 22:56:27
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 643, in _async_add_entity
05/05/2023 22:56:27
    capabilities=entity.capability_attributes,
05/05/2023 22:56:27
  File "/config/custom_components/roborock/vacuum.py", line 358, in capability_attributes
05/05/2023 22:56:27
    capability_attributes[ATTR_MOP_MODE_LIST] = self.mop_mode_list
05/05/2023 22:56:27
  File "/config/custom_components/roborock/vacuum.py", line 331, in mop_mode_list
05/05/2023 22:56:27
    return self._device_status.mop_mode.keys()
05/05/2023 22:56:27
AttributeError: 'NoneType' object has no attribute 'keys'
```

**Comment by Lash-L** [comment]
This is a known issue for vacuums we don't have node information for - we already a fox in progress for it,

But you can help us and help yourself as well by answering on this issue with your mode info

https://github.com/humbertogontijo/homeassistant-roborock/issues/261

**Comment by tomassj9** [comment]
Latest main, solves this issue! Thanks devs!
