### ISSUE TITLE
Roborock S8 - Main branch - Setup error

### ISSUE THREAD

**Issue by stickpin** [humbertogontijo/homeassistant-roborock#297]
## Version of the custom_component

Main Branch

## What vacuum are you using?

Roborock S8

## Describe the bug

Not able to setup the using the main branch, where v0.1.2 is working fine.
Any suggestion?

## Debug log

```text

2023-05-09 10:53:38.392 ERROR (MainThread) [custom_components.roborock.coordinator] Unexpected error fetching roborock data: 'roborock.vacuum.a51'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/roborock/coordinator.py", line 98, in _async_update_data
    await self.fill_device_info(self.device_info)
  File "/config/custom_components/roborock/coordinator.py", line 87, in fill_device_info
    await asyncio.gather(
  File "/config/custom_components/roborock/coordinator.py", line 78, in fill_device_prop
    device_prop = await self.api.get_prop()
  File "/usr/local/lib/python3.10/site-packages/roborock/api.py", line 333, in get_prop
    [status, dnd_timer, clean_summary, consumable] = await asyncio.gather(
  File "/usr/local/lib/python3.10/site-packages/roborock/api.py", line 230, in get_status
    _cls: Type[Status] = ModelStatus[self.device_info.model]
KeyError: 'roborock.vacuum.a51'
2023-05-09 10:53:48.994 INFO (MainThread) [roborock.local_api] Connecting to 10.10.10.122
2023-05-09 10:53:49.002 INFO (MainThread) [roborock.local_api] Connected to 10.10.10.122
2023-05-09 10:53:49.018 ERROR (MainThread) [custom_components.roborock.coordinator] Unexpected error fetching roborock data: 'roborock.vacuum.a51'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/roborock/coordinator.py", line 98, in _async_update_data
    await self.fill_device_info(self.device_info)
  File "/config/custom_components/roborock/coordinator.py", line 87, in fill_device_info
    await asyncio.gather(
  File "/config/custom_components/roborock/coordinator.py", line 78, in fill_device_prop
    device_prop = await self.api.get_prop()
  File "/usr/local/lib/python3.10/site-packages/roborock/api.py", line 333, in get_prop
    [status, dnd_timer, clean_summary, consumable] = await asyncio.gather(
  File "/usr/local/lib/python3.10/site-packages/roborock/api.py", line 230, in get_status
    _cls: Type[Status] = ModelStatus[self.device_info.model]
KeyError: 'roborock.vacuum.a51'

```

**Comment by Lash-L** [comment]
Fill this out

https://github.com/humbertogontijo/homeassistant-roborock/issues/261

**Comment by stickpin** [comment]
@Lash-L done. :) 
Please, let me know if you need more info.
