### ISSUE TITLE
More services: Why are services removed in newer versions?

### ISSUE THREAD

**Issue by Badbandit69** [humbertogontijo/homeassistant-roborock#307]
Why do you remove services like the "_mop" services? They were already there.

It is easier to write automations or make buttons with the UI, when one can select a service and then the value in a drop-down. Now one has to fiddle with selects where one has to know the available values/options.

**Comment by PyRowMan** [comment]
Because you can change the values by updating the select like this : 

```yaml 
- icon: mdi:water-off-outline
  conditions:
    - entity: vacuum.robocorne
      attribute: mop_intensity
      value: 'off'
  tooltip: Change mop intensity
  tap_action:
    action: call-service
    service: select.select_next
    service_data:
      cycle: true
    target:
      entity_id: select.robocorne_intensite_de_frottement
```

**Comment by poudenes** [comment]
Would be great to have this working: (S8 user here)
Want create a schedule in Home Assistant to run the S8 when everyone is out of the house.
Based on days what to do... 

```
service: select.select_option
data:  
  option: Deep
target:
  entity_id: select.roborock_s8_mop_mode
```
option of select.roborock_s8_mop_mode = Standard, Deep, Deep+, Custom

```
Logger: homeassistant.helpers.script.websocket_api_script
Source: components/select/__init__.py:105 
First occurred: 10:24:37 (3 occurrences) 
Last logged: 10:24:58

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Option Deep not valid for select.roborock_s8_mop_mode
websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Option Standard not valid for select.roborock_s8_mop_mode
websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Option Intense not valid for select.roborock_s8_mop_intensity
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 452, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 685, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1849, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1889, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 980, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 105, in async_select_option
    raise ValueError(f"Option {option} not valid for {entity.entity_id}")
ValueError: Option Deep not valid for select.roborock_s8_mop_mode
```

**Comment by JurajNyiri** [comment]
It works as expected, you need to provide a correct value.

fan_speed_list: off, quiet, balanced, turbo, max, custom, max_plus
mop_mode_list: standard, deep, custom, deep_plus
mop_intensity_list: off, mild, moderate, intense, custom
