### ISSUE TITLE
unsupported operand type(s) for +: 'int' and 'list'

### ISSUE THREAD

**Issue by 108085** [humbertogontijo/homeassistant-roborock#318]
## Version of the custom_component

1.0.1

## What vacuum are you using?

Roborock S6 MaxV
## Describe the bug

Since the 1.0.0 update, the integration is not working anymore. Always getting unsupported operand type(s) for +: 'int' and 'list' error

## Debug log

```text

2023-05-13 11:55:30.721 ERROR (MainThread) [custom_components.roborock.coordinator] Unexpected error fetching roborock data: unsupported operand type(s) for +: 'int' and 'list'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/roborock/coordinator.py", line 98, in _async_update_data
    await self.fill_device_info(self.device_info)
  File "/config/custom_components/roborock/coordinator.py", line 87, in fill_device_info
    await asyncio.gather(
  File "/config/custom_components/roborock/coordinator.py", line 63, in fill_room_mapping
    room_mapping = await self.api.get_room_mapping()
  File "/usr/local/lib/python3.10/site-packages/roborock/util.py", line 53, in wrapped
    raise e
  File "/usr/local/lib/python3.10/site-packages/roborock/util.py", line 50, in wrapped
    cache.last_run_result = await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/roborock/api.py", line 368, in get_room_mapping
    for segment_id, iot_id in [unpack_list(room, 2) for room in mapping]
  File "/usr/local/lib/python3.10/site-packages/roborock/api.py", line 368, in <listcomp>
    for segment_id, iot_id in [unpack_list(room, 2) for room in mapping]
  File "/usr/local/lib/python3.10/site-packages/roborock/util.py", line 12, in unpack_list
    return (value + [None] * size)[:size]  # type: ignore
TypeError: unsupported operand type(s) for +: 'int' and 'list'
2023-05-13 11:55:30.724 WARNING (MainThread) [homeassistant.config_entries] Config entry '108085@gmail.com' for roborock integration not ready yet: unsupported operand type(s) for +: 'int' and 'list'; Retrying in background
2023-05-13 11:55:30.727 WARNING (MainThread) [roborock.code_mappings] Missing RoborockFanSpeedE2 code: 103 - defaulting to 41

```

**Comment by 108085** [comment]
Running HassOS (VM) on Proxmox

Home Assistant 2023.5.2
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.3 - latest

**Comment by mirkotr** [comment]
I have the same problem with the Roborock S7 MaxV. Going back to version 0.1.2

**Comment by ecoValentin** [comment]
Not sure if it helps, but I got the same error (S6 MaxV) with this line before the Error Stack Trace:
2023-05-14 18:42:02.342 WARNING (MainThread) [roborock.code_mappings] Missing RoborockDockTypeCode code: 1 - defaulting to 'missing'

**Comment by humbertogontijo** [comment]
Could anyone that had this error share the log for the return from command get_room_mapping?

**Comment by ecoValentin** [comment]
I can also not reproduce the problem with 1.0.2, but I suspect the no go zone, a friend has the same setup without no go zones and it worked.

**Comment by Utopia69** [comment]
> I can also not reproduce the problem with 1.0.2, but I suspect the no go zone, a friend has the same setup without no go zones and it worked.

I don't use no go zones but also have this problem

**Comment by Utopia69** [comment]
Upgrading to v1.0.2 solved the problem for me

**Comment by 108085** [comment]
1.0.2 fixed it for me too
