### ISSUE TITLE
Data mix between 2 roborock vacuums

### ISSUE THREAD

**Issue by BeFygo** [humbertogontijo/homeassistant-roborock#376]
**Roborock data mixups**
Ps: love your work!!

## Version of the custom_component

1.0.6
1.0.9

## What vacuum are you using?

Roborock S7 maxV plus
Roborock Q7 max+

## Describe the bug

I noticed that all the datapoints between the S7 and the Q7 gets mixed often.
A few datapoints as an example below.

![Q7 total clean count](https://github.com/humbertogontijo/homeassistant-roborock/assets/72655961/9959f6fc-1010-4bda-a61f-24caa124ddff)
![S7 total clean count](https://github.com/humbertogontijo/homeassistant-roborock/assets/72655961/dc6503f8-55a7-42ee-99b6-8745c863a5a1)

![Q7 main brush left](https://github.com/humbertogontijo/homeassistant-roborock/assets/72655961/25d69940-18cd-405c-aa8c-efe7e83efbe8)
![S7 main brush left](https://github.com/humbertogontijo/homeassistant-roborock/assets/72655961/2729b6e6-c7ee-468d-8a4b-b3833bdb2408)

## Debug log

Debug is enabled, is that data printed in the HA logs?
If so, some logs below.

Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:137
First occurred: June 11, 2023 at 20:01:53 (2 occurrences)
Last logged: 01:52:39

Error doing job: Exception in callback Future.set_result(({'clean_area': 2936585000, 'clean_count': 205, 'clean_time': 249151, 'dust_collection_count': 136, ...}, None))
Error doing job: Exception in callback Future.set_result(({'enabled': 1, 'end_hour': 7, 'end_minute': 0, 'start_hour': 20, ...}, None))
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
asyncio.exceptions.InvalidStateError: invalid state

This error originated from a custom integration.

Logger: roborock.cloud_api
Source: custom_components/roborock/camera.py:220
Integration: Roborock (documentation, issues)
First occurred: 06:47:29 (7 occurrences)
Last logged: 07:57:26

id=0 Timeout after 4 seconds
id=15589 Timeout after 4 seconds
id=31545 Timeout after 4 seconds
id=16242 Timeout after 4 seconds
id=31964 Timeout after 4 seconds

**Logs after Home assistant update (2023.6.1)**

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/roborock/device.py:110
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 13:04:52 (3 occurrences)
Last logged: 13:09:13

[281472552701584] Error while calling APP_GOTO_TARGET with [24212, 26864]
[281472552701584] Error while calling APP_START with None
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/roborock/local_api.py", line 64, in async_connect
    self.transport, _ = await self.loop.create_connection(  # type: ignore
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 674, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.0.134', 58867)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/roborock/device.py", line 108, in send
    response = await self.coordinator.api.send_command(command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/roborock/local_api.py", line 134, in send_command
    return (await self.send_message(roborock_message))[0]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/roborock/local_api.py", line 183, in send_message
    await self.validate_connection()
  File "/usr/local/lib/python3.11/site-packages/roborock/api.py", line 183, in validate_connection
    await self.async_connect()
  File "/usr/local/lib/python3.11/site-packages/roborock/local_api.py", line 70, in async_connect
    raise RoborockConnectionException(f"Failed connecting to {self.host}") from e
roborock.exceptions.RoborockConnectionException: Failed connecting to 192.168.0.134

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1910, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1950, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 827, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 811, in entity_service_call
    future.result()  # pop exception if have
    ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1034, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 851, in _handle_entity_call
    await result
  File "/config/custom_components/roborock/vacuum.py", line 483, in async_goto
    await self.send(RoborockCommand.APP_GOTO_TARGET, [x_coord, y_coord])
  File "/config/custom_components/roborock/device.py", line 110, in send
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Error while calling APP_GOTO_TARGET with [24212, 26864]

**## failed to connect to roborock Q7**

This error originated from a custom integration.

Logger: custom_components.roborock.coordinator
Source: helpers/update_coordinator.py:262
Integration: Roborock (documentation, issues)
First occurred: 13:02:09 (3 occurrences)
Last logged: 13:17:54

Error fetching roborock data: Failed connecting to 192.168.0.134

**Comment by Lash-L** [comment]
Try with 1.0.11

**Comment by BeFygo** [comment]
> Try with 1.0.11

I upgraded yesterday.
I'll wait a few days to verify is the issue is fixed.

**Comment by BeFygo** [comment]
Hi Guys,

This issue seems to be fixed.

Great work, infinite appreciation!!!
