### ISSUE TITLE
1.0.7: Integration not working

### ISSUE THREAD

**Issue by Boss-man** [humbertogontijo/homeassistant-roborock#379]
HA 2023.6.2

## Version of the custom_component
1.0.7

## What vacuum are you using?
Roborock S6 MaxV

## Describe the bug
Integration can not initialize. Fails repeatedly.
I can see in the log that it talks to the device and gets response, But some where it fails anyway.

## Debug log

```
2023-06-15 13:05:06.022 INFO (MainThread) [roborock.local_api] Connecting to 192.168.1.156
2023-06-15 13:05:06.023 DEBUG (MainThread) [roborock.local_api] id=24287 Requesting method RoborockCommand.GET_ROOM_MAPPING with None
2023-06-15 13:05:06.023 DEBUG (MainThread) [roborock.local_api] id=22881 Requesting method RoborockCommand.GET_SOUND_VOLUME with None
2023-06-15 13:05:06.023 DEBUG (MainThread) [roborock.local_api] id=25134 Requesting method RoborockCommand.GET_FLOW_LED_STATUS with None
2023-06-15 13:05:06.023 DEBUG (MainThread) [roborock.local_api] id=25373 Requesting method RoborockCommand.GET_CHILD_LOCK_STATUS with None
2023-06-15 13:05:06.024 DEBUG (MainThread) [roborock.local_api] id=10536 Requesting method RoborockCommand.GET_STATUS with None
2023-06-15 13:05:06.024 DEBUG (MainThread) [roborock.local_api] id=28429 Requesting method RoborockCommand.GET_CLEAN_SUMMARY with None
2023-06-15 13:05:06.024 DEBUG (MainThread) [roborock.local_api] id=26690 Requesting method RoborockCommand.GET_CONSUMABLE with None
2023-06-15 13:05:06.024 DEBUG (MainThread) [roborock.local_api] id=14578 Requesting method RoborockCommand.GET_DND_TIMER with None
2023-06-15 13:05:06.024 DEBUG (MainThread) [roborock.local_api] id=23692 Requesting method RoborockCommand.GET_VALLEY_ELECTRICITY_TIMER with None
2023-06-15 13:05:06.031 INFO (MainThread) [roborock.local_api] Connected to 192.168.1.156
2023-06-15 13:05:06.054 DEBUG (MainThread) [roborock.local_api] id=24287 Response from method get_room_mapping: [[17, '1933195'], [18, '1933200'], [19, '2568481'], [20, '1933228'], [21, '1933230'], [22, '3030414'], [23, '1933198']]
2023-06-15 13:05:06.054 DEBUG (MainThread) [roborock.local_api] id=22881 Response from method get_sound_volume: 79
2023-06-15 13:05:06.054 DEBUG (MainThread) [roborock.local_api] id=25373 Response from method get_child_lock_status: {'lock_status': 0}
2023-06-15 13:05:06.054 DEBUG (MainThread) [roborock.local_api] id=10536 Response from method get_status: {'msg_ver': 2, 'msg_seq': 2005, 'state': 8, 'battery': 100, 'clean_time': 295, 'clean_area': 5157500, 'error_code': 0, 'map_present': 1, 'in_cleaning': 0, 'in_returning': 0, 'in_fresh_state': 1, 'lab_status': 1, 'water_box_status': 0, 'fan_power': 103, 'dnd_enabled': 0, 'map_status': 3, 'is_locating': 0, 'lock_status': 0, 'water_box_mode': 202, 'distance_off': 0, 'water_box_carriage_status': 0, 'mop_forbidden_enable': 0, 'camera_status': 3493, 'is_exploring': 0, 'home_sec_status': 0, 'home_sec_enable_password': 1, 'adbumper_status': [0, 0, 0]}
2023-06-15 13:05:06.056 DEBUG (MainThread) [custom_components.roborock.coordinator] Finished fetching roborock data in 0.035 seconds (success: False)
2023-06-15 13:05:06.056 DEBUG (MainThread) [roborock.local_api] Disconnecting from 192.168.1.156
2023-06-15 13:05:06.057 DEBUG (MainThread) [roborock.local_api] Disconnecting from 192.168.1.156
2023-06-15 13:05:06.057 DEBUG (MainThread) [roborock.local_api] Disconnecting from 192.168.1.156
2023-06-15 13:05:06.057 DEBUG (MainThread) [roborock.local_api] Disconnecting from 192.168.1.156
2023-06-15 13:05:06.057 DEBUG (MainThread) [roborock.local_api] Disconnecting from 192.168.1.156
2023-06-15 13:05:06.057 DEBUG (MainThread) [roborock.local_api] Disconnecting from 192.168.1.156
2023-06-15 13:05:06.057 DEBUG (MainThread) [roborock.local_api] Disconnecting from 192.168.1.156
2023-06-15 13:05:06.057 DEBUG (MainThread) [roborock.local_api] Disconnecting from 192.168.1.156
2023-06-15 13:05:06.057 DEBUG (MainThread) [roborock.local_api] Disconnecting from 192.168.1.156
2023-06-15 13:05:06.058 WARNING (MainThread) [homeassistant.config_entries] Config entry me@email.com' for roborock integration not ready yet: There are no devices that can currently be reached.; Retrying in background
2023-06-15 13:05:06.068 DEBUG (MainThread) [roborock.local_api] Disconnecting from 192.168.1.156
2023-06-15 13:05:06.068 INFO (MainThread) [roborock.api] Roborock client disconnected
2023-06-15 13:05:06.068 DEBUG (MainThread) [roborock.local_api] Disconnecting from 192.168.1.156
2023-06-15 13:05:06.068 INFO (MainThread) [roborock.api] Roborock client disconnected
2023-06-15 13:05:06.068 DEBUG (MainThread) [roborock.local_api] Disconnecting from 192.168.1.156
2023-06-15 13:05:06.068 INFO (MainThread) [roborock.api] Roborock client disconnected
2023-06-15 13:05:06.069 DEBUG (MainThread) [roborock.local_api] Disconnecting from 192.168.1.156
2023-06-15 13:05:06.069 INFO (MainThread) [roborock.api] Roborock client disconnected
2023-06-15 13:05:06.069 DEBUG (MainThread) [roborock.local_api] Disconnecting from 192.168.1.156
2023-06-15 13:05:06.069 INFO (MainThread) [roborock.api] Roborock client disconnected
2023-06-15 13:05:06.069 DEBUG (MainThread) [roborock.local_api] Disconnecting from 192.168.1.156
2023-06-15 13:05:06.069 INFO (MainThread) [roborock.api] Roborock client disconnected
2023-06-15 13:05:06.069 DEBUG (MainThread) [roborock.local_api] Disconnecting from 192.168.1.156
2023-06-15 13:05:06.070 INFO (MainThread) [roborock.api] Roborock client disconnected
2023-06-15 13:05:07.321 DEBUG (MainThread) [roborock.local_api] Disconnecting from 192.168.1.156
2023-06-15 13:05:07.321 INFO (MainThread) [roborock.local_api] Connecting to 192.168.1.156
2023-06-15 13:05:07.406 INFO (MainThread) [roborock.local_api] Connected to 192.168.1.156
2023-06-15 13:05:07.891 DEBUG (MainThread) [roborock.local_api] Disconnecting from 192.168.1.156
2023-06-15 13:05:07.891 INFO (MainThread) [roborock.local_api] Connecting to 192.168.1.156
2023-06-15 13:05:08.065 INFO (MainThread) [roborock.local_api] Connected to 192.168.1.156
2023-06-15 13:05:09.837 DEBUG (MainThread) [roborock.local_api] Disconnecting from 192.168.1.156
2023-06-15 13:05:09.837 INFO (MainThread) [roborock.local_api] Connecting to 192.168.1.156
2023-06-15 13:05:09.839 DEBUG (MainThread) [roborock.local_api] Disconnecting from 192.168.1.156
2023-06-15 13:05:09.839 INFO (MainThread) [roborock.local_api] Connecting to 192.168.1.156
2023-06-15 13:05:09.840 DEBUG (MainThread) [roborock.local_api] Disconnecting from 192.168.1.156
2023-06-15 13:05:09.841 INFO (MainThread) [roborock.local_api] Connecting to 192.168.1.156
2023-06-15 13:05:09.842 DEBUG (MainThread) [roborock.local_api] Disconnecting from 192.168.1.156
2023-06-15 13:05:09.842 INFO (MainThread) [roborock.local_api] Connecting to 192.168.1.156
2023-06-15 13:05:09.965 INFO (MainThread) [roborock.local_api] Connected to 192.168.1.156
2023-06-15 13:05:09.967 INFO (MainThread) [roborock.local_api] Connected to 192.168.1.156
2023-06-15 13:05:09.968 INFO (MainThread) [roborock.local_api] Connected to 192.168.1.156
2023-06-15 13:05:09.969 INFO (MainThread) [roborock.local_api] Connected to 192.168.1.156
2023-06-15 13:05:10.053 ERROR (MainThread) [roborock.local_api] id=1 Timeout after 4 seconds
2023-06-15 13:05:10.054 DEBUG (MainThread) [roborock.local_api] Disconnecting from 192.168.1.156
2023-06-15 13:05:10.055 INFO (MainThread) [roborock.local_api] Connecting to 192.168.1.156
2023-06-15 13:05:10.063 INFO (MainThread) [roborock.local_api] Connected to 192.168.1.156
2023-06-15 13:05:10.140 DEBUG (MainThread) [roborock.local_api] id=13130 Response from method get_multi_maps_list: {'max_multi_map': 1, 'max_bak_map': 0, 'multi_map_count': 1, 'map_info': [{'mapFlag': 0, 'add_time': 1676538821, 'length': 4, 'name': 'Home', 'bak_maps': []}]}
2023-06-15 13:05:11.305 DEBUG (MainThread) [custom_components.roborock] Integration async setup entry: {'entry_id': '58d257eb29e867ce72096b4279d65eec', 'version': 1, 'domain': 'roborock', 'title': 'me@email.com', 'data': {'home_data': {'id': 1112019, 'name': 'My Home', 'products': [{'id': '7ggJhlYqQs58zKFAOgBPc1', 'name': 'Roborock S6 MaxV', 'model': 'roborock.vacuum.a10', 'capability': 2, 'category': 'robot.vacuum.cleaner', 'schema': [{'id': '101', 'name': 'rpc_request', 'code': 'rpc_request', 'mode': 'rw', 'type': 'RAW'}, {'id': '102', 'name': 'rpc_response', 'code': 'rpc_response', 'mode': 'rw', 'type': 'RAW'}, {'id': '120', 'name': 'é”™è¯¯ä»£ç ', 'code': 'error_code', 'mode': 'ro', 'type': 'ENUM'}, {'id': '121', 'name': 'è®¾å¤‡çŠ¶æ€', 'code': 'state', 'mode': 'ro', 'type': 'ENUM'}, {'id': '122', 'name': 'è®¾å¤‡ç”µé‡', 'code': 'battery', 'mode': 'ro', 'type': 'ENUM'}, {'id': '123', 'name': 'æ¸…æ‰«æ¨¡å¼', 'code': 'fan_power', 'mode': 'rw', 'type': 'ENUM'}, {'id': '124', 'name': 'æ‹–åœ°æ¨¡å¼', 'code': 'water_box_mode', 'mode': 'rw', 'type': 'ENUM'}, {'id': '125', 'name': 'ä¸»åˆ·å¯¿å‘½', 'code': 'main_brush_life', 'mode': 'rw', 'type': 'VALUE'}, {'id': '126', 'name': 'è¾¹åˆ·å¯¿å‘½', 'code': 'side_brush_life', 'mode': 'rw', 'type': 'VALUE'}, {'id': '127', 'name': 'æ»¤ç½‘å¯¿å‘½', 'code': 'filter_life', 'mode': 'rw', 'type': 'VALUE'}, {'id': '128', 'name': 'é¢å¤–çŠ¶æ€', 'code': 'additional_props', 'mode': 'ro', 'type': 'RAW'}, {'id': '130', 'name': 'å®Œæˆäº‹ä»¶', 'code': 'task_complete', 'mode': 'ro', 'type': 'RAW'}, {'id': '131', 'name': 'ç”µé‡ä¸è¶³ä»»åŠ¡å–æ¶ˆ', 'code': 'task_cancel_low_power', 'mode': 'ro', 'type': 'RAW'}, {'id': '132', 'name': 'è¿åŠ¨ä¸­ä»»åŠ¡å–æ¶ˆ', 'code': 'task_cancel_in_motion', 'mode': 'ro', 'type': 'RAW'}, {'id': '133', 'name': 'å……ç”µçŠ¶æ€', 'code': 'charge_status', 'mode': 'ro', 'type': 'RAW'}, {'id': '134', 'name': 'çƒ˜å¹²çŠ¶æ€', 'code': 'drying_status', 'mode': 'ro', 'type': 'RAW'}]}], 'devices': [{'duid': '3bC3wyIWOBhIBPaF3RHzuz', 'name': 'Roborock S6 MaxV', 'localKey': '4nAFdBVGBfTCqOvH', 'fv': '02.62.46', 'activeTime': 1614767168, 'timeZoneId': 'Europe/Copenhagen', 'iconUrl': '', 'productId': '7ggJhlYqQs58zKFAOgBPc1', 'share': False, 'online': True, 'pv': '1.0', 'tuyaMigrated': False, 'extra': '{"xxxx": "xxxx", "RRPhotoPrivacyVersion": "1", "RRMonitorPrivacyVersion": "1"}', 'sn': 'R0402S05007472', 'featureSet': '10738169343', 'deviceStatus': {'121': 8, '122': 100, '123': 103, '124': 202, '125': 18, '126': 0, '127': 0, '120': 0}, 'silentOtaSwitch': False}], 'receivedDevices': [], 'rooms': [{'id': 3030414, 'name': 'Bryggers'}, {'id': 2568481, 'name': 'BadevÃ¦relse'}, {'id': 1933230, 'name': 'Stue'}, {'id': 1933228, 'name': 'EntrÃ©'}, {'id': 1933200, 'name': 'SovevÃ¦relse'}, {'id': 1933198, 'name': 'KÃ¸kken'}, {'id': 1933195, 'name': 'Kontor'}, {'id': 1933191, 'name': 'GÃ¦stevÃ¦relse'}]}, 'username': 'me@email.com', 'user_data': {'uid': 1102769, 'tokentype': '', 'token': 'cc60f03beeec4c168114c4a388671685-dodB+gEcAYom2qN+Hgg6uw==', 'rruid': 'rr5dfde775991820', 'region': 'eu', 'countrycode': '45', 'country': 'DK', 'nickname': 'Me', 'rriot': {'u': '6CNiRqguPklJkNw6GxT2DY', 's': 'JxuGwj', 'h': 'e3bankdUpr', 'k': 'yTbNZ32T', 'r': {'r': 'EU', 'a': 'https://api-eu.roborock.com', 'm': 'ssl://mqtt-eu.roborock.com:8883', 'l': 'https://wood-eu.roborock.com'}}, 'tuyaDeviceState': 2, 'avatarurl': 'https://files.roborock.com/iottest/default_avatar.png'}, 'base_url': 'https://euiot.roborock.com'}, 'options': {}, 'pref_disable_new_entities': False, 'pref_disable_polling': False, 'source': 'user', 'unique_id': 'Me@email.com', 'disabled_by': None}
2023-06-15 13:05:11.307 DEBUG (MainThread) [custom_components.roborock] Requesting home data
2023-06-15 13:05:11.471 DEBUG (MainThread) [custom_components.roborock] Got home data HomeData(id=1112019, name='My Home', lon=None, lat=None, geo_name=None, products=[HomeDataProduct(id='7ggJhlYqQs58zKFAOgBPc1', name='Roborock S6 MaxV', code=None, model='roborock.vacuum.a10', iconurl=None, attribute=None, capability=2, category='robot.vacuum.cleaner', schema=[HomeDataProductSchema(id='101', name='rpc_request', code='rpc_request', mode='rw', type='RAW', product_property=None, desc=None), HomeDataProductSchema(id='102', name='rpc_response', code='rpc_response', mode='rw', type='RAW', product_property=None, desc=None), HomeDataProductSchema(id='120', name='é”™è¯¯ä»£ç ', code='error_code', mode='ro', type='ENUM', product_property=None, desc=None), HomeDataProductSchema(id='121', name='è®¾å¤‡çŠ¶æ€', code='state', mode='ro', type='ENUM', product_property=None, desc=None), HomeDataProductSchema(id='122', name='è®¾å¤‡ç”µé‡', code='battery', mode='ro', type='ENUM', product_property=None, desc=None), HomeDataProductSchema(id='123', name='æ¸…æ‰«æ¨¡å¼', code='fan_power', mode='rw', type='ENUM', product_property=None, desc=None), HomeDataProductSchema(id='124', name='æ‹–åœ°æ¨¡å¼', code='water_box_mode', mode='rw', type='ENUM', product_property=None, desc=None), HomeDataProductSchema(id='125', name='ä¸»åˆ·å¯¿å‘½', code='main_brush_life', mode='rw', type='VALUE', product_property=None, desc=None), HomeDataProductSchema(id='126', name='è¾¹åˆ·å¯¿å‘½', code='side_brush_life', mode='rw', type='VALUE', product_property=None, desc=None), HomeDataProductSchema(id='127', name='æ»¤ç½‘å¯¿å‘½', code='filter_life', mode='rw', type='VALUE', product_property=None, desc=None), HomeDataProductSchema(id='128', name='é¢å¤–çŠ¶æ€', code='additional_props', mode='ro', type='RAW', product_property=None, desc=None), HomeDataProductSchema(id='130', name='å®Œæˆäº‹ä»¶', code='task_complete', mode='ro', type='RAW', product_property=None, desc=None), HomeDataProductSchema(id='131', name='ç”µé‡ä¸è¶³ä»»åŠ¡å–æ¶ˆ', code='task_cancel_low_power', mode='ro', type='RAW', product_property=None, desc=None), HomeDataProductSchema(id='132', name='è¿åŠ¨ä¸­ä»»åŠ¡å–æ¶ˆ', code='task_cancel_in_motion', mode='ro', type='RAW', product_property=None, desc=None), HomeDataProductSchema(id='133', name='å……ç”µçŠ¶æ€', code='charge_status', mode='ro', type='RAW', product_property=None, desc=None), HomeDataProductSchema(id='134', name='çƒ˜å¹²çŠ¶æ€', code='drying_status', mode='ro', type='RAW', product_property=None, desc=None)])], devices=[HomeDataDevice(duid='3bC3wyIWOBhIBPaF3RHzuz', name='Roborock S6 MaxV', local_key='4nAFdBVGBfTCqOvH', fv='02.62.46', attribute=None, active_time=1614767168, runtime_env=None, time_zone_id='Europe/Copenhagen', icon_url='', product_id='7ggJhlYqQs58zKFAOgBPc1', lon=None, lat=None, share=False, share_time=None, online=True, pv='1.0', room_id=None, tuya_uuid=None, tuya_migrated=False, extra='{"xxxx": "xxxx", "RRPhotoPrivacyVersion": "1", "RRMonitorPrivacyVersion": "1"}', sn='R0402S05007472', feature_set='10738169343', new_feature_set=None, device_status={'121': 8, '122': 100, '123': 103, '124': 202, '125': 18, '126': 0, '127': 0, '120': 0}, silent_ota_switch=False)], received_devices=[], rooms=[HomeDataRoom(id=3030414, name='Bryggers'), HomeDataRoom(id=2568481, name='BadevÃ¦relse'), HomeDataRoom(id=1933230, name='Stue'), HomeDataRoom(id=1933228, name='EntrÃ©'), HomeDataRoom(id=1933200, name='SovevÃ¦relse'), HomeDataRoom(id=1933198, name='KÃ¸kken'), HomeDataRoom(id=1933195, name='Kontor'), HomeDataRoom(id=1933191, name='GÃ¦stevÃ¦relse')])
2023-06-15 13:05:15.181 DEBUG (MainThread) [roborock.protocol] Received broadcast: BroadcastMessage(duid='3bC3wyIWOBhIBPaF3RHzuz', ip='192.168.1.156')
2023-06-15 13:05:20.098 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Future.set_result((None, None))
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
asyncio.exceptions.InvalidStateError: invalid state
2023-06-15 13:05:20.101 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Future.set_result((None, None))
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
asyncio.exceptions.InvalidStateError: invalid state
2023-06-15 13:05:20.105 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Future.set_result((None, None))
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
asyncio.exceptions.InvalidStateError: invalid state
2023-06-15 13:05:20.107 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Future.set_result((None, None))
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
asyncio.exceptions.InvalidStateError: invalid state
2023-06-15 13:05:20.167 DEBUG (MainThread) [roborock.protocol] Received broadcast: BroadcastMessage(duid='3bC3wyIWOBhIBPaF3RHzuz', ip='192.168.1.156')
2023-06-15 13:05:21.513 DEBUG (MainThread) [roborock.local_api] id=26121 Requesting method RoborockCommand.GET_MULTI_MAPS_LIST with None

```

**Comment by FuL75** [comment]
same here
Roborock S5 Max

**Comment by slofii** [comment]
same here
Roborock S8

**Comment by AseKarlsson** [comment]
Same here, Roborock S7

**Comment by vadimnazaroff** [comment]
Same here, Roborock S6 Max. 
Integration produce lots of issues and slowing down HAAS system. Critical issue

**Comment by liamlain** [comment]
same,rollback to 1.06 all good

**Comment by poudenes** [comment]
Same Roborock S8. Even i cant downgrade back to 1.0.6

**Comment by Electronlibre2012** [comment]
Better way than add more "same here" that isnt usefull for the DEV, POST some logs and wait for a fix .....LOOOOOOOL

**Comment by AseKarlsson** [comment]
> Not working at all, repeadly failed to connect. Had to rollback to 1.0.6

How did you do the rollback? 
Tried Re-download and select version 1.0.6 but with no succeess.

**Comment by poudenes** [comment]
> > Not working at all, repeadly failed to connect. Had to rollback to 1.0.6
> 
> How did you do the rollback? Tried Re-download and select version 1.0.6 but with no succeess.

I did it couple of times to let the downgrade work

**Comment by AseKarlsson** [comment]
> > > Not working at all, repeadly failed to connect. Had to rollback to 1.0.6
> > 
> > 
> > How did you do the rollback? Tried Re-download and select version 1.0.6 but with no succeess.
> 
> I did it couple of times to let the downgrade work

Thanks, will test!

**Comment by MiguelCosta** [comment]
Same with S7

```
...
2023-06-15 15:51:56.482 INFO (MainThread) [roborock.local_api] Connecting to 192.168.31.232
2023-06-15 15:51:56.485 DEBUG (MainThread) [roborock.local_api] Disconnecting from 192.168.31.232
2023-06-15 15:51:56.485 INFO (MainThread) [roborock.local_api] Connecting to 192.168.31.232
2023-06-15 15:51:56.488 DEBUG (MainThread) [roborock.local_api] Disconnecting from 192.168.31.232
2023-06-15 15:51:56.488 INFO (MainThread) [roborock.local_api] Connecting to 192.168.31.232
2023-06-15 15:51:56.490 DEBUG (MainThread) [roborock.local_api] Disconnecting from 192.168.31.232
2023-06-15 15:51:56.490 INFO (MainThread) [roborock.api] Roborock client disconnected
2023-06-15 15:51:56.491 DEBUG (MainThread) [roborock.local_api] Disconnecting from 192.168.31.232
2023-06-15 15:51:56.491 INFO (MainThread) [roborock.api] Roborock client disconnected
2023-06-15 15:51:56.491 DEBUG (MainThread) [roborock.local_api] Disconnecting from 192.168.31.232
2023-06-15 15:51:56.492 INFO (MainThread) [roborock.api] Roborock client disconnected
2023-06-15 15:51:56.492 DEBUG (MainThread) [roborock.local_api] Disconnecting from 192.168.31.232
2023-06-15 15:51:56.492 INFO (MainThread) [roborock.api] Roborock client disconnected
2023-06-15 15:51:56.493 DEBUG (MainThread) [roborock.local_api] Disconnecting from 192.168.31.232
2023-06-15 15:51:56.493 INFO (MainThread) [roborock.api] Roborock client disconnected
2023-06-15 15:51:56.511 INFO (MainThread) [roborock.local_api] Connected to 192.168.31.232
```

**Comment by derpate1989** [comment]
Same with q7

**Comment by wgumaa** [comment]
Same here S6

**Comment by elninosi** [comment]
Same issue with Roborock S7.

**Comment by AseKarlsson** [comment]
> > > > Not working at all, repeadly failed to connect. Had to rollback to 1.0.6
> > > 
> > > 
> > > How did you do the rollback? Tried Re-download and select version 1.0.6 but with no succeess.
> > 
> > 
> > I did it couple of times to let the downgrade work
> 
> Thanks, will test!

Worked fine, needed to do it twice!

**Comment by Lash-L** [comment]
I've marked the 1.0.7 release as a pre-release and put a note not to download it until we can figure out the cause.

For now, I'd downgrade to 1.0.6 if you have any problems

**Comment by mihaiturturica** [comment]
Same here, Roborock S6 Max.

**Comment by Freundlich** [comment]
Same here Roborock S7

**Comment by thomasadelhardt** [comment]
If you have installed through HACS, then this is how to downgrade:

1. Go to HACS
2. Go to Integrations
3. Select/Search for Roborock
4. Click the 3 ... dots
5. Select Redownload
6. Select 1.0.6 and download
7. Restart Home assistant

**Comment by JurajNyiri** [comment]
Came here from google by encountering this issue trying to use official HA roborock integration. 
Roborock S7 MaxV

Downloaded 1.0.8 from HACS, issue is resolved.

**Comment by poudenes** [comment]
Here installed 1.0.8 and everything working great. Off-topic: Can someone tell me how to use it with MQTT option?
Is this without login into the cloud?

**Comment by lxto** [comment]
1.0.8 works fine here too. I ' d be interessted in a documentation of the "without cloud" parameter. We're using a RR S8. 

Am 27. Juni 2023 20:57:57 MESZ schrieb Peter Oudenes ***@***.***>:

**Comment by isdedina** [comment]
I have Roborock S6 Max V, 1.0.8 works fine. 
1.0.9 and 1.0.10 is not working for me.
No device / entities. Also removed integration and added again, did not help.
Returned to 1.0.8., added again integration, 1.08 is working.

![roborock s6 maxV](https://github.com/humbertogontijo/homeassistant-roborock/assets/112246557/61e554e3-3220-4164-a1b5-03155dec92ee)

**Comment by Lash-L** [comment]
@isdedina can you please try 1.0.11 and a full restart of your Home Assistant instance? And if you are still having issues, please open a new ticket, you are having a seemingly different problem.
