### ISSUE TITLE
Integration not working on Roborock Q Revo

### ISSUE THREAD

**Issue by bchen290** [humbertogontijo/homeassistant-roborock#381]
## Version of the custom_component

1.0.6 on HA 2023.6.1

## What vacuum are you using?

Roborock Q Revo

## Describe the bug

When adding the vacuum, it would show up for 3 minutes before timing out and becoming unavailable and does not come back again. There's a few errors that shows up in the log.

## Debug log

```text
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/diagnostics/__init__.py", line 249, in get
    data = await info.config_entry_diagnostics(hass, config_entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/roborock/diagnostics.py", line 29, in async_get_config_entry_diagnostics
    "coordinators": {
                    ^
  File "/usr/src/homeassistant/homeassistant/components/roborock/diagnostics.py", line 32, in <dictcomp>
    coordinator.roborock_device_info.as_dict(), TO_REDACT_COORD
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/roborock/models.py", line 24, in as_dict
    "props": self.props.as_dict(),
             ^^^^^^^^^^^^^^^^^^
AttributeError: 'DeviceProp' object has no attribute 'as_dict'

Error fetching roborock data: id=26319 Timeout after 4 seconds

roborock: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 537, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/components/roborock/switch.py", line 151, in async_update
    self._attr_is_on = self.entity_description.evaluate_value(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/roborock/switch.py", line 69, in <lambda>
    evaluate_value=lambda data: data["status"] == 1,
                                ~~~~^^^^^^^^^^
TypeError: string indices must be integers, not 'str'

roborock: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 537, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/components/roborock/switch.py", line 151, in async_update
    self._attr_is_on = self.entity_description.evaluate_value(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/roborock/switch.py", line 55, in <lambda>
    evaluate_value=lambda data: data["lock_status"] == 1,
                                ~~~~^^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'

```

**Comment by Lash-L** [comment]
Hello - are you sure you're using the custom integration or the official. I haven't added diagnostics here and that's where the issue is

**Comment by bchen290** [comment]
Hello,

I am using the custom integration and I have attached the logs here

[home-assistant_roborock_2023-06-17T02-57-46.661Z.log](https://github.com/humbertogontijo/homeassistant-roborock/files/11777739/home-assistant_roborock_2023-06-17T02-57-46.661Z.log)

**Comment by Lash-L** [comment]
Hi you need to enable debug logging.

Also you definitely are using the core integration not the custom

**Comment by bchen290** [comment]
Oh sorry seems like it was in a funky state last night but it made me restart this morning but in the screenshot it shows custom integration and debug logging is enabled. I attached the logs that it downloaded

![image](https://github.com/humbertogontijo/homeassistant-roborock/assets/14852675/d0a87d23-2027-4941-8e2f-4831d3f3968a)

[home-assistant_roborock_2023-06-17T13-15-35.723Z.log](https://github.com/humbertogontijo/homeassistant-roborock/files/11779079/home-assistant_roborock_2023-06-17T13-15-35.723Z.log)

**Comment by Lash-L** [comment]
Can you go to services -> vacuum: send command
And then for the command put in 
get_dnd_timer

Then do the same for 
get_child_lock_status

**Comment by bchen290** [comment]
![image](https://github.com/humbertogontijo/homeassistant-roborock/assets/14852675/10bace11-ef83-4e00-900f-7aa8e23f4270)

I put in the command and click Call Service but doesn't seem to do anything. The button turns green but nothing happens and I did this for both commands. I enabled debug logging but nothing new is in there.

**Comment by Lash-L** [comment]
Search your debug log for "dnd" just to be safe, it should post something in there

**Comment by bchen290** [comment]
[home-assistant_roborock_2023-06-17T13-43-39.391Z.log](https://github.com/humbertogontijo/homeassistant-roborock/files/11779162/home-assistant_roborock_2023-06-17T13-43-39.391Z.log)

I have attached the debug logging. It would only show something after I reload the integration but seems like the notable part is:

```
2023-06-17 09:50:59.822 DEBUG (MainThread) [roborock.local_api] id=11897 Requesting method get_child_lock_status with None
2023-06-17 09:51:03.826 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'str' object has no attribute 'name'
Traceback (most recent call last):
  File "/config/custom_components/roborock/device.py", line 108, in send
    response = await self.coordinator.api.send_command(command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.11/site-packages/roborock/local_api.py", line 134, in send_command
    return (await self.send_message(roborock_message))[0]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.11/site-packages/roborock/local_api.py", line 184, in send_message
    return await self._send_message(roborock_messages)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.11/site-packages/roborock/local_api.py", line 179, in _send_message
    raise exception
  File "/config/deps/lib/python3.11/site-packages/roborock/local_api.py", line 147, in async_local_response
    (response, err) = await self._async_response(request_id, response_protocol)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.11/site-packages/roborock/api.py", line 192, in _async_response
    raise RoborockTimeout(f"id={request_id} Timeout after {QUEUE_TIMEOUT} seconds") from None
roborock.exceptions.RoborockTimeout: id=11897 Timeout after 4 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 452, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 685, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1910, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1950, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 811, in entity_service_call
    future.result()  # pop exception if have
    ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1034, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 851, in _handle_entity_call
    await result
  File "/config/custom_components/roborock/vacuum.py", line 539, in async_send_command
    return await self.send(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/roborock/device.py", line 111, in send
    f"Error while calling {command.name} with {params}"
                           ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'name'
2023-06-17 09:51:03.859 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140511444813328] Error handling message: Unknown error (unknown_error) Brian Chen from 162.158.155.95 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.43)
Traceback (most recent call last):
  File "/config/custom_components/roborock/device.py", line 108, in send
    response = await self.coordinator.api.send_command(command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.11/site-packages/roborock/local_api.py", line 134, in send_command
    return (await self.send_message(roborock_message))[0]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.11/site-packages/roborock/local_api.py", line 184, in send_message
    return await self._send_message(roborock_messages)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.11/site-packages/roborock/local_api.py", line 179, in _send_message
    raise exception
  File "/config/deps/lib/python3.11/site-packages/roborock/local_api.py", line 147, in async_local_response
    (response, err) = await self._async_response(request_id, response_protocol)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.11/site-packages/roborock/api.py", line 192, in _async_response
    raise RoborockTimeout(f"id={request_id} Timeout after {QUEUE_TIMEOUT} seconds") from None
roborock.exceptions.RoborockTimeout: id=11897 Timeout after 4 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 678, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1533, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 410, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 454, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 477, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 452, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 685, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1910, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1950, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 811, in entity_service_call
    future.result()  # pop exception if have
    ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1034, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 851, in _handle_entity_call
    await result
  File "/config/custom_components/roborock/vacuum.py", line 539, in async_send_command
    return await self.send(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/roborock/device.py", line 111, in send
    f"Error while calling {command.name} with {params}"
                           ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'name'
2023-06-17 09:51:04.320 DEBUG (MainThread) [roborock.local_api] id=31107 Requesting method RoborockCommand.GET_STATUS with None
2023-06-17 09:51:04.322 DEBUG (MainThread) [roborock.local_api] id=13682 Requesting method RoborockCommand.GET_DND_TIMER with None
2023-06-17 09:51:04.325 DEBUG (MainThread) [roborock.local_api] id=26624 Requesting method RoborockCommand.GET_CLEAN_SUMMARY with None
2023-06-17 09:51:04.326 DEBUG (MainThread) [roborock.local_api] id=24176 Requesting method RoborockCommand.GET_CONSUMABLE with None
```

**Comment by Lash-L** [comment]
Do you have a child lock/ a dnd setting in your app?

**Comment by bchen290** [comment]
I actually did set DND. It's currently not in DND mode but should that be disabled?

**Comment by Lash-L** [comment]
Ah I see the result for dnd timer was in your actualy log file. So that one is good.

Do you have child lock in your app?

**Comment by bchen290** [comment]
No I do not have child lock. Although in the app, it doesn't seem that I'm even able to enable it.

**Comment by Lash-L** [comment]
Are you having issues with the latest version?

**Comment by bchen290** [comment]
Hey it's still not working for me. I am on 1.0.8 now but I have this message
````
2023-07-11 21:03:37.836 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry *@gmail.com for roborock
--
Tue, Jul 11 2023 9:03:38 pm | Traceback (most recent call last):
Tue, Jul 11 2023 9:03:38 pm | File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
Tue, Jul 11 2023 9:03:38 pm | result = await component.async_setup_entry(hass, self)
Tue, Jul 11 2023 9:03:38 pm | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Tue, Jul 11 2023 9:03:38 pm | File "/config/custom_components/roborock/__init__.py", line 59, in async_setup_entry
Tue, Jul 11 2023 9:03:38 pm | home_data = await api_client.get_home_data(user_data)
Tue, Jul 11 2023 9:03:38 pm | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Tue, Jul 11 2023 9:03:38 pm | File "/config/deps/lib/python3.11/site-packages/roborock/api.py", line 565, in get_home_data
Tue, Jul 11 2023 9:03:38 pm | home_id_response = await home_id_request.request(
Tue, Jul 11 2023 9:03:38 pm | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Tue, Jul 11 2023 9:03:38 pm | File "/config/deps/lib/python3.11/site-packages/roborock/api.py", line 87, in request
Tue, Jul 11 2023 9:03:38 pm | async with session.request(
Tue, Jul 11 2023 9:03:38 pm | File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
Tue, Jul 11 2023 9:03:38 pm | self._resp = await self._coro
Tue, Jul 11 2023 9:03:38 pm | ^^^^^^^^^^^^^^^^
Tue, Jul 11 2023 9:03:38 pm | File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
Tue, Jul 11 2023 9:03:38 pm | conn = await self._connector.connect(
Tue, Jul 11 2023 9:03:38 pm | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Tue, Jul 11 2023 9:03:38 pm | File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
Tue, Jul 11 2023 9:03:38 pm | proto = await self._create_connection(req, traces, timeout)
Tue, Jul 11 2023 9:03:38 pm | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Tue, Jul 11 2023 9:03:38 pm | File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
Tue, Jul 11 2023 9:03:38 pm | _, proto = await self._create_direct_connection(req, traces, timeout)
Tue, Jul 11 2023 9:03:38 pm | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Tue, Jul 11 2023 9:03:38 pm | File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
Tue, Jul 11 2023 9:03:38 pm | transp, proto = await self._wrap_create_connection(
Tue, Jul 11 2023 9:03:38 pm | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Tue, Jul 11 2023 9:03:38 pm | File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
Tue, Jul 11 2023 9:03:38 pm | return await self._loop.create_connection(*args, **kwargs) # type: ignore[return-value] # noqa
Tue, Jul 11 2023 9:03:38 pm | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Tue, Jul 11 2023 9:03:38 pm | File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
Tue, Jul 11 2023 9:03:38 pm | sock = await self._connect_sock(
Tue, Jul 11 2023 9:03:38 pm | ^^^^^^^^^^^^^^^^^^^^^^^^^
Tue, Jul 11 2023 9:03:38 pm | File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
Tue, Jul 11 2023 9:03:38 pm | await self.sock_connect(sock, address)
Tue, Jul 11 2023 9:03:38 pm | File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
Tue, Jul 11 2023 9:03:38 pm | return await fut
Tue, Jul 11 2023 9:03:38 pm | ^^^^^^^^^
Tue, Jul 11 2023 9:03:38 pm | asyncio.exceptions.CancelledError
```

**Comment by Lash-L** [comment]
Try again? That's a strange error to have. Try again and let me know if it gives the same thing

**Comment by bchen290** [comment]
I think I'm having the same issue documented here: https://github.com/humbertogontijo/homeassistant-roborock/issues/144 as I'm running OPNsense and my app stopped working
