### ISSUE TITLE
Unsupported Operand Types

### ISSUE THREAD

**Issue by kbrown01** [humbertogontijo/homeassistant-roborock#405]
Seeing two errors in logs, one is:

Logger: roborock.api
Source: /srv/homeassistant/lib/python3.10/site-packages/roborock/api.py:233
First occurred: July 5, 2023 at 2:08:45 PM (41 occurrences)
Last logged: 10:22:32 AM

unsupported operand type(s) for 'in': 'int' and 'EnumMeta'
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.10/site-packages/roborock/api.py", line 226, in on_message_received
    elif data.payload and protocol in RoborockDataProtocol:
  File "/usr/lib/python3.10/enum.py", line 405, in __contains__
    raise TypeError(
TypeError: unsupported operand type(s) for 'in': 'int' and 'EnumMeta'

Second is possible related based on the count of errors:

Logger: custom_components.roborock.coordinator
Source: helpers/update_coordinator.py:229
Integration: Roborock ([documentation](https://github.com/humbertogontijo/homeassistant-roborock), [issues](https://github.com/humbertogontijo/homeassistant-roborock/issues))
First occurred: July 5, 2023 at 1:38:14 PM (49 occurrences)
Last logged: 10:25:04 AM

Error fetching roborock data: id=12652 Timeout after 4 seconds
Error fetching roborock data: id=24714 Timeout after 4 seconds
Error fetching roborock data: id=32220 Timeout after 4 seconds
Error fetching roborock data: id=30794 Timeout after 4 seconds
Error fetching roborock data: id=24421 Timeout after 4 seconds

**Comment by humbertogontijo** [comment]
Are you using v1.0.8?
Could you try main branch?

**Comment by nagydavid** [comment]
Same here for me as well:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/roborock/api.py", line 226, in on_message_received
    elif data.payload and protocol in RoborockDataProtocol:
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 739, in __contains__
    raise TypeError(
TypeError: unsupported operand type(s) for 'in': 'int' and 'EnumType'

I am using v.1.0.8

**Comment by kbrown01** [comment]
v.1.0.8 
Python version doesn;t look like it matters, I am still on 3.10 and @nagydavid is on 3.11

**Comment by joshuamckay** [comment]
Same here.

**Comment by humbertogontijo** [comment]
Is it fix in v1.0.9?
