### ISSUE TITLE
Roborock S7 disconnects after starting to clean

### ISSUE THREAD

**Issue by scripter13** [humbertogontijo/homeassistant-roborock#422]
I have created multiple scripts to start, wait, then set the vacuum to the required cleaning mode. There is a parent script that control the execution of these "mode" scripts. I have verified connectivity and HA control before starting any either the parent script or mode scripts. 
When a script is started, the vacuum starts and is configured correctly with the expected vacuum/mop mode. I then receive an error that HA is unable to communicate with the vacuum. 
When viewing trace:
(script.roboclean) turned on
Let <unknown entity> clean
Delay for 10 seconds
1 second later
(vacuum.roborock_s7) turned cleaning
9 seconds later
Change <unknown entity> option
Change <unknown entity> option
Call a service 'Vacuum: Set fan speed' on Roborock S7
Stopped because an error was encountered at July 22, 2023 at 6:24:57 PM (runtime: 14.30 seconds)
Error while calling SET_CUSTOM_MODE with [104]

I have attempted changing the param of the SET_CUSTOM_MODE to the numeric (104) and text (max) options, but the error still occurs. 

This error then stops the parent script that is running the script.roboclean mode script

## What vacuum are you using?

Roborock S7

## Describe the bug

When the vacuum begins cleaning, it disconnects from HA for over 4 seconds, which causes the script to error out. 

## Debug log

```text

Add your logs here.
[home-assistant_roborock_2023-07-23T00-25-59.394Z.log](https://github.com/humbertogontijo/homeassistant-roborock/files/12137448/home-assistant_roborock_2023-07-23T00-25-59.394Z.log)

```
Please let me know if those debug logs failed to attach correctly

**Comment by marek-vrana** [comment]
Changing fan speed via service call fails for me as well. Maybe it has someting to do with a recent firmware update? 
I own a Roborock S7 MaxV and my current firmware version is 02.58.40 where quick clean mode was added and the layout for changing modes got an additional Route option.

Despite the service call fails via HA, it sets a correct value to vacuum when checked in app, integration does not always keep the value up to date. I tried it with latest Roborock integration 1.0.11 and 1.0.10 - same results.

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/roborock/device.py:85
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 11:29:19 (2 occurrences)
Last logged: 11:45:27

[547053739456] Error while calling SET_CUSTOM_MODE with [105]
[546945101120] Error while calling SET_CUSTOM_MODE with [104]
Traceback (most recent call last):
  File "/config/custom_components/roborock/device.py", line 83, in send
    response = await self.api.send_command(method, params, return_type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/roborock/api.py", line 387, in send_command
    response = await cache.update_value(params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/roborock/api.py", line 137, in update_value
    response = await self.api._send_command(self.attribute.set_command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/roborock/cloud_api.py", line 207, in _send_command
    return await self.send_message(roborock_message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/roborock/cloud_api.py", line 185, in send_message
    (response, err) = await async_response
                      ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/roborock/api.py", line 321, in _wait_response
    raise RoborockTimeout(f"id={request_id} Timeout after {QUEUE_TIMEOUT} seconds") from None
roborock.exceptions.RoborockTimeout: id=17837 Timeout after 4 seconds

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/roborock/vacuum.py", line 385, in async_set_fan_speed
    await self.send(
  File "/config/custom_components/roborock/device.py", line 118, in send
    response = await super().send(method, params, return_type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/roborock/device.py", line 85, in send
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Error while calling SET_CUSTOM_MODE with [105]
```
