### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by eugenet8k** [humbertogontijo/homeassistant-roborock#43]
It was working well until v0.0.1

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/roborock/api.py:299 
Integration: Roborock (documentation, issues) 
First occurred: 6:34:50 PM (2 occurrences) 
Last logged: 6:36:17 PM

Error setting up entry Upstairs for roborock
Traceback (most recent call last):
```
  File "/Users/pi/.homeassistant-venv/lib/python3.9/site-packages/homeassistant/config_entries.py", line 372, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/Users/pi/.homeassistant/custom_components/roborock/__init__.py", line 37, in async_setup_entry
    home_data = await loop.run_in_executor(
  File "/usr/local/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/pi/.homeassistant/custom_components/roborock/api.py", line 346, in get_home_data
    header_clientid = self._get_header_client_id()
  File "/Users/pi/.homeassistant/custom_components/roborock/api.py", line 299, in _get_header_client_id
    md5.update(self._device_identifier.encode())
AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by humbertogontijo** [comment]
v0.0.1 have the passwordless config flow which is a breaking change. You need to remove and add the integration again

**Comment by eugenet8k** [comment]
Thank you @humbertogontijo , it works.
