### ISSUE TITLE
docker - HACS - roborock > not working

### ISSUE THREAD

**Issue by pan-sattan** [humbertogontijo/homeassistant-roborock#443]
Hello,

on non docker installation of Homeassistant its working perfectly.
But in Docker I cannot reach roborock integration - is added, but still make an initializing process....

![image](https://github.com/humbertogontijo/homeassistant-roborock/assets/59567959/a439b5c0-8fb4-4778-b12f-2bc264f30805)

ports 58866, 58867 are exposed on my router. Is necessary to do something in docker compose??

**Comment by artem-zinnatullin** [comment]
Similar issue, I'm running HA docker image `ghcr.io/home-assistant/home-assistant:2023.8.4` and after Roborock integration update through HACS it started crashing and reinstall doesn't help, also commented here https://github.com/humbertogontijo/homeassistant-roborock/issues/427#issuecomment-1696660166

```js
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/roborock/__init__.py", line 126, in async_setup_entry
    map_client.add_listener(data_coordinator.update_device)
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RoborockMqttClient' object has no attribute 'add_listener'
```

**Comment by humbertogontijo** [comment]
The official Roborock integration uses the same library. It could be some issue related to that. Is your HA core up to date?

**Comment by artem-zinnatullin** [comment]
Is HA core a python library? If so I can definitely check it if you know where to look

My and topic starter (I assume) HA is an official docker image `ghcr.io/home-assistant/home-assistant:2023.8.4`

**Comment by pan-sattan** [comment]
@artem-zinnatullin Hi, yes... I am using latest version of HA 
![Screenshot_20230902_211125_Home Assistant](https://github.com/humbertogontijo/homeassistant-roborock/assets/59567959/5288115b-e6e3-4fa0-b8ec-7b169d360256)

here is my docker compose

version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /hassio:/config
      - /etc/localtime:/etc/localtime:ro
      - ./swag/keys/letsencrypt:/ssl
      - /run/dbus:/run/dbus:ro # <-- Bluetooth adapter
    restart: unless-stopped
    privileged: true
    network_mode: host #swag
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=Europe/Prague #optional
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    
    ports:
      - 8123:8123  
      - 58866:58866
      - 58867:58867
