### ISSUE TITLE
Cleaning via automation runs on error

### ISSUE THREAD

**Issue by t-flow-sash** [humbertogontijo/homeassistant-roborock#482]
Using Roborock Custom integration latest version.

Vacuum is a Roborock S8.

Since a week all of a sudden my automations to clean e.g. at a time, via dashboard button or as a result of another automation it fails with the following error:
```

Logger: homeassistant.components.automation.vac_wohnbereich_kuche_saugen
Source: custom_components/roborock/device.py:86 
Integration: Automatisierung (documentation, issues) 
First occurred: 19. September 2023 um 22:53:39 (8 occurrences) 
Last logged: 06:18:50

VAC|Wohnbereich & Küche saugen: Error executing script. Unexpected error for call_service at pos 2: 'str' object has no attribute 'name'
While executing automation automation.vac_wohnbereich_kuche_saugen
Traceback (most recent call last):
  File "/config/custom_components/roborock/device.py", line 83, in send
    response = await self.api.send_command(method, params, return_type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/roborock/api.py", line 387, in send_command
    response = await cache.update_value(params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/roborock/api.py", line 137, in update_value
    response = await self.api._send_command(self.attribute.set_command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/roborock/cloud_api.py", line 207, in _send_command
    return await self.send_message(roborock_message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/roborock/cloud_api.py", line 185, in send_message
    (response, err) = await async_response
                      ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/roborock/api.py", line 321, in _wait_response
    raise RoborockTimeout(f"id={request_id} Timeout after {QUEUE_TIMEOUT} seconds") from None
roborock.exceptions.RoborockTimeout: id=11405 Timeout after 4 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 452, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 685, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1910, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1950, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 811, in entity_service_call
    future.result()  # pop exception if have
    ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1034, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 851, in _handle_entity_call
    await result
  File "/config/custom_components/roborock/vacuum.py", line 542, in async_send_command
    return await self.send(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/roborock/device.py", line 118, in send
    response = await super().send(method, params, return_type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/roborock/device.py", line 86, in send
    f"Error while calling {method.name} with {params}"
                           ^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'name'

```

The weird thing is: running the automation then a second or a third time suddenly works. 
Any help/fix is much appreciated.

**Comment by MikeDeltaHH** [comment]
I have the same error with one of my two roborock when i select rooms cleaning - zone cleanup works! The log brings the following message:

`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/roborock/device.py:86
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 14:52:59 (8 occurrences)
Last logged: 16:27:13

[139803417200576] 'str' object has no attribute 'name'
[139803076934720] 'str' object has no attribute 'name'
[139803176041792] 'str' object has no attribute 'name'
roborock.exceptions.VacuumError: (-10005, 'data for segment is not a number')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/roborock/device.py", line 83, in send
    response = await self.api.send_command(method, params, return_type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/roborock/api.py", line 389, in send_command
    response = await self._send_command(method, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/roborock/cloud_api.py", line 207, in _send_command
    return await self.send_message(roborock_message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/roborock/cloud_api.py", line 192, in send_message
    raise CommandVacuumError(method, err) from err
roborock.exceptions.CommandVacuumError: app_segment_clean: (-10005, 'data for segment is not a number')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 227, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1969, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2006, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/roborock/vacuum.py", line 542, in async_send_command
    return await self.send(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/roborock/device.py", line 118, in send
    response = await super().send(method, params, return_type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/roborock/device.py", line 86, in send
    f"Error while calling {method.name} with {params}"
                           ^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'name'`

**Comment by badmin-c** [comment]
I am getting the same error on an automation for my Roborock S4 Max.

Automation triggers when the following conditions are met:

All our mobile phones have been logged out of the Wi-Fi for more than 15 minutes
The automation has not run for at least 18 hours
Then the following actions are triggered:

Suction power is set to max
Various rooms are vacuumed
Wait until Roborock docks
Suction power is set back to Balanced


Automation always goes as far as setting suction power to MAX, but after that sometimes (e.g. every second or third time) it fails with

str’ object has no attribute ‘name’

I don't see a clear pattern, sometimes it works like 10 times in a row. When I test the automation in HA it always works as intended without any error. 

I am using default HACS Integration on a HA Green, everything up to date. Error exists for at least 6 months

Automation Code: https://pastebin.com/yx2TtFGU
Full Trace with error: https://pastebin.com/Xxngrb1R
