### ISSUE TITLE
Roborock Q7 Max - Room cleaning not working since a few days

### ISSUE THREAD

**Issue by MikeDeltaHH** [humbertogontijo/homeassistant-roborock#498]
## Version of the custom_component

1.0.12

## What vacuum are you using?

Roborock Q7 Max

I have defined several rooms and had zero problems with them for a few months - but since a few days the room cleaning does not work anymore without changing anything in the configuration - only with version 1.0.11 and also the update to 1.0.12 did not solve the problem. The zone cleaning works without problems but when I select one or more rooms via Rooms, two error messages appear immediately:

`Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:143
First occurred: 10:37:31 (3 occurrences)
Last logged: 10:52:12

Error doing job: Exception in callback RoborockFuture._resolve((None, VacuumError(-...not a number')))
Error doing job: Exception in callback RoborockFuture._resolve((None, VacuumError(-...s is invalid')))
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/site-packages/roborock/roborock_future.py", line 19, in _resolve
    self.fut.set_result(item)
asyncio.exceptions.InvalidStateError: invalid state`

`Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:226
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 10:37:31 (3 occurrences)
Last logged: 10:52:12

[139970109536448] 'str' object has no attribute 'name'
roborock.exceptions.VacuumError: (-10005, 'data for segments is invalid')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/roborock/device.py", line 83, in send
    response = await self.api.send_command(method, params, return_type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/roborock/api.py", line 404, in send_command
    response = await self._send_command(method, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/roborock/cloud_api.py", line 207, in _send_command
    return await self.send_message(roborock_message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/roborock/cloud_api.py", line 192, in send_message
    raise CommandVacuumError(method, err) from err
roborock.exceptions.CommandVacuumError: app_segment_clean: (-10005, 'data for segments is invalid')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2012, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2049, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/roborock/vacuum.py", line 542, in async_send_command
    return await self.send(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/roborock/device.py", line 118, in send
    response = await super().send(method, params, return_type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/roborock/device.py", line 86, in send
    f"Error while calling {method.name} with {params}"
                           ^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'name'`

A second Roborock (S5 Max) does not have this problem. I am a bit stumped and ask for support....

Thank you for this amazing plugin!

## Debug log
[home-assistant_roborock_2023-10-05T08-30-56.174Z.log](https://github.com/humbertogontijo/homeassistant-roborock/files/12816234/home-assistant_roborock_2023-10-05T08-30-56.174Z.log)

```

**Comment by Lash-L** [comment]
This error comes from the vacuum

roborock.exceptions.CommandVacuumError: app_segment_clean: (-10005, 'data for segments is invalid')


It means something is wrong in the data that was passed - something more than likely changed on your side(even if you don't realize it did) i.e. room names changed or the wrong map is selected or a map got cleared

**Comment by MikeDeltaHH** [comment]
Ok, I don't know what could have happened here.... is there a way to fix this? The map is the correct one, identical to the map in the Roborock app for the Q7 Max and I have already recreated the room config and assigned new names but without success.
