### ISSUE TITLE
Problem adding Robot. Login is OK, but can't find my Vacuum in account.

### ISSUE THREAD

**Issue by azafred** [humbertogontijo/homeassistant-roborock#503]
## Version of the custom_component
1.0.12

## What vacuum are you using?

S8 Pro Ultra
## Describe the bug
Unable to add vacuum. Upon entering the code I am receiving, I get a "No device found within your Roborock Account"

## Debug log

```text
2023-10-05 17:52:44.599 ERROR (MainThread) [custom_components.roborock.config_flow] wrong value type for field "rriot" - should be "roborock.containers.RRiot | None" instead of value "{'u': 'xxxxx', 's': 'xxx', 'h': 'xxx', 'k': 'Hhuo7Pfy', 'r': {'r': 'US', 'a': 'https://api-us.roborock.com', 'm': 'ssl://mqtt-us-2.roborock.com:8883', 'l': 'https://wood-us.roborock.com'}}" of type "dict"
Traceback (most recent call last):
  File "/config/custom_components/roborock/config_flow.py", line 228, in _code_login
    login_data = await self._client.code_login(code)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/roborock/api.py", line 660, in code_login
    return UserData.from_dict(user_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/roborock/containers.py", line 90, in from_dict
    return from_dict(cls, decamelize_obj(data, ignore_keys), config=Config(cast=[Enum]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dacite/core.py", line 68, in from_dict
    raise WrongTypeError(field_path=field.name, field_type=field.type, value=value)
dacite.exceptions.WrongTypeError: wrong value type for field "rriot" - should be "roborock.containers.RRiot | None" instead of value "{'u': 'xxxx', 's': 'xxxx', 'h': 'xxxx', 'k': 'Hhuo7Pfy', 'r': {'r': 'US', 'a': 'https://api-us.roborock.com', 'm': 'ssl://mqtt-us-2.roborock.com:8883', 'l': 'https://wood-us.roborock.com'}}" of type "dict"

```

**Comment by azafred** [comment]
Never mind. Found the problem. Govee is requiring an older dacite. Once bumped, everything works.
Cheers :)
