### ISSUE TITLE
No Camera Entity Available for S7 MAXV

### ISSUE THREAD

**Issue by HomeAssistantNewbie** [humbertogontijo/homeassistant-roborock#561]
### Discussed in https://github.com/humbertogontijo/homeassistant-roborock/discussions/556

<div type='discussions-op-text'>

<sup>Originally posted by **HomeAssistantNewbie** November 29, 2023</sup>
Hi,

First of all, thank you for the work on the integration, it's an incredible achievement.

I started HA yesterdy, and everything has worked correctly, except that when integrating Piotr Wachowski's card, there seems to be no camera entity and therefore the map can't be generated.

I've searched around and only found https://github.com/humbertogontijo/homeassistant-roborock/discussions/40#discussioncomment-4613706 but I believe the integration is already configured. However there's just no camera entity. I've reloaded a few times, but I have no idea where to go from here. Anybody have an idea?

Thanks in advance!

![image](https://github.com/humbertogontijo/homeassistant-roborock/assets/152271851/7695f662-ecfc-42f0-9bad-b98f0e69d7d7)
![image](https://github.com/humbertogontijo/homeassistant-roborock/assets/152271851/73a97c87-5443-4bf6-a933-dc6e1bdbae6c)
</div>

May be related, but not entirely sure. Robot responds to commands normally.

^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9e in position 1: invalid start byte
2023-11-28 22:26:06.930 ERROR (MainThread) [homeassistant.components.roborock.coordinator] Error fetching roborock data: id=19713 Timeout after 4 seconds
2023-11-28 22:53:27.220 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 332, in data_received
messages, upgraded, tail = self._request_parser.feed_data(data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
Bad status line "Invalid method encountered:\n\n b'MGLNDD_188.76.176.38_8123'\n ^"
2023-11-29 00:48:31.909 ERROR (MainThread) [metno] https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned 503
2023-11-29 00:48:31.910 ERROR (MainThread) [homeassistant.components.met] Error fetching met data: Update failed:
2023-11-29 03:39:57.734 ERROR (MainThread) [homeassistant.components.roborock.coordinator] Error fetching roborock data: Failed connecting to 10.0.0.11
2023-11-29 11:24:08.603 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback SsdpSearchResponder._send_responses(('10.0.0.23', 60483), [b'HTTP/1.1 20...ORG:1\r\n\r\n'])
Traceback (most recent call last):
File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
self._context.run(self._callback, *self._args)
File "/usr/local/lib/python3.11/site-packages/async_upnp_client/server.py", line 713, in _send_responses
self._response_socket.sendto(response, remote_addr)
OSError: [Errno 101] Network unreachable
2023-11-29 11:39:47.038 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 332, in data_received
messages, upgraded, tail = self._request_parser.feed_data(data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
Bad status line "Invalid method encountered:\n\n b'\x16\x03\x01'\n ^"
2023-11-29 13:41:23.721 ERROR (MainThread) [homeassistant.components.roborock.coordinator] Error fetching roborock data: id=18677 Timeout after 4 seconds

**Comment by dscarr10** [comment]
Be sure that you installed the Roborock integration through HACS and not the official roborock integration. They are functionally and visually similar,  the HACS version is more feature complete and is compatible with the map card you are trying to use.

**Comment by HomeAssistantNewbie** [comment]
Was indeed done, but ... magically solved itself without input on HA 23.12

**Comment by SkiBoard** [comment]
> Be sure that you installed the Roborock integration through HACS and not the official roborock integration. They are functionally and visually similar, the HACS version is more feature complete and is compatible with the map card you are trying to use.

Thanks so much - this fixed my exact issue!  For those looking at this now - this has the instructions you need to install the integration through HACS. https://github.com/humbertogontijo/homeassistant-roborock/blob/main/info.md
