### ISSUE TITLE
HA very slow after internet breakdown , duo homeassistant-roborock integration

### ISSUE THREAD

**Issue by Androo123nl** [humbertogontijo/homeassistant-roborock#576]
## Version of the custom_component

1.0.12

## What vacuum are you using?
Roborock S7 MaxV

## Describe the bug

Last week, my internet went down. But my HA went very slow for some reason.
After investigating, it seems that the RoboRock integration wants to connect that many times in a second, that my HA is very slow.

After disabling the roborock integration, HA went fast again as usual.
After enabling the integration again ( when online ) everything works fine.
When going offline again, HA is slow.
When disabling roborock integration ( and still offline ) everything works fine again.

## Debug log

```text

Add your logs here.

`Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 8:03:58 PM (1 occurrences)
Last logged: 8:03:58 PM

Error setting up entry ***********@gmail.com for roborock
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/roborock/init.py", line 108, in async_setup_entry
networking = await map_client.get_networking()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/roborock/api.py", line 513, in get_networking
return await self.send_command(RoborockCommand.GET_NETWORK_INFO, return_type=NetworkInfo)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/roborock/api.py", line 404, in send_command
response = await self._send_command(method, params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/roborock/cloud_api.py", line 207, in _send_command
return await self.send_message(roborock_message)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/roborock/cloud_api.py", line 170, in send_message
await self.validate_connection()
File "/usr/local/lib/python3.11/site-packages/roborock/api.py", line 326, in validate_connection
await self.async_connect()
File "/usr/local/lib/python3.11/site-packages/roborock/cloud_api.py", line 158, in async_connect
(connecting, connected_future) = self.sync_connect()
^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/roborock/cloud_api.py", line 143, in sync_connect
super().connect(host=self._mqtt_host, port=self._mqtt_port, keepalive=KEEPALIVE)
File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
return self.reconnect()
^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
sock = self._create_socket_connection()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/socket.py", line 827, in create_connection
for res in getaddrinfo(host, port, 0, SOCK_STREAM):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Try again`

`This error originated from a custom integration.

Logger: custom_components.roborock.camera
Source: custom_components/roborock/camera.py:244
Integration: Roborock (documentation, issues)
First occurred: 8:00:31 PM (4 occurrences)
Last logged: 8:05:36 PM

[Errno 101] Network unreachable
Traceback (most recent call last):
File "/config/custom_components/roborock/camera.py", line 244, in async_update
await self._handle_map_data()
File "/config/custom_components/roborock/camera.py", line 299, in _handle_map_data
map_data = await self.get_map(
^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/roborock/camera.py", line 270, in get_map
response = await self.async_map()
^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/roborock/camera.py", line 252, in async_map
map_v1 = await self.coordinator.map_api.get_map_v1()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/roborock/cloud_api.py", line 210, in get_map_v1
return await self.send_command(RoborockCommand.GET_MAP_V1)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/roborock/api.py", line 404, in send_command
response = await self._send_command(method, params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/roborock/cloud_api.py", line 207, in _send_command
return await self.send_message(roborock_message)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/roborock/cloud_api.py", line 170, in send_message
await self.validate_connection()
File "/usr/local/lib/python3.11/site-packages/roborock/api.py", line 326, in validate_connection
await self.async_connect()
File "/usr/local/lib/python3.11/site-packages/roborock/cloud_api.py", line 158, in async_connect
(connecting, connected_future) = self.sync_connect()
^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/roborock/cloud_api.py", line 143, in sync_connect
super().connect(host=self._mqtt_host, port=self._mqtt_port, keepalive=KEEPALIVE)
File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
return self.reconnect()
^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
sock = self._create_socket_connection()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
raise exceptions[0]
File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
sock.connect(sa)
OSError: [Errno 101] Network unreachable`

`Logger: homeassistant.helpers.entity
Source: helpers/entity.py:698
First occurred: 8:00:31 PM (4 occurrences)
Last logged: 8:05:36 PM

Update for camera.roborock_s7_maxv_map fails
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 698, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 959, in async_device_update
await self.async_update()
File "/config/custom_components/roborock/camera.py", line 247, in async_update
raise err
File "/config/custom_components/roborock/camera.py", line 244, in async_update
await self._handle_map_data()
File "/config/custom_components/roborock/camera.py", line 299, in _handle_map_data
map_data = await self.get_map(
^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/roborock/camera.py", line 270, in get_map
response = await self.async_map()
^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/roborock/camera.py", line 252, in async_map
map_v1 = await self.coordinator.map_api.get_map_v1()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/roborock/cloud_api.py", line 210, in get_map_v1
return await self.send_command(RoborockCommand.GET_MAP_V1)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/roborock/api.py", line 404, in send_command
response = await self._send_command(method, params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/roborock/cloud_api.py", line 207, in _send_command
return await self.send_message(roborock_message)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/roborock/cloud_api.py", line 170, in send_message
await self.validate_connection()
File "/usr/local/lib/python3.11/site-packages/roborock/api.py", line 326, in validate_connection
await self.async_connect()
File "/usr/local/lib/python3.11/site-packages/roborock/cloud_api.py", line 158, in async_connect
(connecting, connected_future) = self.sync_connect()
^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/roborock/cloud_api.py", line 143, in sync_connect
super().connect(host=self._mqtt_host, port=self._mqtt_port, keepalive=KEEPALIVE)
File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
return self.reconnect()
^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
sock = self._create_socket_connection()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
raise exceptions[0]
File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
sock.connect(sa)
OSError: [Errno 101] Network unreachable`

`and the last one:
This error originated from a custom integration.

Logger: custom_components.roborock.coordinator
Source: helpers/update_coordinator.py:332
Integration: Roborock (documentation, issues)
First occurred: 6:53:28 PM (3 occurrences)
Last logged: 8:06:06 PM

Error fetching roborock data: id=30673 Timeout after 4 seconds
Error fetching roborock data: Failed connecting to 192.168.1.76

where the 1.76 is the roborock itself.`

**Comment by peregrinus** [comment]
I have exactly the same issue. A flood of connections attempted and home assistant becomes unusable while hitting max CPU. There are quite a few integrations that seem to suffer this issue like the deluge one which also hasnt been resolved: https://github.com/home-assistant/core/issues/96528

**Comment by dochodges** [comment]
Also same issue. I had to disable the integration for now

**Comment by jgibson02** [comment]
Same issue

**Comment by tmkjchen** [comment]
Same issue. 

My roborock robot went offline by incident, and the integration created unlimited "roborock.cloud_api" connections.

After some tests, it seems to me that the problem occurs under the following situations:

1. account change. According to HA log, even after I change my roborock login account in roborock integration, it still polls devices in the old account. The unload code does not seem to take effect.
2. device offline. When the device is offline, "networking = await mqtt_client.get_networking()" raises error. However, I see nowhere it closes the RoborockMqttClient. HA calls async_setup_entry periodically, which continuously creates & leaks connection.

This is the source line mentioned above:
[roborock/__init__py#L94](https://github.com/home-assistant/core/blob/9d47e1983e0a7247790eda78ffaef14b80051bc7/homeassistant/components/roborock/__init__.py#L94)

**Comment by krzyk** [comment]
And same for me, I was wondering why HA is so slow today and restarts every 2 hours - issue was with this integration :(

**Comment by kamilk91** [comment]
Same here. 
![image](https://github.com/humbertogontijo/homeassistant-roborock/assets/26136300/3a983e6b-f211-4147-b665-3ea791d8d764)

**Comment by MikeDeltaHH** [comment]
The same with me - since yesterday evening the Interation has been reporting errors non-stop, after a few hours HA is virtually unusable and I have to switch the Intel NUC off and on again. In the Roborock app itself, both devices work without any problems...
Is there any help for this?

Logger: roborock.cloud_api
Source: /usr/local/lib/python3.11/site-packages/roborock/api.py:332
First occurred: 07:36:49 (72 occurrences)
Last logged: 07:39:26

[Roborock Q7 Max] A network protocol error occurred when communicating with the broker.
[Roborock S5 Max] A network protocol error occurred when communicating with the broker.

**Comment by MikeDeltaHH** [comment]
I deleted the integration and completely reintegrated it - everything was ok for a few minutes and now I get the same error messages again...

Logger: roborock.cloud_api
Source: /usr/local/lib/python3.11/site-packages/roborock/cloud_api.py:63
First occurrence: 07:36:49 (546 occurrences)
Last logged: 08:34:30
[Roborock Q7 Max] Connection failed (Unknown error.)
[Roborock S5 Max] Connection failed (Unknown error.)

Logger: roborock.cloud_api
Source: /usr/local/lib/python3.11/site-packages/roborock/api.py:332
First occurred: 07:36:49 (546 occurrences)
Last logged: 08:34:30
[Roborock Q7 Max] A network protocol error occurred while communicating with the broker.
[Roborock S5 Max] A network protocol error occurred while communicating with the broker.

**Comment by krzyk** [comment]
BTW. I had exact same issue with the built-int roborock integration. So it looks like the issue is maybe in home assistant itself?

**Comment by ABEIDO** [comment]
After 2024.3 release  i havent seen this issue occur, anyone else feels that i works better after last release?
