### ISSUE TITLE
Integration tries to connect to remote vacuum locally, fails set up

### ISSUE THREAD

**Issue by mrestorff** [humbertogontijo/homeassistant-roborock#583]
## What vacuum are you using?
- Roborock S7 Max Ultra (local)
- Roborock S5 Max (remote)

## Describe the bug

I have two vacuums set up in my account, one is a local one and the other is in another network.
On set up, the integration tries to connect to the remote vacuum (`[roborock.local_api] [Roborock S5 Max] Connecting to 10.20.107.xxx`) but of course fails to reach it.
It then fails setup entirely as it tries to set up the sensors for that vacuum.

## Debug log

```text

2024-01-13 17:22:06.016 DEBUG (MainThread) [roborock.local_api] [Roborock S5 Max] Connecting to 10.20.107.213
2024-01-13 17:22:10.017 DEBUG (MainThread) [roborock.local_api] [Roborock S5 Max] Connecting to 10.20.107.213
2024-01-13 17:22:14.020 DEBUG (MainThread) [roborock.local_api] [Roborock S5 Max] Connecting to 10.20.107.213
2024-01-13 17:22:18.021 DEBUG (MainThread) [roborock.local_api] [Roborock S5 Max] Connecting to 10.20.107.213
2024-01-13 17:22:18.025 DEBUG (MainThread) [custom_components.roborock.coordinator] Finished fetching roborock data in 16.040 seconds (success: False)
2024-01-13 17:22:18.201 ERROR (MainThread) [homeassistant.components.button] Error while setting up roborock platform for button
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/roborock/button.py", line 87, in async_setup_entry
    coordinator = device_entry_data["coordinator"]
                  ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-01-13 17:22:18.209 ERROR (MainThread) [homeassistant.components.camera] Error while setting up roborock platform for camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/roborock/camera.py", line 78, in async_setup_entry
    coordinator = device_entry_data["coordinator"]
                  ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-01-13 17:22:18.219 ERROR (MainThread) [homeassistant.components.number] Error while setting up roborock platform for number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/roborock/number.py", line 68, in async_setup_entry
    coordinator = device_entry_data["coordinator"]
                  ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

```

**Comment by noobey** [comment]
Same here.
Whats odd is that it continues to try to reconnect causing other issues in HA. I've disabled the integration for now.

**Comment by kamilk91** [comment]
It is funny because i have strange behaviour. 

Many times re-configured this library, and reinstalled with different versions after bug you mentioned @op, but it keeps failing. 
One time i reconfigured it started to work, i run kitchen cleaning (it is 10-15minutes) when he returned everything were unavailable.

**Comment by bvindmar** [comment]
Same here.. as @noobey noticed, the reconnecting integration makes the whole system laggy and unresponsive
