### ISSUE TITLE
Failed to set up

### ISSUE THREAD

**Issue by shivindera** [humbertogontijo/homeassistant-roborock#59]
![Screenshot_20221229-093914](https://user-images.githubusercontent.com/5311338/209925844-0fd03ce5-da91-4fce-8b51-dcfd7c4ab9b8.png)

Getting the below errors when trying to set it up for the first time. Using the latest version 0.0.9:

```
Logger: homeassistant.helpers.storage
Source: helpers/storage.py:254
First occurred: 09:35:47 (1 occurrences)
Last logged: 09:35:47

Error writing config for core.config_entries: Failed to serialize to JSON: /config/.storage/core.config_entries. Bad data at $.data.entries[33].data.user_data=<custom_components.roborock.api.containers.UserData object at 0xffff606fc430>(<class 'custom_components.roborock.api.containers.UserData'>
```

```
Logger: homeassistant.util.json
Source: util/json.py:88
First occurred: 09:35:47 (1 occurrences)
Last logged: 09:35:47

Failed to serialize to JSON: /config/.storage/core.config_entries. Bad data at $.data.entries[33].data.user_data=<custom_components.roborock.api.containers.UserData object at 0xffff606fc430>(<class 'custom_components.roborock.api.containers.UserData'>
```

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/roborock/api/containers.py:284
Integration: Roborock (documentation, issues)
First occurred: 09:35:46 (1 occurrences)
Last logged: 09:35:46

Error setting up entry Roborock for roborock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 372, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/roborock/__init__.py", line 32, in async_setup_entry
    home_data = HomeData(await api_client.get_home_data(user_data))
  File "/config/custom_components/roborock/api/api.py", line 392, in get_home_data
    rriot = user_data.rriot
  File "/config/custom_components/roborock/api/containers.py", line 284, in rriot
    return RRiot(self.data.get(UserDataField.RRIOT))
AttributeError: 'UserData' object has no attribute 'get'
```

**Comment by shivindera** [comment]
Works fine when using v0.0.8

**Comment by Xyaren** [comment]
Duplicate of #58

**Comment by toollu** [comment]
can confirm this

**Comment by Aaronhrndz** [comment]
Mine shows the same behavior

**Comment by humbertogontijo** [comment]
New release 0.0.10 should fix it

**Comment by shivindera** [comment]
Update fixed the issue.
