### ISSUE TITLE
ValueError: 16383 is not a valid VacuumEntityFeature

### ISSUE THREAD

**Issue by MartinTerp** [humbertogontijo/homeassistant-roborock#6]
Just installed the intergration, logged in and i can see in the logs that it fails with:

`[31m2022-12-09 11:26:03.873 ERROR (MainThread) [homeassistant.components.vacuum] Error while setting up roborock platform for vacuum 
Traceback (most recent call last): 
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform 
    await asyncio.gather(*pending) 
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities 
    await asyncio.gather(*tasks) 
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 605, in _async_add_entity 
    capabilities=entity.capability_attributes, 
  File "/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py", line 213, in capability_attributes 
    if self.supported_features & VacuumEntityFeature.FAN_SPEED: 
  File "/config/custom_components/roborock/vacuum.py", line 100, in supported_features 
    return VacuumEntityFeature(features) 
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__ 
    return cls.__new__(cls, value) 
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__ 
    raise ve_exc 
ValueError: 16383 is not a valid VacuumEntityFeature[0m `

Im from EU, using Roborock S7

**Comment by humbertogontijo** [comment]
Should be fixed now

**Comment by humbertogontijo** [comment]
Closing as complete. Feel free to create a new one if it persists
