### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by superpower10** [humbertogontijo/homeassistant-roborock#614]
## Version of the custom_component
1.0.13

## What vacuum are you using?
S7 MaxV Ultra

## Describe the bug
Integration stopped working. In the normal Log all kind of sensor can‘t be set up. 

## Debug log
Just a few examples:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 350, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/roborock/vacuum.py", line 201, in async_setup_entry
    coordinator = device_entry_data["coordinator"]
                  ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

Or

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 350, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/roborock/time.py", line 136, in async_setup_entry
    coordinators = [device_entry_data["coordinator"] for device_entry_data in domain_data.get("devices").values()]
                    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

Or

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 350, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/roborock/switch.py", line 109, in async_setup_entry
    coordinators = [device_entry_data["coordinator"] for device_entry_data in domain_data.get("devices").values()]
                    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable


## Further information
Multiple restarts of HA didn’t change anything about it


2024-04-02 08:59:43.252 DEBUG (Thread-15 (_thread_main)) [roborock.cloud_api] [Jürgen Cleansmann] Received PUBLISH (d0, q0, r0, m0), 'rr/m/o/5kOmUYiE2L9VqdxE1ltPcb/6e641156/jWlG1iFnE5580eojFBf21', properties=[], ... (71 bytes)
2024-04-02 08:59:43.253 DEBUG (Thread-15 (_thread_main)) [roborock.cloud_api] [Jürgen Cleansmann] Got device update for battery: 69
2024-04-02 08:59:43.253 DEBUG (Thread-15 (_thread_main)) [roborock.cloud_api] [Jürgen Cleansmann] Got status update(battery) before get_status was called.
2024-04-02 08:59:59.279 DEBUG (Thread-15 (_thread_main)) [roborock.cloud_api] [Jürgen Cleansmann] Sending PINGREQ
2024-04-02 08:59:59.337 DEBUG (Thread-15 (_thread_main)) [roborock.cloud_api] [Jürgen Cleansmann] Received PINGRESP
2024-04-02 08:59:59.949 DEBUG (MainThread) [roborock.cloud_api] [Jürgen Cleansmann] id=16574 Requesting method get_consumable with []
2024-04-02 08:59:59.950 DEBUG (MainThread) [roborock.cloud_api] [Jürgen Cleansmann] Sending PUBLISH (d0, q0, r0, m11), 'b'rr/m/i/5kOmUYiE2L9VqdxE1ltPcb/6e641156/jWlG1iFnE5580eojFBf21'', properties=None, ... (215 bytes)
2024-04-02 08:59:59.950 DEBUG (MainThread) [roborock.cloud_api] [Jürgen Cleansmann] id=17572 Requesting method get_status with []
2024-04-02 08:59:59.951 DEBUG (MainThread) [roborock.cloud_api] [Jürgen Cleansmann] Sending PUBLISH (d0, q0, r0, m12), 'b'rr/m/i/5kOmUYiE2L9VqdxE1ltPcb/6e641156/jWlG1iFnE5580eojFBf21'', properties=None, ... (199 bytes)
2024-04-02 09:00:00.315 DEBUG (MainThread) [roborock.cloud_api] [Jürgen Cleansmann] id=16574 Response from get_consumable: {'main_brush_work_time': 754205, 'side_brush_work_time': 26702, 'filter_work_time': 197764, 'filter_element_work_time': 0, 'sensor_dirty_time': 73054, 'strainer_work_times': 118, 'dust_collection_work_times': 321, 'cleaning_brush_work_times': 118}
2024-04-02 09:00:00.401 DEBUG (Thread-15 (_thread_main)) [roborock.cloud_api] [Jürgen Cleansmann] Received PUBLISH (d0, q0, r0, m0), 'rr/m/o/5kOmUYiE2L9VqdxE1ltPcb/6e641156/jWlG1iFnE5580eojFBf21', properties=[], ... (983 bytes)
2024-04-02 09:00:00.404 DEBUG (MainThread) [roborock.cloud_api] [Jürgen Cleansmann] id=17572 Response from get_status: {'msg_ver': 2, 'msg_seq': 447, 'state': 8, 'battery': 69, 'clean_time': 3057, 'clean_area': 33980000, 'error_code': 0, 'map_present': 1, 'in_cleaning': 0, 'in_returning': 0, 'in_fresh_state': 1, 'lab_status': 3, 'water_box_status': 1, 'back_type': -1, 'wash_phase': 0, 'wash_ready': 0, 'fan_power': 103, 'dnd_enabled': 0, 'map_status': 3, 'is_locating': 0, 'lock_status': 0, 'water_box_mode': 201, 'water_box_carriage_status': 1, 'mop_forbidden_enable': 1, 'camera_status': 423, 'is_exploring': 0, 'home_sec_status': 0, 'home_sec_enable_password': 1, 'adbumper_status': [0, 0, 0], 'water_shortage_status': 0, 'dock_type': 3, 'dust_collection_status': 0, 'auto_dust_collection': 1, 'avoid_count': 254, 'mop_mode': 300, 'debug_mode': 0, 'collision_avoid_status': 1, 'switch_map_mode': 0, 'dock_error_status': 0, 'charge_status': 1, 'unsave_map_reason': 0, 'unsave_map_flag': 0, 'clean_percent': 0}
2024-04-02 09:00:00.743 DEBUG (MainThread) [roborock.cloud_api] [Jürgen Cleansmann] id=10246 Requesting method get_wash_towel_mode with []
2024-04-02 09:00:00.743 DEBUG (MainThread) [roborock.cloud_api] [Jürgen Cleansmann] Sending PUBLISH (d0, q0, r0, m13), 'b'rr/m/i/5kOmUYiE2L9VqdxE1ltPcb/6e641156/jWlG1iFnE5580eojFBf21'', properties=None, ... (215 bytes)
2024-04-02 09:00:00.746 DEBUG (MainThread) [roborock.cloud_api] [Jürgen Cleansmann] id=28058 Requesting method get_smart_wash_params with []
2024-04-02 09:00:00.746 DEBUG (MainThread) [roborock.cloud_api] [Jürgen Cleansmann] Sending PUBLISH (d0, q0, r0, m14), 'b'rr/m/i/5kOmUYiE2L9VqdxE1ltPcb/6e641156/jWlG1iFnE5580eojFBf21'', properties=None, ... (215 bytes)
2024-04-02 09:00:00.747 DEBUG (MainThread) [roborock.cloud_api] [Jürgen Cleansmann] id=11736 Requesting method get_dust_collection_mode with []
2024-04-02 09:00:00.747 DEBUG (MainThread) [roborock.cloud_api] [Jürgen Cleansmann] Sending PUBLISH (d0, q0, r0, m15), 'b'rr/m/i/5kOmUYiE2L9VqdxE1ltPcb/6e641156/jWlG1iFnE5580eojFBf21'', properties=None, ... (215 bytes)
2024-04-02 09:00:00.916 DEBUG (Thread-15 (_thread_main)) [roborock.cloud_api] [Jürgen Cleansmann] Received PUBLISH (d0, q0, r0, m0), 'rr/m/o/5kOmUYiE2L9VqdxE1ltPcb/6e641156/jWlG1iFnE5580eojFBf21', properties=[], ... (103 bytes)
2024-04-02 09:00:00.918 DEBUG (MainThread) [roborock.cloud_api] [Jürgen Cleansmann] id=10246 Response from get_wash_towel_mode: {'wash_mode': 1}
2024-04-02 09:00:00.945 DEBUG (Thread-15 (_thread_main)) [roborock.cloud_api] [Jürgen Cleansmann] Received PUBLISH (d0, q0, r0, m0), 'rr/m/o/5kOmUYiE2L9VqdxE1ltPcb/6e641156/jWlG1iFnE5580eojFBf21', properties=[], ... (103 bytes)
2024-04-02 09:00:00.948 DEBUG (MainThread) [roborock.cloud_api] [Jürgen Cleansmann] id=11736 Response from get_dust_collection_mode: {'mode': 0}
2024-04-02 09:00:00.949 DEBUG (Thread-15 (_thread_main)) [roborock.cloud_api] [Jürgen Cleansmann] Received PUBLISH (d0, q0, r0, m0), 'rr/m/o/5kOmUYiE2L9VqdxE1ltPcb/6e641156/jWlG1iFnE5580eojFBf21', properties=[], ... (135 bytes)
2024-04-02 09:00:00.951 DEBUG (MainThread) [roborock.cloud_api] [Jürgen Cleansmann] id=28058 Response from get_smart_wash_params: {'smart_wash': 0, 'wash_interval': 1200}

**Comment by macsatcom** [comment]
I am suddenly seeing the same issue, after it has been working for months both for my S5 and S6.

**Comment by zach-ovic** [comment]
Same here. Anybody has solution to this?

**Comment by kankadev** [comment]
Same issue

**Comment by 108085** [comment]
Got a new Qrevo S, worked one day, the next day I got  this error. 
Also got a S6 MaxV and it was working "for years" now.
I'm on 1.0.14
