### ISSUE TITLE
Roborock Integration not working on Home Assistant Core 2024.5.4

### ISSUE THREAD

**Issue by guanaco0403** [humbertogontijo/homeassistant-roborock#640]
<!-- Before you open a new issue, search through the existing issues to see if others have had the same problem.

Issues not containing the minimum requirements will be closed:

- Issues without a description (using the header is not good enough) will be closed.

## Version of the custom_component

am using the latest version avaible on HACS

## What vacuum are you using?
Roborock S7

## Describe the bug

the roborock integration doesnt setup at HA boot anymore + makes crash HA after a few hours
it spams errors in the log file

```text

[home-assistant_2024-05-19T15-00-17.677Z.log](https://github.com/humbertogontijo/homeassistant-roborock/files/15401485/home-assistant_2024-05-19T15-00-17.677Z.log)


```

**Comment by guanaco0403** [comment]
[home-assistant_2024-05-19T15-00-17.677Z.log](https://github.com/humbertogontijo/homeassistant-roborock/files/15401514/home-assistant_2024-05-19T15-00-17.677Z.log)
it didnt upload correctly

**Comment by simonepittis** [comment]
+1 

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 575, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/roborock/__init__.py", line 88, in async_setup_entry
    device_network.update(await get_local_devices_info())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/roborock/__init__.py", line 162, in get_local_devices_info
    discovered_devices = await RoborockProtocol(timeout=10).discover()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/roborock/protocol.py", line 66, in discover
    await asyncio.sleep(self.timeout)
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 665, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

**Comment by ifflanb** [comment]
Yes I believe I am seeing HA crash when the Roborock vacuum is running. I don't have any proof of this. Just seems very coincidental at this stage.

**Comment by jacobwaage** [comment]
+1 

hope this will be fixed asap ☺️

**Comment by isthevao** [comment]
I had the same problem after the update, but today it was able to connect and is working properly. Maybe it was on the roborock side.

**Comment by machielkreiken** [comment]
Same here. Setup failing since last update.

**Comment by HarsiTomiii** [comment]
Same here. Since last update, setup failing.

**Comment by Dillton** [comment]
I am running HA Core 2024.5.4 for 4 days now and have no problem at all.

**Comment by RacerEdge** [comment]
But what else could it be?
I uninstalled the integration, reboot HAS and installed the integration.
Login data are accepted but initialization failed.

Any ideas ?

**Comment by guanaco0403** [comment]
its a problem with the code they need to fix it

**Comment by RacerEdge** [comment]
ok, so the only thing we can do is wait and hope. :-)

**Comment by bobzer** [comment]
or you can contribute either by code, probable reason for the crash. or simply buy a coffee, it take a lot of time and effort to maintain and it's done on the family time.

**Comment by HarsiTomiii** [comment]
> Same here. Since last update, setup failing. on 2024.5.5
> 
> edit: added version, since this is a different thread

so I did some cleaning and reinstall.

1. I removed the roborock integration, then restart home assistant
2. I reinstalled the roborock hacs integration, then restart home assistant
3. I reinstalled the xiaomi map extractor hacs integration, then restart home assistant
4. I reinstalled the roborock integration, it asked for login, authorization etc and then it works again

I am on 2024.5.5, Roborock S7, Roborock custom integration + xiaomi map extractor

**Comment by Lash-L** [comment]
Hi everyone - for those of you still having issues, I recommend you disable the integration for a day and then switch to the core integration.

I do not have the time to maintain both the custom integration and the core integration. I barely have enough time to maintain the core integration by itself. And I believe @humbertogontijo does not have the time either for the custom integration

**Comment by guanaco0403** [comment]
Oh they are not the same ? @Lash-L

**Comment by guanaco0403** [comment]
I taught they were soo i just remove it and then use the ha one ?

**Comment by Lash-L** [comment]
> Oh they are not the same ? @Lash-L 

No

**Comment by RacerEdge** [comment]
How is the way to install it ?

**Comment by japper83** [comment]
Removing the hacs intergration, restart HA. Then reinstall and reauthenticate fixed it for me.

**Comment by Eidolf** [comment]
> Removing the hacs intergration, restart HA. Then reinstall and reauthenticate fixed it for me. 

Also for me, good Tip.

**Comment by jacobwaage** [comment]
Thanks for the tip. But one drawback in the HA-integration: there is no “Clean segment” option… and no “Go to coordinates “…Den 31. maj 2024 kl. 12.56 skrev Eidolf ***@***.***>:﻿

Removing the hacs intergration, restart HA. Then reinstall and reauthenticate fixed it for me.

Also for me, good Tip.

**Comment by Lash-L** [comment]
Both of these exist. Just use the vacuum send command service

app_segment_clean

app_goto_target

**Comment by RacerEdge** [comment]
After setup with a W11 PC and not with my MAC-Book it works!

**Comment by r77s** [comment]
> > Same here. Since last update, setup failing. on 2024.5.5
> > edit: added version, since this is a different thread
> 
> so I did some cleaning and reinstall.
> 
> 1. I removed the roborock integration, then restart home assistant
> 2. I reinstalled the roborock hacs integration, then restart home assistant
> 3. I reinstalled the xiaomi map extractor hacs integration, then restart home assistant
> 4. I reinstalled the roborock integration, it asked for login, authorization etc and then it works again
> 
> I am on 2024.5.5, Roborock S7, Roborock custom integration + xiaomi map extractor

Thank you for your tip, but in version 2024.6.3 it doesn't work for me with the Roborock S8. Has anyone managed to do this with the current Home Assistant version?

**Comment by cpsskipper** [comment]
> > > Same here. Since last update, setup failing. on 2024.5.5
> > > edit: added version, since this is a different thread
> > 
> > 
> > so I did some cleaning and reinstall.
> > 
> > 1. I removed the roborock integration, then restart home assistant
> > 2. I reinstalled the roborock hacs integration, then restart home assistant
> > 3. I reinstalled the xiaomi map extractor hacs integration, then restart home assistant
> > 4. I reinstalled the roborock integration, it asked for login, authorization etc and then it works again
> > 
> > I am on 2024.5.5, Roborock S7, Roborock custom integration + xiaomi map extractor
> 
> Thank you for your tip, but in version 2024.6.3 it doesn't work for me with the Roborock S8. Has anyone managed to do this with the current Home Assistant version?

I do it instruction step by step in version 2024.6.4.  It works

**Comment by HarsiTomiii** [comment]
> > > > Same here. Since last update, setup failing. on 2024.5.5
> > > > edit: added version, since this is a different thread
> > > 
> > > 
> > > so I did some cleaning and reinstall.
> > > 
> > > 1. I removed the roborock integration, then restart home assistant
> > > 2. I reinstalled the roborock hacs integration, then restart home assistant
> > > 3. I reinstalled the xiaomi map extractor hacs integration, then restart home assistant
> > > 4. I reinstalled the roborock integration, it asked for login, authorization etc and then it works again
> > > 
> > > I am on 2024.5.5, Roborock S7, Roborock custom integration + xiaomi map extractor
> > 
> > 
> > Thank you for your tip, but in version 2024.6.3 it doesn't work for me with the Roborock S8. Has anyone managed to do this with the current Home Assistant version?
> 
> I do it instruction step by step in version 2024.6.4. It works

glad to hear!
strange that the same steps don't work for others...

since my post previously i had a few updates to core, and it still works without issue.

**Comment by hotmachina** [comment]
Hope this helps. This is the error message I am receiving:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/roborock/containers.py", line 124, in convert_to_class_obj
    converted_value = class_type(value)
  File "/usr/local/lib/python3.13/enum.py", line 726, in __call__
    raise TypeError(
            f"{cls} has no members; specify `names=()` if you meant to create a new, empty, enum"
            )
TypeError: <enum 'RoborockMopModeCode'> has no members; specify `names=()` if you meant to create a new, empty, enum
