### ISSUE TITLE
[Roborock S8 Pro Ultra] Detected that custom integration 'roborock' calls async_write_ha_state

### ISSUE THREAD

**Issue by w1Ngx** [humbertogontijo/homeassistant-roborock#641]
Hi,

I am getting the following error in the log. Version 1.0.13 used

Logger: roborock.cloud_api
Source: /usr/local/lib/python3.12/site-packages/roborock/api.py:326
First occurred: 12:39:48 PM (4 occurrences)
Last logged: 1:06:36 PM

[Roborock S8 Pro Ultra] Detected that custom integration 'roborock' calls async_write_ha_state from a thread at custom_components/roborock/device.py, line 129: self.async_write_ha_state(). Please report it to the author of the 'roborock' custom integration.
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/roborock/api.py", line 283, in on_message_received
    listener(status)
  File "/config/custom_components/roborock/device.py", line 129, in _update_from_listener
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1008, in async_write_ha_state
    self.hass.verify_event_loop_thread("async_write_ha_state")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'roborock' calls async_write_ha_state from a thread at custom_components/roborock/device.py, line 129: self.async_write_ha_state(). Please report it to the author of the 'roborock' custom integration.

**Comment by liamlain** [comment]
same after updated core 2024.6.2

```Logger: roborock.cloud_api
Source: /usr/local/lib/python3.12/site-packages/roborock/api.py:326
First occurred: 12:27:33 AM (1 occurrences)
Last logged: 12:27:33 AM

[Roborock S8 MaxV Ultra] Detected that custom integration 'roborock' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/roborock/device.py, line 129: self.async_write_ha_state(). Please report it to the author of the 'roborock' custom integration.
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/roborock/api.py", line 283, in on_message_received
    listener(status)
  File "/config/custom_components/roborock/device.py", line 129, in _update_from_listener
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 999, in async_write_ha_state
    self.hass.verify_event_loop_thread("async_write_ha_state")
  File "/usr/src/homeassistant/homeassistant/core.py", line 447, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 159, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 197, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'roborock' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/roborock/device.py, line 129: self.async_write_ha_state(). Please report it to the author of the 'roborock' custom integration.```

**Comment by SlightlyGrumpyArchitect** [comment]
I am seeing this on 2024.6.3 as well:

```
2024-06-17 19:47:45.678 WARNING (Thread-3 (_thread_main)) [homeassistant.helpers.frame] Detected that custom integration 'roborock' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/roborock/device.py, line 129: self.async_write_ha_state(), please report it to the author of the 'roborock' custom integration
2024-06-17 19:47:45.679 ERROR (Thread-3 (_thread_main)) [roborock.cloud_api] [Roborock S5 Max] Detected that custom integration 'roborock' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/roborock/device.py, line 129: self.async_write_ha_state(). Please report it to the author of the 'roborock' custom integration.
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/roborock/api.py", line 283, in on_message_received
listener(status)
File "/config/custom_components/roborock/device.py", line 129, in _update_from_listener
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 999, in async_write_ha_state
self.hass.verify_event_loop_thread("async_write_ha_state")
File "/usr/src/homeassistant/homeassistant/core.py", line 447, in verify_event_loop_thread
frame.report(
File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 159, in report
_report_integration(what, integration_frame, level, error_if_integration)
File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 197, in _report_integration
raise RuntimeError(
RuntimeError: Detected that custom integration 'roborock' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/roborock/device.py, line 129: self.async_write_ha_state(). Please report it to the author of the 'roborock' custom integration.
```

Let me know if you require extra information/logs

**Comment by kuchar91** [comment]
Is this project abandoned?

**Comment by Lash-L** [comment]
There is a note in the readme, it's recommended you use the core integration. PRs are accepted but all of my time goes towards adding more features and bug fixes for the core integration, not the custom

**Comment by w1Ngx** [comment]
What is the easiest way to migrate from this one to core?

**Comment by Lash-L** [comment]
Uninstall it from hacs, restart and then you can just install it like a normal integration

**Comment by kuchar91** [comment]
Have you already include your calibration points in core integration?

**Comment by j0sp0r** [comment]
I can also confirm, I still have this issue. Always when my Robo is offline or not reachable, HA crashes after some time when the plugin is on and active.
