### ISSUE TITLE
no devices

### ISSUE THREAD

**Issue by texta83** [humbertogontijo/homeassistant-roborock#642]
Unfortunately, with this integration no devices are displayed in the HA.
I have already uninstalled, rebooted and reinstalled everything.
With the original integration it finds my four devices.
What could be the error here?

It worked with this one until 2 weeks ago.

**Comment by Smdst07** [comment]
Same here with s7+...

**Comment by r77s** [comment]
Same here with S8

**Comment by r77s** [comment]
> Unfortunately, with this integration no devices are displayed in the HA. I have already uninstalled, rebooted and reinstalled everything. With the original integration it finds my four devices. What could be the error here?
> 
> It worked with this one until 2 weeks ago.

Which roborock do you have? If I try to connect with the orig. integration. I get the code via mail, but also find no devices.

**Comment by texta83** [comment]
hi
i have two 5s, q7max, 8qmax
original works and hacs no devices

**Comment by r77s** [comment]
> hi
> i have two 5s, q7max, 8qmax
> original works and hacs no devices
> 

What do you mean by original? In the roborock app?

**Comment by texta83** [comment]
yes the roborock app in HA

**Comment by Highjack77** [comment]
Same for me, Installed it two weeks ago, it was working and since 2 days, all entities are unavailable, I uninstalled and reinstalled, and have no entities at all now :-(

**Comment by r77s** [comment]
I found something. I use the Govee addon for LED stribes etc. When I deactive this addon, the roborock addon works. When I activate the Govee addon again the roborock addon failed to load with the following error message:
`Logger: homeassistant.setup
Quelle: setup.py:320
Erstmals aufgetreten: 09:46:44 (1 Vorkommnisse)
Zuletzt protokolliert: 09:46:44

Setup failed for custom integration 'roborock': Unable to import component: No module named 'imp'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 320, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1012, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 992, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1052, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 131, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/roborock/__init__.py", line 10, in <module>
    from roborock.api import RoborockApiClient
  File "/usr/local/lib/python3.12/site-packages/roborock/api.py", line 60, in <module>
    from .protocol import Utils
  File "/usr/local/lib/python3.12/site-packages/roborock/protocol.py", line 12, in <module>
    from construct import (  # type: ignore
  File "/usr/local/lib/python3.12/site-packages/construct/__init__.py", line 22, in <module>
    from construct.core import *
  File "/usr/local/lib/python3.12/site-packages/construct/core.py", line 3, in <module>
    import struct, io, binascii, itertools, collections, pickle, sys, os, tempfile, hashlib, importlib, imp
ModuleNotFoundError: No module named 'imp'`

**Comment by bobloadmire** [comment]
Anything we can do to assist fixing this? I enabled debug logging and refreshed the integration, and oddly I don't see any logs in Core?

**Comment by Lash-L** [comment]
I recommend swapping to the core integration. I do not spend time working on this integration and neither does the other contributor - so all updates come from others who are typically doing small things. I do frequently and regular updates on the core version

**Comment by jlogan223** [comment]
> I recommend swapping to the core integration. I do not spend time working on this integration and neither does the other contributor - so all updates come from others who are typically doing small things. I do frequently and regular updates on the core version

Where do we find the core version?
