### ISSUE TITLE
Integration won't load / how can I swap to core integration?

### ISSUE THREAD

**Issue by tbgoose** [humbertogontijo/homeassistant-roborock#662]
Looking to swap to core integration as suggested on the git. As of a few days ago this integration is no longer working for me. But how do I do that?

## Version of the custom_component
1.0.13

## What vacuum are you using?
S6 Pure

## Describe the bug

Device no longer loads. When I go to add roborock to HA only this one comes up, can't see any core integration...

## Error log

```
![Screenshot_20241013-210936](https://github.com/user-attachments/assets/f262b37c-ec85-4d8b-8214-131345067d6f)
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 9:02:20 PM (2 occurrences)
Last logged: 9:06:22 PM

Error setting up entry xxxx for roborock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/roborock/__init__.py", line 88, in async_setup_entry
    device_network.update(await get_local_devices_info())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/roborock/__init__.py", line 162, in get_local_devices_info
    discovered_devices = await RoborockProtocol(timeout=10).discover()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/roborock/protocol.py", line 65, in discover
    self.transport, _ = await loop.create_datagram_endpoint(lambda: self, local_addr=("0.0.0.0", 58866))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1423, in create_datagram_endpoint
    raise exceptions[0]
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1407, in create_datagram_endpoint
    sock.bind(local_address)
OSError: [Errno 98] Address in use

```

**Comment by PierreB40** [comment]
To swap to core integration you have to uninstall custom integration from HACS first
Then install the core one from settings > devices and services > integrations > add integrations
Or directly from here : https://www.home-assistant.io/integrations/roborock/
