### ISSUE TITLE
Line causes log warning and errors due to "blocking call"

### ISSUE THREAD

**Issue by dagobert** [humbertogontijo/homeassistant-roborock#663]
The following line is doing a blocking call not wanted by HASS.

https://github.com/humbertogontijo/homeassistant-roborock/blob/af31d3ece7dec747a519b3bd87386833f380cf00/custom_components/roborock/__init__.py#L103

Log warning

```
2024-10-15 11:22:03.392 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_default_certs with args (<ssl.SSLContext object at 0x7f88de939550>,) inside the event loop by custom integration 'roborock' at custom_components/roborock/__init__.py, line 103: map_client = RoborockMqttClient(user_data, device_info) (offender: /usr/local/lib/python3.12/site-packages/paho/mqtt/client.py, line 806: context.load_default_certs()), please create a bug report at https://github.com/humbertogontijo/homeassistant-roborock/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/roborock/__init__.py", line 103, in async_setup_entry
    map_client = RoborockMqttClient(user_data, device_info)
```

Fix is replacing the line by:

`            map_client = await hass.async_add_executor_job(RoborockMqttClient, user_data, device_info)`

I will create a Pull request...

**Comment by Tozapid** [comment]
Looks like I have the same issue, thank you for the Pull request

**Comment by Lash-L** [comment]
Merged and sent out a new release

**Comment by Tozapid** [comment]
Hm, I still can't connect, but the error is less informative for now

```
15:32:48.341 INFO (Thread-14 (_thread_main)) [roborock.cloud_api] [robo] Roborock client disconnected
2024-10-16 15:32:48.341 WARNING (Thread-14 (_thread_main)) [roborock.cloud_api] [robo] A network protocol error occurred when communicating with the broker.
2024-10-16 15:32:48.343 DEBUG (MainThread) [roborock.cloud_api] [robo] Connecting to mqtt
2024-10-16 15:32:48.482 DEBUG (MainThread) [roborock.cloud_api] [robo] Sending CONNECT (u1, p1, wr0, wq0, wf0, c1, k60) client_id=0UXdHVK2FMbsuloFJ4votX properties=None
2024-10-16 15:32:52.483 DEBUG (Thread-14 (_thread_main)) [roborock.cloud_api] [robo] Sending CONNECT (u1, p1, wr0, wq0, wf0, c1, k60) client_id=0UXdHVK2FMbsuloFJ4votX properties=None
2024-10-16 15:32:52.527 DEBUG (Thread-14 (_thread_main)) [roborock.cloud_api] [robo] Received CONNACK (0, Not authorized) properties=[]
2024-10-16 15:32:52.527 ERROR (Thread-14 (_thread_main)) [roborock.cloud_api] [robo] Failed to connect (Unknown error.)
2024-10-16 15:32:52.527 INFO (Thread-14 (_thread_main)) [roborock.cloud_api] [robo] Roborock client disconnected
```

**Comment by dagobert** [comment]
> Hm, I still can't connect, but the error is less informative for now
> 
> ```
> 15:32:48.341 INFO (Thread-14 (_thread_main)) [roborock.cloud_api] [robo] Roborock client disconnected
> 2024-10-16 15:32:48.341 WARNING (Thread-14 (_thread_main)) [roborock.cloud_api] [robo] A network protocol error occurred when communicating with the broker.
> 2024-10-16 15:32:48.343 DEBUG (MainThread) [roborock.cloud_api] [robo] Connecting to mqtt
> 2024-10-16 15:32:48.482 DEBUG (MainThread) [roborock.cloud_api] [robo] Sending CONNECT (u1, p1, wr0, wq0, wf0, c1, k60) client_id=0UXdHVK2FMbsuloFJ4votX properties=None
> 2024-10-16 15:32:52.483 DEBUG (Thread-14 (_thread_main)) [roborock.cloud_api] [robo] Sending CONNECT (u1, p1, wr0, wq0, wf0, c1, k60) client_id=0UXdHVK2FMbsuloFJ4votX properties=None
> 2024-10-16 15:32:52.527 DEBUG (Thread-14 (_thread_main)) [roborock.cloud_api] [robo] Received CONNACK (0, Not authorized) properties=[]
> 2024-10-16 15:32:52.527 ERROR (Thread-14 (_thread_main)) [roborock.cloud_api] [robo] Failed to connect (Unknown error.)
> 2024-10-16 15:32:52.527 INFO (Thread-14 (_thread_main)) [roborock.cloud_api] [robo] Roborock client disconnected
> ```

I don't think this has anything to do with this issue. I just updated to the new version and everything works fine.
