### ISSUE TITLE
Version 1.0.14 fails to initialize on HA startup

### ISSUE THREAD

**Issue by Roukanken42** [humbertogontijo/homeassistant-roborock#666]
## Version of the custom_component
1.0.14

## What vacuum are you using?
S6 MaxV

## Describe the bug

Integrations fails to start on start of Home Assistant. Only 1.0.14 does this, downgrading to 1.0.13 fixes the issue. Seems like it imports some module that doesn't exist... I tried switching between the two versions several times via HACS's install, and it's consistent in this.

## Debug log

```text
Setup failed for custom integration 'roborock': Unable to import component: No module named 'roborock.web_api'

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/roborock/__init__.py", line 10, in <module>
    from roborock.web_api import RoborockApiClient
ModuleNotFoundError: No module named 'roborock.web_api'
```

**Comment by mike8206** [comment]
Facing the same problem. 

This version occupied all memory and the core process was killed.
After removing roborock folder and restarting the core, the HA is normally startup now.

**Comment by fdreckmann** [comment]
Same Here

**Comment by jeffgoh** [comment]
I had  same problem with 1.0.14 - reverting to 1.0.13 works again for me

> ## Version of the custom_component
> 1.0.14
> 
> ## What vacuum are you using?
> S6 MaxV
> 
> ## Describe the bug
> Integrations fails to start on start of Home Assistant. Only 1.0.14 does this, downgrading to 1.0.13 fixes the issue. Seems like it imports some module that doesn't exist... I tried switching between the two versions several times via HACS's install, and it's consistent in this.
> 
> ## Debug log
> ```
> Setup failed for custom integration 'roborock': Unable to import component: No module named 'roborock.web_api'
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
>     component = await integration.async_get_component()
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
>     self._component_future.result()
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
>     comp = await self.hass.async_add_import_executor_job(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
>     ComponentProtocol, importlib.import_module(self.pkg_path)
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
>     return func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
>   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
>   File "/config/custom_components/roborock/__init__.py", line 10, in <module>
>     from roborock.web_api import RoborockApiClient
> ModuleNotFoundError: No module named 'roborock.web_api'
> ```
