### ISSUE TITLE
Integration Not loading 

### ISSUE THREAD

**Issue by fdreckmann** [humbertogontijo/homeassistant-roborock#667]
## Version of the custom_component
1.0.14

## What vacuum are you using?
 Qrevo master 

## Describe the bug

Integration Not started

## Debug log
                        
```text

Add your logs here.

Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 6:58:16 PM (2 occurrences)
Last logged: 6:59:13 PM

Error setting up entry dreckmann.florian@gmail.com for roborock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/roborock/__init__.py", line 88, in async_setup_entry
    device_network.update(await get_local_devices_info())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/roborock/__init__.py", line 159, in get_local_devices_info
    discovered_devices = await RoborockProtocol(timeout=10).discover()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/roborock/protocol.py", line 65, in discover
    self.transport, _ = await loop.create_datagram_endpoint(lambda: self, local_addr=("0.0.0.0", 58866))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1423, in create_datagram_endpoint
    raise exceptions[0]
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1407, in create_datagram_endpoint
    sock.bind(local_address)
OSError: [Errno 98] Address in use

```

**Comment by alsmaison** [comment]
Same issue for me

**Comment by greee82** [comment]
Same issue for me. I have Roborock s7 Pro Ultra too.
