### ISSUE TITLE
Detected blocking call to load_default_certs with args

### ISSUE THREAD

**Issue by wiedwo** [humbertogontijo/homeassistant-roborock#668]
Got following in HA systemlog:
2024-10-22 16:38:41.269 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_default_certs with args (<ssl.SSLContext object at 0x7f46cf36d0>,) inside the event loop by custom integration 'roborock' at custom_components/roborock/__init__.py, line 103: map_client = RoborockMqttClient(user_data, device_info) (offender: /usr/local/lib/python3.12/site-packages/paho/mqtt/client.py, line 806: context.load_default_certs()), please create a bug report at https://github.com/humbertogontijo/homeassistant-roborock/issues

**Comment by wiedwo** [comment]
Additional Traceback:
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs
Traceback (most recent call last):
  File "", line 198, in _run_module_as_main
  File "", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in 
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/roborock/__init__.py", line 103, in async_setup_entry
    map_client = RoborockMqttClient(user_data, device_info)

**Comment by ytugarev** [comment]
+1. Roborock Dyad Pro Combo - built in integration

`Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: 8:53:26 PM (1 occurrences)
Last logged: 8:53:26 PM

Detected blocking call to load_default_certs with args (<ssl.SSLContext object at 0xffff899ea720>,) inside the event loop by integration 'roborock' at homeassistant/components/roborock/__init__.py, line 236: mqtt_client = RoborockMqttClientA01( (offender: /usr/local/lib/python3.13/site-packages/paho/mqtt/client.py, line 806: context.load_default_certs()), please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+roborock%22 For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.13/asyncio/base_events.py", line 708, in run_until_complete self.run_forever() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 679, in run_forever self._run_once() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2027, in _run_once handle._run() File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/components/roborock/__init__.py", line 152, in setup_device return await setup_device_a01(hass, user_data, device, product_info) File "/usr/src/homeassistant/homeassistant/components/roborock/__init__.py", line 236, in setup_device_a01 mqtt_client = RoborockMqttClientA01(`
