### ISSUE TITLE
'RoborockMqttClient' object has no attribute 'get_networking'

### ISSUE THREAD

**Issue by FerronN** [humbertogontijo/homeassistant-roborock#674]
## Version of the custom_component
1.0.14

## What vacuum are you using?
Roborock S8

## Describe the bug
Failure during initialization. I tried moving to the core implementation. That one works, but I'm missing crucial information in that integration. I can't read the current room the vacuum is in :(

## Debug log

```
AttributeError: 'RoborockMqttClient' object has no attribute 'get_networking'
2024-12-09 23:38:32.889 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry <account email> for roborock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/roborock/__init__.py", line 108, in async_setup_entry
    networking = await map_client.get_networking()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RoborockMqttClient' object has no attribute 'get_networking'
```

**Comment by FerronN** [comment]
I've setup a devcontainer environment and there it just works. I can't determine why this is yet.
The `device_network` property is missing from the config entries file within my prod environment.

So, this could point towards the problem. Putting this manually in the config entries of the prod environment doesn't make a difference unfortunately.

**Comment by FerronN** [comment]
I've found the problem :)

The core roborock component uses a much newer version of `python-roborock` (2.70.2). This version doesn't include all methods called by the component in this repository. The requirements of this package in the core component take precedent over the the custom one, which it shouldn't. I will create a ticket in the home assistant core repo and share it.

**Comment by FerronN** [comment]
https://github.com/home-assistant/core/issues/132887
