### ISSUE TITLE
Unexpected exception importing platform custom_components.roborock.vacuum

### ISSUE THREAD

**Issue by eugenet8k** [humbertogontijo/homeassistant-roborock#7]
I have two vacuums on my Roborock account. I noticed the integration was created only for one of them (the first from the list).

```
Logger: homeassistant.loader
Source: custom_components/roborock/vacuum.py:66 
Integration: Roborock ([documentation](https://github.com/humbertogontijo/homeassistant-roborock), [issues](https://github.com/humbertogontijo/homeassistant-roborock/issues)) 


Unexpected exception importing platform custom_components.roborock.vacuum
Traceback (most recent call last):
  File "/Users/pi/.homeassistant-venv/lib/python3.9/site-packages/homeassistant/loader.py", line 728, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/Users/pi/.homeassistant-venv/lib/python3.9/site-packages/homeassistant/loader.py", line 745, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/pi/.homeassistant/custom_components/roborock/vacuum.py", line 55, in <module>
    class RoborockVacuum(StateVacuumEntity):
  File "/Users/pi/.homeassistant/custom_components/roborock/vacuum.py", line 66, in RoborockVacuum
    def send(self, command: str, params: list | None = None):
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

```
Logger: homeassistant.setup
Source: setup.py:338 


Unable to prepare setup for platform roborock.vacuum: Platform not found (Exception importing custom_components.roborock.vacuum).
```

Everything is latest

```
Home Assistant 2022.12.0
Frontend 20221207.0 - latest
```

I am using HomeAssistant Core at macOS, the  Python is  3.9.15, also I updated to `6eef389` for this component before seeing this error.

**Comment by humbertogontijo** [comment]
Could you check if its fixed now?
