### ISSUE TITLE
'NoneType' object cannot be interpreted as an integer (datetime)

### ISSUE THREAD

**Issue by shred86** [humbertogontijo/homeassistant-roborock#72]
Looking through my HA logs after the integration has been running for several hours, I noticed there's cases where the "API" didn't return a value so `None` was sent to the sensor and the lambda function for `parse_datetime_time` is failing.

I noticed a [check was added](https://github.com/humbertogontijo/homeassistant-roborock/blob/287f612223170b88e10ff54c6ec8ffba37d590e6/custom_components/roborock/sensor.py#L270) to catch this but I think if `native_value` is `None` in this case, won't `_handle_coordinator_update` just return `None` (python default)? I'm wondering if we need an `else` statement for certain sensors (time related) to return the previous value, or do we modify the lambda function to just check for `None` types and display Unknown for the device state.

Also, I'm wondering if it would be better to catch these on the "API" side so the integration doesn't have to worry about the catching these errors?

````
2022-12-30 11:44:48.373 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved:   File "/usr/local/python/bin/hass", line 8, in <module>
    sys.exit(main())
  File "/usr/local/python/lib/python3.10/site-packages/homeassistant/__main__.py", line 202, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/local/python/lib/python3.10/site-packages/homeassistant/runner.py", line 120, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/python/lib/python3.10/asyncio/base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "/usr/local/python/lib/python3.10/asyncio/base_events.py", line 595, in run_forever
    self._run_once()
  File "/usr/local/python/lib/python3.10/asyncio/base_events.py", line 1873, in _run_once
    handle._run()
  File "/usr/local/python/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/python/lib/python3.10/site-packages/homeassistant/helpers/event.py", line 1326, in run_action
    hass.async_run_hass_job(job, utc_point_in_time)
  File "/usr/local/python/lib/python3.10/site-packages/homeassistant/core.py", line 580, in async_run_hass_job
    return self.async_add_hass_job(hassjob, *args)
  File "/usr/local/python/lib/python3.10/site-packages/homeassistant/core.py", line 483, in async_add_hass_job
    task = self.loop.create_task(hassjob.target(*args))
Traceback (most recent call last):
  File "/usr/local/python/lib/python3.10/site-packages/homeassistant/helpers/update_coordinator.py", line 168, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/local/python/lib/python3.10/site-packages/homeassistant/helpers/update_coordinator.py", line 316, in _async_refresh
    self.async_update_listeners()
  File "/usr/local/python/lib/python3.10/site-packages/homeassistant/helpers/update_coordinator.py", line 121, in async_update_listeners
    update_callback()
  File "/config/custom_components/roborock/sensor.py", line 268, in _handle_coordinator_update
    native_value = self._determine_native_value()
  File "/config/custom_components/roborock/sensor.py", line 291, in _determine_native_value
    native_value = self.entity_description.value(native_value)
  File "/config/custom_components/roborock/sensor.py", line 61, in <lambda>
    value=lambda values: parse_datetime_time(time(hour=values[0], minute=values[1])),
TypeError: 'NoneType' object cannot be interpreted as an integer
````

````
2022-12-30 12:43:28.370 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved:   File "/usr/local/python/bin/hass", line 8, in <module>
    sys.exit(main())
  File "/usr/local/python/lib/python3.10/site-packages/homeassistant/__main__.py", line 202, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/local/python/lib/python3.10/site-packages/homeassistant/runner.py", line 120, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/python/lib/python3.10/asyncio/base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "/usr/local/python/lib/python3.10/asyncio/base_events.py", line 595, in run_forever
    self._run_once()
  File "/usr/local/python/lib/python3.10/asyncio/base_events.py", line 1873, in _run_once
    handle._run()
  File "/usr/local/python/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/python/lib/python3.10/site-packages/homeassistant/helpers/event.py", line 1326, in run_action
    hass.async_run_hass_job(job, utc_point_in_time)
  File "/usr/local/python/lib/python3.10/site-packages/homeassistant/core.py", line 580, in async_run_hass_job
    return self.async_add_hass_job(hassjob, *args)
  File "/usr/local/python/lib/python3.10/site-packages/homeassistant/core.py", line 483, in async_add_hass_job
    task = self.loop.create_task(hassjob.target(*args))
Traceback (most recent call last):
  File "/usr/local/python/lib/python3.10/site-packages/homeassistant/helpers/update_coordinator.py", line 168, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/local/python/lib/python3.10/site-packages/homeassistant/helpers/update_coordinator.py", line 316, in _async_refresh
    self.async_update_listeners()
  File "/usr/local/python/lib/python3.10/site-packages/homeassistant/helpers/update_coordinator.py", line 121, in async_update_listeners
    update_callback()
  File "/config/custom_components/roborock/sensor.py", line 268, in _handle_coordinator_update
    native_value = self._determine_native_value()
  File "/config/custom_components/roborock/sensor.py", line 291, in _determine_native_value
    native_value = self.entity_description.value(native_value)
  File "/config/custom_components/roborock/sensor.py", line 61, in <lambda>
    value=lambda values: parse_datetime_time(time(hour=values[0], minute=values[1])),
TypeError: 'NoneType' object cannot be interpreted as an integer
````

**Comment by humbertogontijo** [comment]
This is probably fixed now
