### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 8: invalid continuation byte

### ISSUE THREAD

**Issue by shred86** [humbertogontijo/homeassistant-roborock#76]
Receiving several of these when my vacuum was doing a segment cleaning (vacuum & mop) of two rooms. This is the S7 MaxV Ultra. I did open the app several times while it was cleaning but not sure if that's related to this. I'll have to pay closer attention next time to see if I can figure out when it's occurring. Log messages below with some entires leading up to the specific UnicodeDecodeErrors:

````
2022-12-31 03:54:38.489 DEBUG (MainThread) [custom_components.roborock.api.api] id=1614 Response from get_status: {'msg_ver': 2, 'msg_seq': 3070, 'state': 18, 'battery': 94, 'clean_time': 688, 'clean_area': 15505000, 'error_code': 0, 'map_present': 1, 'in_cleaning': 3, 'in_returning': 0, 'in_fresh_state': 0, 'lab_status': 1, 'water_box_status': 1, 'back_type': -1, 'wash_phase': 0, 'wash_ready': 0, 'fan_power': 102, 'dnd_enabled': 0, 'map_status': 3, 'is_locating': 0, 'lock_status': 0, 'water_box_mode': 203, 'water_box_carriage_status': 1, 'mop_forbidden_enable': 1, 'camera_status': 3457, 'is_exploring': 0, 'home_sec_status': 0, 'home_sec_enable_password': 0, 'adbumper_status': [0, 0, 0], 'water_shortage_status': 0, 'dock_type': 3, 'dust_collection_status': 0, 'auto_dust_collection': 1, 'avoid_count': 0, 'mop_mode': 300, 'debug_mode': 0, 'collision_avoid_status': 1, 'switch_map_mode': 0, 'dock_error_status': 0, 'charge_status': 1, 'unsave_map_reason': 0, 'unsave_map_flag': 0}
2022-12-31 03:54:38.490 DEBUG (MainThread) [custom_components.roborock.api.api] id=1615 Response from get_dnd_timer: {'start_hour': 22, 'start_minute': 0, 'end_hour': 7, 'end_minute': 0, 'enabled': 1}
2022-12-31 03:54:38.550 DEBUG (MainThread) [custom_components.roborock.api.api] id=1616 Response from get_clean_summary: {'clean_time': 71223, 'clean_area': 1105407500, 'clean_count': 29, 'dust_collection_count': 23, 'records': [1672284539, 1672018069, 1671833299, 1671762562, 1671735384, 1671649255, 1671636991, 1671562835, 1671476643, 1671399986, 1671305160, 1671158013, 1671142561, 1671043136, 1670986322, 1670957168, 1670723771, 1670711593, 1670511909, 1670511768]}
2022-12-31 03:54:38.551 DEBUG (MainThread) [custom_components.roborock.api.api] id=1617 Response from get_consumable: {'main_brush_work_time': 71223, 'side_brush_work_time': 71223, 'filter_work_time': 71223, 'filter_element_work_time': 0, 'sensor_dirty_time': 71223, 'strainer_work_times': 61, 'dust_collection_work_times': 23, 'cleaning_brush_work_times': 61}
2022-12-31 03:54:38.553 DEBUG (MainThread) [custom_components.roborock.api.api] id=1618 Requesting method get_clean_record with [1672284539]
2022-12-31 03:54:38.832 DEBUG (MainThread) [custom_components.roborock.api.api] id=1618 Response from get_clean_record: {'begin': 1672284539, 'end': 1672285908, 'duration': 1233, 'area': 20672500, 'error': 0, 'complete': 1, 'start_type': 2, 'clean_type': 3, 'finish_reason': 56, 'dust_collection_status': 1, 'avoid_count': 34, 'wash_count': 2, 'map_flag': 0}
2022-12-31 03:54:38.832 DEBUG (MainThread) [custom_components.roborock] Finished fetching roborock data in 0.513 seconds (success: True)
2022-12-31 03:54:39.710 ERROR (MainThread) [custom_components.roborock.api.api] 'utf-8' codec can't decode byte 0xe7 in position 8: invalid continuation byte
Traceback (most recent call last):
  File "/config/custom_components/roborock/api/api.py", line 156, in on_message
    if endpoint.decode().startswith(self._endpoint):
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 8: invalid continuation byte
````

````
2022-12-31 03:54:55.647 DEBUG (MainThread) [custom_components.roborock.camera] Retrieving map from Roborock MQTT
2022-12-31 03:54:55.647 DEBUG (MainThread) [custom_components.roborock.api.api] id=1622 Requesting method get_map_v1 with None
2022-12-31 03:54:56.117 DEBUG (MainThread) [custom_components.roborock.api.api] id=1622 Response from get_map_v1: 634675 bytes
2022-12-31 03:54:57.268 DEBUG (MainThread) [custom_components.roborock.camera] Map data retrieved
2022-12-31 03:54:57.269 DEBUG (MainThread) [custom_components.roborock.camera] Map is ok
2022-12-31 03:54:57.284 WARNING (MainThread) [asyncio] Executing <Task finished name='Task-13496' coro=<VacuumCameraMap.async_update() done, defined at /config/custom_components/roborock/camera.py:161> result=None created at /usr/local/python/lib/python3.10/site-packages/homeassistant/core.py:515> took 1.168 seconds
2022-12-31 03:54:57.426 ERROR (MainThread) [custom_components.roborock.api.api] 'utf-8' codec can't decode byte 0xf8 in position 8: invalid start byte
Traceback (most recent call last):
  File "/config/custom_components/roborock/api/api.py", line 156, in on_message
    if endpoint.decode().startswith(self._endpoint):
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 8: invalid start byte
````

````
2022-12-31 03:58:47.569 DEBUG (MainThread) [custom_components.roborock.api.api] Unknown data point number received 122 with 91
2022-12-31 03:58:50.880 DEBUG (MainThread) [custom_components.roborock.camera] Retrieving map from Roborock MQTT
2022-12-31 03:58:50.880 DEBUG (MainThread) [custom_components.roborock.api.api] id=1709 Requesting method get_map_v1 with None
2022-12-31 03:58:51.391 DEBUG (MainThread) [custom_components.roborock.api.api] id=1709 Response from get_map_v1: 635878 bytes
2022-12-31 03:58:52.582 DEBUG (MainThread) [custom_components.roborock.camera] Map data retrieved
2022-12-31 03:58:52.582 DEBUG (MainThread) [custom_components.roborock.camera] Map is ok
2022-12-31 03:58:52.598 WARNING (MainThread) [asyncio] Executing <Task finished name='Task-14284' coro=<VacuumCameraMap.async_update() done, defined at /config/custom_components/roborock/camera.py:161> result=None created at /usr/local/python/lib/python3.10/site-packages/homeassistant/core.py:515> took 1.207 seconds
2022-12-31 03:58:54.414 ERROR (MainThread) [custom_components.roborock.api.api] 'utf-8' codec can't decode byte 0xd4 in position 8: invalid continuation byte
Traceback (most recent call last):
  File "/config/custom_components/roborock/api/api.py", line 156, in on_message
    if endpoint.decode().startswith(self._endpoint):
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 8: invalid continuation byte
````

````
2022-12-31 04:03:00.987 DEBUG (MainThread) [custom_components.roborock.api.api] id=1799 Requesting method get_map_v1 with None
2022-12-31 04:03:01.449 DEBUG (MainThread) [custom_components.roborock.api.api] id=1799 Response from get_map_v1: 637128 bytes
2022-12-31 04:03:02.764 DEBUG (MainThread) [custom_components.roborock.camera] Map data retrieved
2022-12-31 04:03:02.764 DEBUG (MainThread) [custom_components.roborock.camera] Map is ok
2022-12-31 04:03:02.780 WARNING (MainThread) [asyncio] Executing <Task finished name='Task-15117' coro=<VacuumCameraMap.async_update() done, defined at /config/custom_components/roborock/camera.py:161> result=None created at /usr/local/python/lib/python3.10/site-packages/homeassistant/core.py:515> took 1.331 seconds
2022-12-31 04:03:05.090 ERROR (MainThread) [custom_components.roborock.api.api] 'utf-8' codec can't decode byte 0xc3 in position 8: invalid continuation byte
Traceback (most recent call last):
  File "/config/custom_components/roborock/api/api.py", line 156, in on_message
    if endpoint.decode().startswith(self._endpoint):
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 8: invalid continuation byte
````

**Comment by shred86** [comment]
Other observations looking at the logs from yesterday. I think this was around the time I started the cleaning from the Roborock app, but I noticed these log entires:

````
2022-12-31 03:40:42.814 DEBUG (MainThread) [custom_components.roborock.api.api] Unknown data point number received 120 with 0
2022-12-31 03:40:42.888 DEBUG (MainThread) [custom_components.roborock.api.api] Remote control 18
2022-12-31 03:40:42.888 DEBUG (MainThread) [custom_components.roborock.api.api] Unknown data point number received 128 with 1
2022-12-31 03:40:57.688 DEBUG (MainThread) [custom_components.roborock.api.api] Remote control 26
2022-12-31 03:40:57.689 DEBUG (MainThread) [custom_components.roborock.api.api] Unknown data point number received 128 with 3
````

I was also thinking, for the UnicodeDecodeErrors, maybe we can use a `try:` block at [line 156](https://github.com/humbertogontijo/homeassistant-roborock/blob/287f612223170b88e10ff54c6ec8ffba37d590e6/custom_components/roborock/api/api.py#L156) and catch the `UnicodeDecodeError` to print out the raw bytes. At least that way it's logged and perhaps we can try to decode it using something other than utf-8?

**Comment by Lash-L** [comment]
@shred86 I assume you are no longer getting these errors?

**Comment by shred86** [comment]
I haven't seen these errors in a while but I honestly haven't been looking very closely. I'll go ahead and close it though and if it reappears, I'll just create a new issue.
